import { Router, Request, Response } from 'express';
import { authenticate } from '../middleware/auth';
import { paginate, errorResponse } from '../types/responses';

const router = Router();

interface GrammarTip {
  id: string;
  title: string;
  titleVi: string;
  explanation: string;
  pattern?: string;
  examples: Array<{ sentence: string; translation: string }>;
  level: string;
  commonMistakes?: string;
}

const grammarTips: Record<string, GrammarTip[]> = {
  en: [
    { id: 'en-1', title: 'Present Simple vs Present Continuous', titleVi: 'Hiện tại đơn vs Hiện tại tiếp diễn', explanation: 'Present Simple dùng cho thói quen, sự thật chung. Present Continuous dùng cho hành động đang xảy ra ngay lúc nói.', pattern: 'Simple: S + V(s/es) | Continuous: S + am/is/are + V-ing', examples: [{ sentence: 'I study English every day.', translation: 'Tôi học tiếng Anh mỗi ngày. (thói quen)' }, { sentence: 'I am studying English now.', translation: 'Tôi đang học tiếng Anh bây giờ. (đang xảy ra)' }, { sentence: 'She works at a hospital.', translation: 'Cô ấy làm việc ở bệnh viện. (sự thật)' }], level: 'beginner', commonMistakes: 'Người Việt hay dùng "I am study" thay vì "I am studying". Nhớ thêm -ing khi dùng Continuous.' },
    { id: 'en-2', title: 'Countable vs Uncountable Nouns', titleVi: 'Danh từ đếm được vs không đếm được', explanation: 'Danh từ đếm được có thể dùng số đếm và a/an. Danh từ không đếm được không dùng a/an và không có dạng số nhiều.', pattern: 'Countable: a/an, many, few | Uncountable: much, little, some', examples: [{ sentence: 'I have many books and a pen.', translation: 'Tôi có nhiều sách và một cây bút.' }, { sentence: 'I need some water and a little sugar.', translation: 'Tôi cần một ít nước và một chút đường.' }, { sentence: 'There is much traffic today.', translation: 'Hôm nay có nhiều xe cộ.' }], level: 'beginner', commonMistakes: 'Không nói "a water", "an information", "many furnitures". Đây là các danh từ không đếm được.' },
    { id: 'en-3', title: 'Articles: a, an, the', titleVi: 'Mạo từ: a, an, the', explanation: 'a/an dùng cho danh từ chưa xác định (lần đầu nhắc đến). the dùng cho danh từ đã xác định (đã biết, duy nhất).', pattern: 'a + phụ âm | an + nguyên âm | the + danh từ đã biết', examples: [{ sentence: 'I saw a dog. The dog was big.', translation: 'Tôi thấy một con chó. Con chó đó to.' }, { sentence: 'She is an engineer.', translation: 'Cô ấy là kỹ sư.' }, { sentence: 'The sun rises in the east.', translation: 'Mặt trời mọc ở phía đông.' }], level: 'beginner', commonMistakes: 'Người Việt thường bỏ mạo từ vì tiếng Việt không có. Luôn kiểm tra xem danh từ đã xác định chưa.' },
    { id: 'en-4', title: 'Past Simple vs Present Perfect', titleVi: 'Quá khứ đơn vs Hiện tại hoàn thành', explanation: 'Past Simple: hành động đã kết thúc hoàn toàn, có thời gian cụ thể. Present Perfect: hành động có liên quan đến hiện tại, không có thời gian cụ thể.', pattern: 'Past Simple: S + V2/ed | Present Perfect: S + have/has + V3', examples: [{ sentence: 'I went to Japan last year.', translation: 'Tôi đã đi Nhật năm ngoái. (thời gian cụ thể)' }, { sentence: 'I have been to Japan.', translation: 'Tôi đã từng đi Nhật. (kinh nghiệm)' }, { sentence: 'She has just finished her homework.', translation: 'Cô ấy vừa mới làm xong bài tập.' }], level: 'intermediate', commonMistakes: 'Không dùng "yesterday/last year" với Present Perfect. Sai: "I have gone there yesterday."' },
    { id: 'en-5', title: 'Conditional Sentences', titleVi: 'Câu điều kiện', explanation: 'Type 0: sự thật. Type 1: có thể xảy ra. Type 2: không thực ở hiện tại. Type 3: không thực ở quá khứ.', pattern: 'Type 1: If + present → will + V | Type 2: If + past → would + V', examples: [{ sentence: 'If it rains, I will stay home.', translation: 'Nếu trời mưa, tôi sẽ ở nhà. (Type 1)' }, { sentence: 'If I were rich, I would travel the world.', translation: 'Nếu tôi giàu, tôi sẽ đi du lịch thế giới. (Type 2)' }, { sentence: 'If I had studied harder, I would have passed.', translation: 'Nếu tôi học chăm hơn, tôi đã đậu rồi. (Type 3)' }], level: 'intermediate', commonMistakes: 'Type 2 dùng "were" cho tất cả ngôi: "If I were you..." không phải "If I was you..."' },
    { id: 'en-6', title: 'Relative Clauses', titleVi: 'Mệnh đề quan hệ', explanation: 'Mệnh đề quan hệ bổ nghĩa cho danh từ đứng trước. Who (người), which (vật), that (cả hai), where (nơi), when (thời gian), whose (sở hữu).', pattern: 'Noun + who/which/that/where/when + clause', examples: [{ sentence: 'The man who lives next door is a teacher.', translation: 'Người đàn ông sống cạnh nhà là giáo viên.' }, { sentence: 'The book which I bought is very interesting.', translation: 'Cuốn sách mà tôi mua rất thú vị.' }, { sentence: 'This is the city where I was born.', translation: 'Đây là thành phố nơi tôi sinh ra.' }], level: 'intermediate', commonMistakes: 'Không dùng đại từ thừa: Sai "The man who he lives..." Đúng "The man who lives..."' },
    { id: 'en-7', title: 'Modal Verbs', titleVi: 'Động từ khuyết thiếu', explanation: 'Can (có thể), must (phải), should (nên), may (có thể/được phép), will (sẽ), would (sẽ - lịch sự hơn).', pattern: 'S + modal + V (nguyên thể, không to)', examples: [{ sentence: 'You should study more.', translation: 'Bạn nên học nhiều hơn.' }, { sentence: 'Can you help me, please?', translation: 'Bạn có thể giúp tôi không?' }, { sentence: 'You must wear a seatbelt.', translation: 'Bạn phải thắt dây an toàn.' }], level: 'beginner', commonMistakes: 'Không thêm -s/-es sau modal: Sai "She cans swim." Đúng "She can swim."' },
    { id: 'en-8', title: 'Passive Voice', titleVi: 'Câu bị động', explanation: 'Dùng khi không biết hoặc không cần nêu chủ thể hành động, hoặc muốn nhấn mạnh đối tượng bị tác động.', pattern: 'S + be + V3 (+ by + agent)', examples: [{ sentence: 'The letter was written by Anna.', translation: 'Bức thư được viết bởi Anna.' }, { sentence: 'English is spoken worldwide.', translation: 'Tiếng Anh được nói trên toàn thế giới.' }, { sentence: 'The cake has been eaten.', translation: 'Cái bánh đã bị ăn mất rồi.' }], level: 'intermediate', commonMistakes: 'Nhớ chia "be" theo thì: is/are (hiện tại), was/were (quá khứ), has been (hoàn thành).' },
    { id: 'en-9', title: 'Gerund vs Infinitive', titleVi: 'Danh động từ vs Động từ nguyên thể', explanation: 'Một số động từ đi với gerund (V-ing), một số đi với infinitive (to + V), một số đi được cả hai nhưng nghĩa khác nhau.', pattern: 'enjoy/finish/avoid + V-ing | want/decide/hope + to V', examples: [{ sentence: 'I enjoy swimming in the sea.', translation: 'Tôi thích bơi ở biển.' }, { sentence: 'She decided to study abroad.', translation: 'Cô ấy quyết định du học.' }, { sentence: 'I stopped smoking. vs I stopped to smoke.', translation: 'Tôi đã bỏ thuốc. vs Tôi dừng lại để hút thuốc.' }], level: 'intermediate', commonMistakes: 'Sau "enjoy, mind, avoid, finish" luôn dùng V-ing. Sau "want, need, decide, hope" luôn dùng to + V.' },
    { id: 'en-10', title: 'Reported Speech', titleVi: 'Câu tường thuật', explanation: 'Khi thuật lại lời nói của người khác, thì của động từ lùi về quá khứ một bậc.', pattern: 'Direct: "I am tired." → Reported: He said (that) he was tired.', examples: [{ sentence: '"I love you." → She said she loved me.', translation: '"Tôi yêu bạn." → Cô ấy nói cô ấy yêu tôi.' }, { sentence: '"I will call you." → He said he would call me.', translation: '"Tôi sẽ gọi cho bạn." → Anh ấy nói anh ấy sẽ gọi cho tôi.' }, { sentence: '"Are you hungry?" → She asked if I was hungry.', translation: '"Bạn có đói không?" → Cô ấy hỏi tôi có đói không.' }], level: 'intermediate', commonMistakes: 'Câu hỏi tường thuật dùng if/whether và trật tự câu khẳng định: "She asked if I was..." không phải "...if was I..."' },
    { id: 'en-11', title: 'Prepositions of Time', titleVi: 'Giới từ chỉ thời gian', explanation: 'at (giờ cụ thể, ngày lễ), on (ngày trong tuần, ngày tháng), in (tháng, năm, buổi trong ngày).', pattern: 'at + time/holiday | on + day/date | in + month/year/period', examples: [{ sentence: 'The meeting is at 3 PM on Monday.', translation: 'Cuộc họp lúc 3 giờ chiều vào thứ Hai.' }, { sentence: 'I was born in 2000, in March.', translation: 'Tôi sinh năm 2000, vào tháng 3.' }, { sentence: 'We eat dinner at night.', translation: 'Chúng tôi ăn tối vào buổi tối.' }], level: 'beginner', commonMistakes: 'Không nói "in Monday" hay "on 3 PM". Nhớ: at giờ, on ngày, in tháng/năm.' },
    { id: 'en-12', title: 'Question Tags', titleVi: 'Câu hỏi đuôi', explanation: 'Thêm vào cuối câu để xác nhận thông tin. Câu khẳng định → đuôi phủ định. Câu phủ định → đuôi khẳng định.', pattern: 'Positive sentence + negative tag? | Negative sentence + positive tag?', examples: [{ sentence: "It's a nice day, isn't it?", translation: 'Hôm nay đẹp trời nhỉ?' }, { sentence: "You don't like coffee, do you?", translation: 'Bạn không thích cà phê, phải không?' }, { sentence: "She can swim, can't she?", translation: 'Cô ấy biết bơi, phải không?' }], level: 'intermediate', commonMistakes: 'Người Việt hay dùng "right?" hoặc "yes?" thay vì question tag đúng chuẩn.' },
    { id: 'en-13', title: 'Comparatives and Superlatives', titleVi: 'So sánh hơn và so sánh nhất', explanation: 'So sánh hơn: tính từ ngắn + -er / more + tính từ dài. So sánh nhất: the + tính từ ngắn + -est / the most + tính từ dài.', pattern: 'Comparative: adj + -er / more + adj | Superlative: the + adj + -est / the most + adj', examples: [{ sentence: 'This book is cheaper than that one.', translation: 'Cuốn sách này rẻ hơn cuốn kia.' }, { sentence: 'She is more intelligent than her brother.', translation: 'Cô ấy thông minh hơn anh trai.' }, { sentence: 'This is the most beautiful city I have visited.', translation: 'Đây là thành phố đẹp nhất tôi từng đến.' }], level: 'beginner', commonMistakes: 'Không dùng cả hai: Sai "more taller", "more better". Đúng "taller", "better".' },
    { id: 'en-14', title: 'Future Tenses', titleVi: 'Các thì tương lai', explanation: 'will + V: quyết định tức thời, dự đoán. be going to + V: kế hoạch đã có, dự đoán có bằng chứng. Present Continuous: kế hoạch đã sắp xếp.', pattern: 'will + V | be going to + V | be + V-ing (future)', examples: [{ sentence: "I'll have a coffee, please.", translation: 'Cho tôi một ly cà phê. (quyết định tức thời)' }, { sentence: "I'm going to visit my parents this weekend.", translation: 'Tôi sẽ thăm bố mẹ cuối tuần này. (kế hoạch)' }, { sentence: "I'm meeting John at 5 PM tomorrow.", translation: 'Tôi gặp John lúc 5 giờ chiều mai. (đã sắp xếp)' }], level: 'intermediate', commonMistakes: 'Người Việt hay dùng "will" cho mọi tình huống. Hãy phân biệt kế hoạch (going to) và quyết định tức thời (will).' },
    { id: 'en-15', title: 'Adverbs of Frequency', titleVi: 'Trạng từ tần suất', explanation: 'always (100%), usually (80%), often (60%), sometimes (40%), rarely (20%), never (0%). Đặt trước động từ thường, sau be.', pattern: 'S + adverb + V | S + be + adverb', examples: [{ sentence: 'I always brush my teeth before bed.', translation: 'Tôi luôn đánh răng trước khi ngủ.' }, { sentence: 'She is never late for work.', translation: 'Cô ấy không bao giờ đi làm muộn.' }, { sentence: 'He sometimes forgets his keys.', translation: 'Anh ấy đôi khi quên chìa khóa.' }], level: 'beginner', commonMistakes: 'Đặt sai vị trí: Sai "I brush always my teeth." Đúng "I always brush my teeth."' },
    { id: 'en-16', title: 'Phrasal Verbs', titleVi: 'Cụm động từ', explanation: 'Động từ + giới từ/trạng từ tạo nghĩa mới hoàn toàn. Rất phổ biến trong tiếng Anh giao tiếp.', pattern: 'Verb + particle (preposition/adverb)', examples: [{ sentence: 'Can you turn off the light?', translation: 'Bạn có thể tắt đèn không? (turn off = tắt)' }, { sentence: 'I need to look up this word.', translation: 'Tôi cần tra từ này. (look up = tra cứu)' }, { sentence: 'She gave up smoking last year.', translation: 'Cô ấy bỏ thuốc năm ngoái. (give up = từ bỏ)' }], level: 'intermediate', commonMistakes: 'Không dịch từng từ một. "Give up" không phải "cho lên" mà là "từ bỏ".' },
    { id: 'en-17', title: 'Subject-Verb Agreement', titleVi: 'Sự hòa hợp chủ ngữ - động từ', explanation: 'Động từ phải hòa hợp với chủ ngữ về số. Ngôi 3 số ít thêm -s/-es ở hiện tại đơn.', pattern: 'He/She/It + V-s/es | I/You/We/They + V', examples: [{ sentence: 'She works hard every day.', translation: 'Cô ấy làm việc chăm chỉ mỗi ngày.' }, { sentence: 'The students are studying in the library.', translation: 'Các sinh viên đang học trong thư viện.' }, { sentence: 'Everyone has a different opinion.', translation: 'Mỗi người có ý kiến khác nhau.' }], level: 'beginner', commonMistakes: 'Everyone/someone/nobody là số ít: "Everyone is here" không phải "Everyone are here".' },
    { id: 'en-18', title: 'Conjunctions', titleVi: 'Liên từ', explanation: 'Coordinating: and, but, or, so, yet. Subordinating: because, although, when, if, while.', pattern: 'Clause + coordinating conjunction + clause | Subordinating conjunction + clause, main clause', examples: [{ sentence: 'I like coffee but she prefers tea.', translation: 'Tôi thích cà phê nhưng cô ấy thích trà hơn.' }, { sentence: 'Although it was raining, we went out.', translation: 'Mặc dù trời mưa, chúng tôi vẫn ra ngoài.' }, { sentence: 'I stayed home because I was sick.', translation: 'Tôi ở nhà vì tôi bị ốm.' }], level: 'beginner', commonMistakes: 'Không dùng "although" và "but" cùng lúc: Sai "Although it rained, but we went out."' },
    { id: 'en-19', title: 'Quantifiers', titleVi: 'Từ chỉ số lượng', explanation: 'some/any (một ít), much/many (nhiều), a lot of (nhiều - cả hai loại), a few/a little (một ít - đủ dùng), few/little (rất ít - gần như không có).', pattern: 'some/any + noun | much + uncountable | many + countable | a lot of + both', examples: [{ sentence: 'I have some money but not much.', translation: 'Tôi có một ít tiền nhưng không nhiều.' }, { sentence: 'Are there any questions?', translation: 'Có câu hỏi nào không?' }, { sentence: 'A few students passed the exam.', translation: 'Một vài sinh viên đã đậu kỳ thi.' }], level: 'beginner', commonMistakes: 'some (khẳng định), any (phủ định/câu hỏi). Sai: "I don\'t have some money." Đúng: "I don\'t have any money."' },
    { id: 'en-20', title: 'Wish Sentences', titleVi: 'Câu ước', explanation: 'Wish + past simple: ước điều không thực ở hiện tại. Wish + past perfect: ước điều không thực ở quá khứ.', pattern: 'I wish + S + V2 (present wish) | I wish + S + had + V3 (past wish)', examples: [{ sentence: 'I wish I could fly.', translation: 'Ước gì tôi có thể bay.' }, { sentence: 'I wish I had studied harder.', translation: 'Ước gì tôi đã học chăm hơn.' }, { sentence: 'I wish you would stop talking.', translation: 'Ước gì bạn ngừng nói chuyện.' }], level: 'advanced', commonMistakes: 'Sau "wish" dùng thì quá khứ: Sai "I wish I am rich." Đúng "I wish I were rich."' },
    { id: 'en-21', title: 'Inversion for Emphasis', titleVi: 'Đảo ngữ để nhấn mạnh', explanation: 'Đảo ngữ dùng để nhấn mạnh, thường gặp trong văn viết trang trọng. Bắt đầu bằng từ phủ định hoặc trạng từ đặc biệt.', pattern: 'Never/Rarely/Seldom + auxiliary + S + V', examples: [{ sentence: 'Never have I seen such beauty.', translation: 'Chưa bao giờ tôi thấy vẻ đẹp như vậy.' }, { sentence: 'Not only did she win, but she also broke the record.', translation: 'Không chỉ thắng, cô ấy còn phá kỷ lục.' }, { sentence: 'Hardly had I arrived when it started raining.', translation: 'Tôi vừa đến thì trời bắt đầu mưa.' }], level: 'advanced', commonMistakes: 'Đảo ngữ chỉ dùng trong văn viết trang trọng hoặc văn học, không dùng trong giao tiếp thông thường.' },
    { id: 'en-22', title: 'Cleft Sentences', titleVi: 'Câu chẻ để nhấn mạnh', explanation: 'Dùng "It is/was...that/who" để nhấn mạnh một phần của câu.', pattern: 'It is/was + [phần nhấn mạnh] + that/who + phần còn lại', examples: [{ sentence: 'It was John who broke the window.', translation: 'Chính John là người đã đập vỡ cửa sổ.' }, { sentence: 'It is hard work that leads to success.', translation: 'Chính sự chăm chỉ dẫn đến thành công.' }, { sentence: 'It was in Paris that they first met.', translation: 'Chính ở Paris là nơi họ gặp nhau lần đầu.' }], level: 'advanced', commonMistakes: 'Câu chẻ nhấn mạnh một yếu tố cụ thể. Đừng nhầm với câu bình thường.' },
  ],
  ja: [
    { id: 'ja-1', title: 'は vs が (Particles)', titleVi: 'Trợ từ は vs が', explanation: 'は (wa): đánh dấu chủ đề. が (ga): đánh dấu chủ ngữ mới/nhấn mạnh.', examples: [{ sentence: '私は学生です。', translation: 'Tôi là học sinh. (chủ đề)' }, { sentence: '誰が来ましたか？', translation: 'Ai đã đến? (nhấn mạnh chủ ngữ)' }], level: 'beginner' },
    { id: 'ja-2', title: 'て-form (Te-form)', titleVi: 'Thể て', explanation: 'Dùng để nối câu, yêu cầu, đang làm gì. Cách chia: 食べる→食べて, 飲む→飲んで.', examples: [{ sentence: '食べてください。', translation: 'Xin hãy ăn.' }, { sentence: '本を読んでいます。', translation: 'Tôi đang đọc sách.' }], level: 'beginner' },
    { id: 'ja-3', title: 'Verb Groups (動詞グループ)', titleVi: 'Nhóm động từ', explanation: 'Group 1 (u-verbs): 書く, 飲む. Group 2 (ru-verbs): 食べる, 見る. Group 3 (irregular): する, 来る.', examples: [{ sentence: '書く → 書きます (Group 1)', translation: 'Viết → Viết (lịch sự)' }, { sentence: '食べる → 食べます (Group 2)', translation: 'Ăn → Ăn (lịch sự)' }], level: 'beginner' },
    { id: 'ja-4', title: 'Passive Form (受身形)', titleVi: 'Thể bị động', explanation: 'Group 1: u→areru. Group 2: ru→rareru. する→される, 来る→来られる.', examples: [{ sentence: '先生に褒められました。', translation: 'Tôi được thầy khen.' }, { sentence: '雨に降られました。', translation: 'Tôi bị mưa (gặp mưa).' }], level: 'intermediate' },
  ],
  zh: [
    { id: 'zh-1', title: '了 (le) - Completed Action', titleVi: 'Trợ từ 了 - Hành động hoàn thành', explanation: '了 đặt sau động từ biểu thị hành động đã hoàn thành, hoặc cuối câu biểu thị thay đổi trạng thái.', examples: [{ sentence: '我吃了饭。', translation: 'Tôi đã ăn cơm.' }, { sentence: '下雨了。', translation: 'Trời mưa rồi. (thay đổi trạng thái)' }], level: 'beginner' },
    { id: 'zh-2', title: '的/得/地 (de)', titleVi: 'Ba chữ "de" trong tiếng Trung', explanation: '的: bổ nghĩa cho danh từ. 得: bổ nghĩa cho động từ (kết quả). 地: bổ nghĩa cho động từ (cách thức).', examples: [{ sentence: '漂亮的花 (beautiful flower)', translation: 'Hoa đẹp (的 + danh từ)' }, { sentence: '跑得快 (run fast)', translation: 'Chạy nhanh (得 + kết quả)' }], level: 'beginner' },
    { id: 'zh-3', title: '把 (bǎ) Structure', titleVi: 'Cấu trúc 把', explanation: 'S + 把 + O + V + complement. Dùng khi muốn nhấn mạnh tác động lên đối tượng.', examples: [{ sentence: '我把书放在桌子上。', translation: 'Tôi đặt sách lên bàn.' }, { sentence: '请把门关上。', translation: 'Xin hãy đóng cửa lại.' }], level: 'intermediate' },
    { id: 'zh-4', title: 'Measure Words (量词)', titleVi: 'Lượng từ', explanation: 'Tiếng Trung dùng lượng từ giữa số và danh từ: 个(cái), 本(cuốn), 只(con), 条(sợi/con).', examples: [{ sentence: '一个人 (one person)', translation: 'Một người (个 = lượng từ chung)' }, { sentence: '三本书 (three books)', translation: 'Ba cuốn sách (本 = cho sách)' }], level: 'beginner' },
  ],
  ko: [
    { id: 'ko-1', title: '은/는 vs 이/가 (Particles)', titleVi: 'Trợ từ 은/는 vs 이/가', explanation: '은/는: đánh dấu chủ đề (topic). 이/가: đánh dấu chủ ngữ (subject), thông tin mới.', examples: [{ sentence: '저는 학생이에요. (topic)', translation: 'Tôi là học sinh. (chủ đề)' }, { sentence: '누가 왔어요? (subject)', translation: 'Ai đã đến? (chủ ngữ mới)' }], level: 'beginner' },
    { id: 'ko-2', title: 'Honorific Speech (존댓말)', titleVi: 'Kính ngữ', explanation: 'Tiếng Hàn có nhiều cấp độ lịch sự: 해요체 (lịch sự thường), 합니다체 (trang trọng), 반말 (thân mật).', examples: [{ sentence: '먹어요 (polite)', translation: 'Ăn (lịch sự thường)' }, { sentence: '먹습니다 (formal)', translation: 'Ăn (trang trọng)' }], level: 'beginner' },
    { id: 'ko-3', title: 'Verb Conjugation Basics', titleVi: 'Chia động từ cơ bản', explanation: 'Bỏ 다 → thêm đuôi. 아/어요 (hiện tại), 았/었어요 (quá khứ), ㄹ/을 거예요 (tương lai).', examples: [{ sentence: '가다 → 가요 (present)', translation: 'Đi → Đi (hiện tại)' }, { sentence: '먹다 → 먹었어요 (past)', translation: 'Ăn → Đã ăn (quá khứ)' }], level: 'beginner' },
    { id: 'ko-4', title: '(으)면 - Conditional', titleVi: 'Câu điều kiện (으)면', explanation: 'V + (으)면: nếu... thì... Dùng cho điều kiện và giả định.', examples: [{ sentence: '비가 오면 집에 있어요.', translation: 'Nếu trời mưa thì ở nhà.' }, { sentence: '시간이 있으면 만나요.', translation: 'Nếu có thời gian thì gặp nhau.' }], level: 'intermediate' },
  ],
};

router.get('/', authenticate, async (req: Request, res: Response) => {
  try {
    const lang = (req.query.lang as string) || 'en';
    const level = req.query.level as string;
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 20;

    let tips = grammarTips[lang] || grammarTips['en'];
    if (level) {
      tips = tips.filter((t) => t.level === level);
    }

    res.json(paginate(tips, page, limit));
  } catch (error) {
    console.error('Grammar tips error:', error);
    res.status(500).json(errorResponse('Không thể tải mẹo ngữ pháp', 'INTERNAL_ERROR'));
  }
});

router.get('/:id', authenticate, async (req: Request, res: Response) => {
  try {
    const { id } = req.params;

    for (const lang of Object.values(grammarTips)) {
      const tip = lang.find((t) => t.id === id);
      if (tip) {
        res.json(tip);
        return;
      }
    }

    res.status(404).json(errorResponse('Không tìm thấy mẹo ngữ pháp', 'NOT_FOUND'));
  } catch (error) {
    console.error('Grammar tip error:', error);
    res.status(500).json(errorResponse('Không thể tải mẹo ngữ pháp', 'INTERNAL_ERROR'));
  }
});

export default router;
