import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const chineseDailyLessons: LessonData[] = [
  {
    title: 'Daily Life (日常生活)',
    titleVi: 'Sinh hoạt hàng ngày',
    description: 'Learn Chinese vocabulary about daily activities',
    descriptionVi: 'Học từ vựng tiếng Trung về sinh hoạt hàng ngày',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: '起床', reading: 'qǐ chuáng', meaning: 'thức dậy', example: '我每天六点起床。', exampleMeaning: 'Tôi thức dậy lúc 6 giờ mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: '睡觉', reading: 'shuì jiào', meaning: 'đi ngủ', example: '我十一点睡觉。', exampleMeaning: 'Tôi đi ngủ lúc 11 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '吃饭', reading: 'chī fàn', meaning: 'ăn cơm', example: '我们一起吃饭吧。', exampleMeaning: 'Chúng ta cùng ăn cơm nhé.', difficulty: DIFFICULTY.EASY },
      { word: '喝水', reading: 'hē shuǐ', meaning: 'uống nước', example: '多喝水对身体好。', exampleMeaning: 'Uống nhiều nước tốt cho sức khỏe.', difficulty: DIFFICULTY.EASY },
      { word: '上班', reading: 'shàng bān', meaning: 'đi làm', example: '我八点上班。', exampleMeaning: 'Tôi đi làm lúc 8 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '下班', reading: 'xià bān', meaning: 'tan làm', example: '五点下班。', exampleMeaning: 'Tan làm lúc 5 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '上学', reading: 'shàng xué', meaning: 'đi học', example: '孩子们上学了。', exampleMeaning: 'Bọn trẻ đi học rồi.', difficulty: DIFFICULTY.EASY },
      { word: '回家', reading: 'huí jiā', meaning: 'về nhà', example: '我想回家。', exampleMeaning: 'Tôi muốn về nhà.', difficulty: DIFFICULTY.EASY },
      { word: '洗澡', reading: 'xǐ zǎo', meaning: 'tắm', example: '我每天晚上洗澡。', exampleMeaning: 'Tôi tắm mỗi tối.', difficulty: DIFFICULTY.EASY },
      { word: '刷牙', reading: 'shuā yá', meaning: 'đánh răng', example: '早上要刷牙。', exampleMeaning: 'Buổi sáng phải đánh răng.', difficulty: DIFFICULTY.EASY },
      { word: '看书', reading: 'kàn shū', meaning: 'đọc sách', example: '我喜欢看书。', exampleMeaning: 'Tôi thích đọc sách.', difficulty: DIFFICULTY.EASY },
      { word: '看电视', reading: 'kàn diàn shì', meaning: 'xem TV', example: '晚上看电视。', exampleMeaning: 'Buổi tối xem TV.', difficulty: DIFFICULTY.EASY },
      { word: '运动', reading: 'yùn dòng', meaning: 'tập thể dục', example: '我每天运动。', exampleMeaning: 'Tôi tập thể dục mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: '做饭', reading: 'zuò fàn', meaning: 'nấu cơm', example: '妈妈在做饭。', exampleMeaning: 'Mẹ đang nấu cơm.', difficulty: DIFFICULTY.EASY },
      { word: '打扫', reading: 'dǎ sǎo', meaning: 'dọn dẹp', example: '周末打扫房间。', exampleMeaning: 'Cuối tuần dọn dẹp phòng.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Thức dậy" tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['睡觉', '起床', '上班', '回家'], answer: '起床', explanation: '起床 (qǐ chuáng) = thức dậy', explanationVi: '起床 (qǐ chuáng) = thức dậy', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "洗澡" = ?', type: QUIZ_TYPES.MATCHING, options: ['Tắm', 'Đánh răng', 'Đi ngủ', 'Ăn cơm'], answer: 'Tắm', explanation: '洗澡 = tắm', explanationVi: '洗澡 = tắm', difficulty: DIFFICULTY.EASY },
      { question: '"Đi làm" tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['下班', '上学', '上班', '回家'], answer: '上班', explanation: '上班 = đi làm', explanationVi: '上班 = đi làm', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "我每天___。" (tập thể dục)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '运动', explanation: '运动 = tập thể dục', explanationVi: '运动 = tập thể dục', difficulty: DIFFICULTY.EASY },
      { question: '"做饭" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Ăn cơm', 'Nấu cơm', 'Dọn dẹp', 'Đọc sách'], answer: 'Nấu cơm', explanation: '做饭 = nấu cơm', explanationVi: '做饭 = nấu cơm', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Family (家庭)',
    titleVi: 'Gia đình',
    description: 'Learn Chinese vocabulary about family members',
    descriptionVi: 'Học từ vựng tiếng Trung về gia đình',
    topic: TOPICS.FAMILY,
    vocabulary: [
      { word: '家', reading: 'jiā', meaning: 'nhà/gia đình', example: '我家有五口人。', exampleMeaning: 'Gia đình tôi có 5 người.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '爸爸', reading: 'bà ba', meaning: 'bố', example: '爸爸在工作。', exampleMeaning: 'Bố đang làm việc.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '妈妈', reading: 'mā ma', meaning: 'mẹ', example: '妈妈做的菜很好吃。', exampleMeaning: 'Món ăn mẹ nấu rất ngon.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '哥哥', reading: 'gē ge', meaning: 'anh trai', example: '哥哥比我大三岁。', exampleMeaning: 'Anh trai lớn hơn tôi 3 tuổi.', difficulty: DIFFICULTY.EASY },
      { word: '姐姐', reading: 'jiě jie', meaning: 'chị gái', example: '姐姐是医生。', exampleMeaning: 'Chị gái là bác sĩ.', difficulty: DIFFICULTY.EASY },
      { word: '弟弟', reading: 'dì di', meaning: 'em trai', example: '弟弟在上学。', exampleMeaning: 'Em trai đang đi học.', difficulty: DIFFICULTY.EASY },
      { word: '妹妹', reading: 'mèi mei', meaning: 'em gái', example: '妹妹很可爱。', exampleMeaning: 'Em gái rất dễ thương.', difficulty: DIFFICULTY.EASY },
      { word: '爷爷', reading: 'yé ye', meaning: 'ông nội', example: '爷爷今年八十岁。', exampleMeaning: 'Ông nội năm nay 80 tuổi.', difficulty: DIFFICULTY.EASY },
      { word: '奶奶', reading: 'nǎi nai', meaning: 'bà nội', example: '奶奶住在乡下。', exampleMeaning: 'Bà nội sống ở quê.', difficulty: DIFFICULTY.EASY },
      { word: '丈夫', reading: 'zhàng fu', meaning: 'chồng', example: '她的丈夫是老师。', exampleMeaning: 'Chồng cô ấy là giáo viên.', difficulty: DIFFICULTY.EASY },
      { word: '妻子', reading: 'qī zi', meaning: 'vợ', example: '他和妻子去旅行。', exampleMeaning: 'Anh ấy đi du lịch với vợ.', difficulty: DIFFICULTY.EASY },
      { word: '儿子', reading: 'ér zi', meaning: 'con trai', example: '儿子在上大学。', exampleMeaning: 'Con trai đang học đại học.', difficulty: DIFFICULTY.EASY },
      { word: '女儿', reading: 'nǚ ér', meaning: 'con gái', example: '女儿喜欢画画。', exampleMeaning: 'Con gái thích vẽ.', difficulty: DIFFICULTY.EASY },
      { word: '孩子', reading: 'hái zi', meaning: 'con/trẻ em', example: '孩子们在玩。', exampleMeaning: 'Bọn trẻ đang chơi.', difficulty: DIFFICULTY.EASY },
      { word: '父母', reading: 'fù mǔ', meaning: 'bố mẹ', example: '我爱我的父母。', exampleMeaning: 'Tôi yêu bố mẹ.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Bố" tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['妈妈', '爸爸', '哥哥', '爷爷'], answer: '爸爸', explanation: '爸爸 = bố', explanationVi: '爸爸 = bố', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Nối: "妹妹" = ?', type: QUIZ_TYPES.MATCHING, options: ['Em gái', 'Chị gái', 'Em trai', 'Anh trai'], answer: 'Em gái', explanation: '妹妹 = em gái', explanationVi: '妹妹 = em gái', difficulty: DIFFICULTY.EASY },
      { question: '"Ông nội" tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['奶奶', '爷爷', '爸爸', '哥哥'], answer: '爷爷', explanation: '爷爷 = ông nội', explanationVi: '爷爷 = ông nội', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "我___有五口人。" (nhà)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '家', explanation: '家 = nhà/gia đình', explanationVi: '家 = nhà/gia đình', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"孩子" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Bố mẹ', 'Con/trẻ em', 'Anh trai', 'Vợ'], answer: 'Con/trẻ em', explanation: '孩子 = con/trẻ em', explanationVi: '孩子 = con/trẻ em', difficulty: DIFFICULTY.EASY },
    ],
  },
];
