import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const chineseGreetingsLessons: LessonData[] = [
  {
    title: '基本问候',
    titleVi: 'Chào hỏi cơ bản',
    description: 'Learn basic Chinese greetings and introductions',
    descriptionVi: 'Học cách chào hỏi cơ bản trong tiếng Trung',
    topic: TOPICS.GREETINGS,
    vocabulary: [
      { word: '你好', reading: 'nǐ hǎo', meaning: 'Xin chào', example: '你好，很高兴认识你。', exampleMeaning: 'Xin chào, rất vui được gặp bạn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '早上好', reading: 'zǎo shang hǎo', meaning: 'Chào buổi sáng', example: '早上好，今天天气真好。', exampleMeaning: 'Chào buổi sáng, hôm nay thời tiết đẹp quá.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '晚上好', reading: 'wǎn shang hǎo', meaning: 'Chào buổi tối', example: '晚上好，吃饭了吗？', exampleMeaning: 'Chào buổi tối, bạn ăn cơm chưa?', difficulty: DIFFICULTY.VERY_EASY },
      { word: '再见', reading: 'zài jiàn', meaning: 'Tạm biệt', example: '再见，明天见！', exampleMeaning: 'Tạm biệt, ngày mai gặp lại!', difficulty: DIFFICULTY.VERY_EASY },
      { word: '谢谢', reading: 'xiè xie', meaning: 'Cảm ơn', example: '谢谢你的帮助。', exampleMeaning: 'Cảm ơn sự giúp đỡ của bạn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '不客气', reading: 'bú kè qi', meaning: 'Không có gì', example: '不客气，这是我应该做的。', exampleMeaning: 'Không có gì, đây là việc tôi nên làm.', difficulty: DIFFICULTY.EASY },
      { word: '对不起', reading: 'duì bu qǐ', meaning: 'Xin lỗi', example: '对不起，我迟到了。', exampleMeaning: 'Xin lỗi, tôi đến muộn rồi.', difficulty: DIFFICULTY.EASY },
      { word: '没关系', reading: 'méi guān xi', meaning: 'Không sao', example: '没关系，不用担心。', exampleMeaning: 'Không sao, đừng lo lắng.', difficulty: DIFFICULTY.EASY },
      { word: '请', reading: 'qǐng', meaning: 'Xin mời / Làm ơn', example: '请坐。', exampleMeaning: 'Xin mời ngồi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '你好吗', reading: 'nǐ hǎo ma', meaning: 'Bạn khỏe không?', example: '你好吗？我很好。', exampleMeaning: 'Bạn khỏe không? Tôi rất khỏe.', difficulty: DIFFICULTY.VERY_EASY },
    ],
    quizzes: [
      { question: '"Xin chào" trong tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['你好', '再见', '谢谢', '对不起'], answer: '你好', explanationVi: '你好 (nǐ hǎo) là cách chào phổ biến nhất', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"谢谢" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Xin lỗi', 'Cảm ơn', 'Tạm biệt', 'Xin chào'], answer: 'Cảm ơn', explanationVi: '谢谢 (xiè xie) = Cảm ơn', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Cách nói "Tạm biệt" trong tiếng Trung?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['你好', '早上好', '再见', '晚上好'], answer: '再见', explanationVi: '再见 (zài jiàn) = Tạm biệt, nghĩa đen là "gặp lại"', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"对不起" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Không sao', 'Xin lỗi', 'Cảm ơn', 'Xin mời'], answer: 'Xin lỗi', explanationVi: '对不起 (duì bu qǐ) = Xin lỗi', difficulty: DIFFICULTY.EASY },
      { question: 'Khi ai đó nói "谢谢", bạn đáp lại thế nào?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['再见', '你好', '不客气', '对不起'], answer: '不客气', explanationVi: '不客气 (bú kè qi) = Không có gì, dùng để đáp lại lời cảm ơn', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: '自我介绍',
    titleVi: 'Tự giới thiệu bản thân',
    description: 'Learn to introduce yourself in Chinese',
    descriptionVi: 'Học cách tự giới thiệu bản thân bằng tiếng Trung',
    topic: TOPICS.SELF_INTRO,
    vocabulary: [
      { word: '我', reading: 'wǒ', meaning: 'Tôi', example: '我是学生。', exampleMeaning: 'Tôi là sinh viên.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '你', reading: 'nǐ', meaning: 'Bạn', example: '你叫什么名字？', exampleMeaning: 'Bạn tên gì?', difficulty: DIFFICULTY.VERY_EASY },
      { word: '名字', reading: 'míng zi', meaning: 'Tên', example: '我的名字是小明。', exampleMeaning: 'Tên tôi là Tiểu Minh.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '叫', reading: 'jiào', meaning: 'Gọi là / Tên là', example: '我叫阿安。', exampleMeaning: 'Tôi tên là An.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '是', reading: 'shì', meaning: 'Là', example: '我是越南人。', exampleMeaning: 'Tôi là người Việt Nam.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '越南', reading: 'yuè nán', meaning: 'Việt Nam', example: '我来自越南。', exampleMeaning: 'Tôi đến từ Việt Nam.', difficulty: DIFFICULTY.EASY },
      { word: '学生', reading: 'xué shēng', meaning: 'Sinh viên / Học sinh', example: '我是大学生。', exampleMeaning: 'Tôi là sinh viên đại học.', difficulty: DIFFICULTY.EASY },
      { word: '老师', reading: 'lǎo shī', meaning: 'Giáo viên', example: '她是我的老师。', exampleMeaning: 'Cô ấy là giáo viên của tôi.', difficulty: DIFFICULTY.EASY },
      { word: '认识', reading: 'rèn shi', meaning: 'Quen biết', example: '很高兴认识你。', exampleMeaning: 'Rất vui được quen biết bạn.', difficulty: DIFFICULTY.EASY },
      { word: '岁', reading: 'suì', meaning: 'Tuổi', example: '我二十岁。', exampleMeaning: 'Tôi hai mươi tuổi.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"我叫..." có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Tôi là...', 'Tôi tên là...', 'Tôi thích...', 'Tôi muốn...'], answer: 'Tôi tên là...', explanationVi: '我叫 (wǒ jiào) = Tôi tên là...', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"学生" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Giáo viên', 'Bác sĩ', 'Sinh viên / Học sinh', 'Công nhân'], answer: 'Sinh viên / Học sinh', explanationVi: '学生 (xué shēng) = Sinh viên / Học sinh', difficulty: DIFFICULTY.EASY },
      { question: 'Cách hỏi "Bạn tên gì?" trong tiếng Trung?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['你好吗？', '你叫什么名字？', '你是谁？', '你几岁？'], answer: '你叫什么名字？', explanationVi: '你叫什么名字？ = Bạn tên gì?', difficulty: DIFFICULTY.EASY },
      { question: '"越南" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Trung Quốc', 'Nhật Bản', 'Hàn Quốc', 'Việt Nam'], answer: 'Việt Nam', explanationVi: '越南 (yuè nán) = Việt Nam', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"老师" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sinh viên', 'Giáo viên', 'Bạn bè', 'Gia đình'], answer: 'Giáo viên', explanationVi: '老师 (lǎo shī) = Giáo viên', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: '数字 1-100',
    titleVi: 'Số đếm 1-100',
    description: 'Learn numbers from 1 to 100 in Chinese',
    descriptionVi: 'Học số đếm từ 1 đến 100 trong tiếng Trung',
    topic: TOPICS.NUMBERS,
    vocabulary: [
      { word: '一', reading: 'yī', meaning: 'Một (1)', example: '我有一个苹果。', exampleMeaning: 'Tôi có một quả táo.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '二', reading: 'èr', meaning: 'Hai (2)', example: '我有两个孩子。', exampleMeaning: 'Tôi có hai đứa con.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '三', reading: 'sān', meaning: 'Ba (3)', example: '三月是春天。', exampleMeaning: 'Tháng ba là mùa xuân.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '五', reading: 'wǔ', meaning: 'Năm (5)', example: '五点钟下班。', exampleMeaning: 'Năm giờ tan làm.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '十', reading: 'shí', meaning: 'Mười (10)', example: '十个人来了。', exampleMeaning: 'Mười người đã đến.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '二十', reading: 'èr shí', meaning: 'Hai mươi (20)', example: '我二十岁了。', exampleMeaning: 'Tôi hai mươi tuổi rồi.', difficulty: DIFFICULTY.EASY },
      { word: '五十', reading: 'wǔ shí', meaning: 'Năm mươi (50)', example: '这本书五十块。', exampleMeaning: 'Cuốn sách này năm mươi tệ.', difficulty: DIFFICULTY.EASY },
      { word: '一百', reading: 'yī bǎi', meaning: 'Một trăm (100)', example: '一百分！', exampleMeaning: 'Một trăm điểm!', difficulty: DIFFICULTY.EASY },
      { word: '零', reading: 'líng', meaning: 'Không (0)', example: '今天零度。', exampleMeaning: 'Hôm nay không độ.', difficulty: DIFFICULTY.EASY },
      { word: '多少', reading: 'duō shǎo', meaning: 'Bao nhiêu', example: '这个多少钱？', exampleMeaning: 'Cái này bao nhiêu tiền?', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"三" là số mấy?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['2', '3', '4', '5'], answer: '3', explanationVi: '三 (sān) = 3', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"十" là số mấy?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['5', '8', '10', '100'], answer: '10', explanationVi: '十 (shí) = 10', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"多少钱" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Bao nhiêu tiền?', 'Mấy giờ?', 'Bao xa?', 'Mấy tuổi?'], answer: 'Bao nhiêu tiền?', explanationVi: '多少钱 (duō shǎo qián) = Bao nhiêu tiền?', difficulty: DIFFICULTY.EASY },
      { question: 'Số 50 trong tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['十五', '五十', '五百', '十'], answer: '五十', explanationVi: '五十 (wǔ shí) = 50', difficulty: DIFFICULTY.EASY },
      { question: '"零" là số mấy?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['1', '10', '100', '0'], answer: '0', explanationVi: '零 (líng) = 0', difficulty: DIFFICULTY.VERY_EASY },
    ],
  },
];
