import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const chineseFoodLessons: LessonData[] = [
  {
    title: '食物 (Food)',
    titleVi: 'Đồ ăn',
    description: 'Common food vocabulary in Chinese',
    descriptionVi: 'Từ vựng về đồ ăn phổ biến trong tiếng Trung',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: '米饭', reading: 'mǐ fàn', meaning: 'cơm', example: '我每天吃米饭。', exampleMeaning: 'Tôi ăn cơm mỗi ngày.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '面条', reading: 'miàn tiáo', meaning: 'mì', example: '我喜欢吃面条。', exampleMeaning: 'Tôi thích ăn mì.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '鸡肉', reading: 'jī ròu', meaning: 'thịt gà', example: '鸡肉很好吃。', exampleMeaning: 'Thịt gà rất ngon.', difficulty: DIFFICULTY.EASY },
      { word: '牛肉', reading: 'niú ròu', meaning: 'thịt bò', example: '我要一份牛肉面。', exampleMeaning: 'Tôi muốn một tô mì bò.', difficulty: DIFFICULTY.EASY },
      { word: '猪肉', reading: 'zhū ròu', meaning: 'thịt heo', example: '猪肉在越南很受欢迎。', exampleMeaning: 'Thịt heo rất phổ biến ở Việt Nam.', difficulty: DIFFICULTY.EASY },
      { word: '鱼', reading: 'yú', meaning: 'cá', example: '这条鱼很新鲜。', exampleMeaning: 'Con cá này rất tươi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '蔬菜', reading: 'shū cài', meaning: 'rau', example: '多吃蔬菜对身体好。', exampleMeaning: 'Ăn nhiều rau tốt cho sức khỏe.', difficulty: DIFFICULTY.EASY },
      { word: '水果', reading: 'shuǐ guǒ', meaning: 'trái cây', example: '越南的水果很甜。', exampleMeaning: 'Trái cây Việt Nam rất ngọt.', difficulty: DIFFICULTY.EASY },
      { word: '鸡蛋', reading: 'jī dàn', meaning: 'trứng gà', example: '早餐吃鸡蛋。', exampleMeaning: 'Bữa sáng ăn trứng.', difficulty: DIFFICULTY.EASY },
      { word: '面包', reading: 'miàn bāo', meaning: 'bánh mì', example: '越南面包很有名。', exampleMeaning: 'Bánh mì Việt Nam rất nổi tiếng.', difficulty: DIFFICULTY.EASY },
      { word: '水', reading: 'shuǐ', meaning: 'nước', example: '请给我一杯水。', exampleMeaning: 'Cho tôi một ly nước.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '茶', reading: 'chá', meaning: 'trà', example: '你要喝茶吗？', exampleMeaning: 'Bạn muốn uống trà không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: '咖啡', reading: 'kā fēi', meaning: 'cà phê', example: '越南咖啡很浓。', exampleMeaning: 'Cà phê Việt Nam rất đậm.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '好吃', reading: 'hǎo chī', meaning: 'ngon', example: '这个菜很好吃！', exampleMeaning: 'Món này ngon quá!', difficulty: DIFFICULTY.VERY_EASY },
      { word: '饿', reading: 'è', meaning: 'đói', example: '我饿了，我们去吃饭吧。', exampleMeaning: 'Tôi đói rồi, đi ăn thôi.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"米饭" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Mì', 'Cơm', 'Bánh mì', 'Trứng'], answer: 'Cơm', explanation: '米饭 (mǐ fàn) = cơm', explanationVi: '米饭 (mǐ fàn) = cơm', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Pinyin của "好吃" là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['hǎo kàn', 'hǎo chī', 'hǎo hē', 'hǎo wán'], answer: 'hǎo chī', explanation: '好吃 đọc là "hǎo chī" = ngon', explanationVi: '好吃 đọc là "hǎo chī" = ngon', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "请给我一杯___。" (nước)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '水', explanation: '水 (shuǐ) = nước', explanationVi: '水 (shuǐ) = nước', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"Thịt bò" tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['鸡肉', '牛肉', '猪肉', '鱼'], answer: '牛肉', explanation: '牛肉 (niú ròu) = thịt bò', explanationVi: '牛肉 (niú ròu) = thịt bò', difficulty: DIFFICULTY.EASY },
      { question: 'Ghép: "蔬菜" = ?', type: QUIZ_TYPES.MATCHING, options: ['Trái cây', 'Rau', 'Thịt', 'Cá'], answer: 'Rau', explanation: '蔬菜 (shū cài) = rau', explanationVi: '蔬菜 (shū cài) = rau', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: '在餐厅 (At a Restaurant)',
    titleVi: 'Tại nhà hàng',
    description: 'Ordering food at Chinese restaurants',
    descriptionVi: 'Gọi món tại nhà hàng Trung Quốc',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: '菜单', reading: 'cài dān', meaning: 'thực đơn', example: '请给我菜单。', exampleMeaning: 'Cho tôi thực đơn.', difficulty: DIFFICULTY.EASY },
      { word: '点菜', reading: 'diǎn cài', meaning: 'gọi món', example: '我们可以点菜了。', exampleMeaning: 'Chúng tôi có thể gọi món rồi.', difficulty: DIFFICULTY.EASY },
      { word: '买单', reading: 'mǎi dān', meaning: 'thanh toán', example: '服务员，买单！', exampleMeaning: 'Phục vụ ơi, tính tiền!', difficulty: DIFFICULTY.EASY },
      { word: '服务员', reading: 'fú wù yuán', meaning: 'phục vụ', example: '服务员，请过来。', exampleMeaning: 'Phục vụ ơi, lại đây.', difficulty: DIFFICULTY.MEDIUM },
      { word: '辣', reading: 'là', meaning: 'cay', example: '这个菜辣不辣？', exampleMeaning: 'Món này có cay không?', difficulty: DIFFICULTY.EASY },
      { word: '甜', reading: 'tián', meaning: 'ngọt', example: '这个蛋糕太甜了。', exampleMeaning: 'Bánh này ngọt quá.', difficulty: DIFFICULTY.EASY },
      { word: '咸', reading: 'xián', meaning: 'mặn', example: '汤有点咸。', exampleMeaning: 'Canh hơi mặn.', difficulty: DIFFICULTY.EASY },
      { word: '酸', reading: 'suān', meaning: 'chua', example: '我喜欢酸辣汤。', exampleMeaning: 'Tôi thích canh chua cay.', difficulty: DIFFICULTY.EASY },
      { word: '筷子', reading: 'kuài zi', meaning: 'đũa', example: '请给我一双筷子。', exampleMeaning: 'Cho tôi một đôi đũa.', difficulty: DIFFICULTY.EASY },
      { word: '碗', reading: 'wǎn', meaning: 'bát/tô', example: '一碗米饭。', exampleMeaning: 'Một bát cơm.', difficulty: DIFFICULTY.EASY },
      { word: '杯', reading: 'bēi', meaning: 'ly/cốc', example: '一杯咖啡。', exampleMeaning: 'Một ly cà phê.', difficulty: DIFFICULTY.EASY },
      { word: '外卖', reading: 'wài mài', meaning: 'đồ ăn mang đi', example: '我们点外卖吧。', exampleMeaning: 'Đặt đồ ăn mang đi nhé.', difficulty: DIFFICULTY.EASY },
      { word: '打包', reading: 'dǎ bāo', meaning: 'gói mang về', example: '请帮我打包。', exampleMeaning: 'Gói cho tôi mang về.', difficulty: DIFFICULTY.MEDIUM },
      { word: '推荐', reading: 'tuī jiàn', meaning: 'đề xuất/giới thiệu', example: '你推荐什么菜？', exampleMeaning: 'Bạn giới thiệu món gì?', difficulty: DIFFICULTY.MEDIUM },
      { word: '份', reading: 'fèn', meaning: 'phần/suất', example: '两份炒饭。', exampleMeaning: 'Hai phần cơm chiên.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: 'Khi muốn tính tiền, bạn nói gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['点菜', '买单', '打包', '推荐'], answer: '买单', explanation: '买单 (mǎi dān) = thanh toán/tính tiền', explanationVi: '买单 (mǎi dān) = thanh toán/tính tiền', difficulty: DIFFICULTY.EASY },
      { question: '"辣" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Ngọt', 'Mặn', 'Cay', 'Chua'], answer: 'Cay', explanation: '辣 (là) = cay', explanationVi: '辣 (là) = cay', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "请给我___。" (thực đơn)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '菜单', explanation: '菜单 (cài dān) = thực đơn', explanationVi: '菜单 (cài dān) = thực đơn', difficulty: DIFFICULTY.EASY },
      { question: '"Đũa" tiếng Trung là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['碗', '杯', '筷子', '盘子'], answer: '筷子', explanation: '筷子 (kuài zi) = đũa', explanationVi: '筷子 (kuài zi) = đũa', difficulty: DIFFICULTY.EASY },
      { question: 'Ghép: "外卖" = ?', type: QUIZ_TYPES.MATCHING, options: ['Gọi món', 'Đồ ăn mang đi', 'Thanh toán', 'Đặt bàn'], answer: 'Đồ ăn mang đi', explanation: '外卖 (wài mài) = đồ ăn mang đi/giao hàng', explanationVi: '外卖 (wài mài) = đồ ăn mang đi/giao hàng', difficulty: DIFFICULTY.EASY },
    ],
  },
];
