import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const koreanFoodLessons: LessonData[] = [
  {
    title: '음식 (Food)',
    titleVi: 'Đồ ăn',
    description: 'Common food vocabulary in Korean',
    descriptionVi: 'Từ vựng về đồ ăn phổ biến trong tiếng Hàn',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: '밥', reading: 'bap', meaning: 'cơm', example: '밥 먹었어요?', exampleMeaning: 'Bạn ăn cơm chưa?', difficulty: DIFFICULTY.VERY_EASY },
      { word: '김치', reading: 'gimchi', meaning: 'kim chi', example: '김치는 한국 음식이에요.', exampleMeaning: 'Kim chi là món ăn Hàn Quốc.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '불고기', reading: 'bulgogi', meaning: 'thịt nướng Hàn', example: '불고기가 맛있어요.', exampleMeaning: 'Bulgogi ngon lắm.', difficulty: DIFFICULTY.EASY },
      { word: '치킨', reading: 'chikin', meaning: 'gà rán', example: '치킨 시킬까요?', exampleMeaning: 'Gọi gà rán nhé?', difficulty: DIFFICULTY.VERY_EASY },
      { word: '라면', reading: 'ramyeon', meaning: 'mì gói/ramen', example: '라면 먹고 싶어요.', exampleMeaning: 'Tôi muốn ăn mì.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '고기', reading: 'gogi', meaning: 'thịt', example: '고기를 좋아해요.', exampleMeaning: 'Tôi thích thịt.', difficulty: DIFFICULTY.EASY },
      { word: '생선', reading: 'saengseon', meaning: 'cá', example: '생선이 신선해요.', exampleMeaning: 'Cá rất tươi.', difficulty: DIFFICULTY.EASY },
      { word: '야채', reading: 'yachae', meaning: 'rau', example: '야채를 많이 먹어요.', exampleMeaning: 'Tôi ăn nhiều rau.', difficulty: DIFFICULTY.EASY },
      { word: '과일', reading: 'gwail', meaning: 'trái cây', example: '과일이 달아요.', exampleMeaning: 'Trái cây ngọt.', difficulty: DIFFICULTY.EASY },
      { word: '물', reading: 'mul', meaning: 'nước', example: '물 주세요.', exampleMeaning: 'Cho tôi nước.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '커피', reading: 'keopi', meaning: 'cà phê', example: '커피 한 잔 주세요.', exampleMeaning: 'Cho tôi một ly cà phê.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '맥주', reading: 'maekju', meaning: 'bia', example: '맥주 마실래요?', exampleMeaning: 'Uống bia không?', difficulty: DIFFICULTY.EASY },
      { word: '맛있다', reading: 'masitda', meaning: 'ngon', example: '이 음식 정말 맛있어요!', exampleMeaning: 'Món này ngon thật!', difficulty: DIFFICULTY.VERY_EASY },
      { word: '배고프다', reading: 'baegopuda', meaning: 'đói', example: '배고파요. 뭐 먹을까요?', exampleMeaning: 'Tôi đói. Ăn gì nhỉ?', difficulty: DIFFICULTY.EASY },
      { word: '떡볶이', reading: 'tteokbokki', meaning: 'bánh gạo cay', example: '떡볶이는 매워요.', exampleMeaning: 'Tteokbokki cay lắm.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"밥" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Mì', 'Cơm', 'Bánh mì', 'Kim chi'], answer: 'Cơm', explanation: '밥 (bap) = cơm. "밥 먹었어요?" là câu chào phổ biến', explanationVi: '밥 (bap) = cơm. "밥 먹었어요?" là câu chào phổ biến ở Hàn', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Cách đọc của "맛있다" là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['maepda', 'masitda', 'malhada', 'meokda'], answer: 'masitda', explanation: '맛있다 đọc là "masitda" = ngon', explanationVi: '맛있다 đọc là "masitda" = ngon', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "___ 주세요." (nước)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '물', explanation: '물 (mul) = nước. "물 주세요" = Cho tôi nước', explanationVi: '물 (mul) = nước. "물 주세요" = Cho tôi nước', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Món ăn nào là đặc trưng Hàn Quốc?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['寿司', '김치', 'ラーメン', '春卷'], answer: '김치', explanation: '김치 (gimchi/kimchi) là món ăn đặc trưng nhất của Hàn Quốc', explanationVi: '김치 (gimchi/kimchi) là món ăn đặc trưng nhất của Hàn Quốc', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Ghép: "배고프다" = ?', type: QUIZ_TYPES.MATCHING, options: ['No', 'Đói', 'Ngon', 'Cay'], answer: 'Đói', explanation: '배고프다 (baegopuda) = đói', explanationVi: '배고프다 (baegopuda) = đói', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: '식당에서 (At a Restaurant)',
    titleVi: 'Tại nhà hàng',
    description: 'Ordering food at Korean restaurants',
    descriptionVi: 'Gọi món tại nhà hàng Hàn Quốc',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: '메뉴', reading: 'menyu', meaning: 'thực đơn', example: '메뉴 좀 보여주세요.', exampleMeaning: 'Cho tôi xem thực đơn.', difficulty: DIFFICULTY.EASY },
      { word: '주문하다', reading: 'jumunhada', meaning: 'gọi món', example: '주문할게요.', exampleMeaning: 'Tôi sẽ gọi món.', difficulty: DIFFICULTY.EASY },
      { word: '계산', reading: 'gyesan', meaning: 'thanh toán', example: '계산해 주세요.', exampleMeaning: 'Cho tôi thanh toán.', difficulty: DIFFICULTY.EASY },
      { word: '매운', reading: 'maeun', meaning: 'cay', example: '이거 매워요?', exampleMeaning: 'Cái này cay không?', difficulty: DIFFICULTY.EASY },
      { word: '달다', reading: 'dalda', meaning: 'ngọt', example: '이 케이크 너무 달아요.', exampleMeaning: 'Bánh này ngọt quá.', difficulty: DIFFICULTY.EASY },
      { word: '짜다', reading: 'jjada', meaning: 'mặn', example: '국이 좀 짜요.', exampleMeaning: 'Canh hơi mặn.', difficulty: DIFFICULTY.EASY },
      { word: '젓가락', reading: 'jeotgarak', meaning: 'đũa', example: '젓가락 주세요.', exampleMeaning: 'Cho tôi đũa.', difficulty: DIFFICULTY.EASY },
      { word: '숟가락', reading: 'sutgarak', meaning: 'thìa/muỗng', example: '숟가락이 필요해요.', exampleMeaning: 'Tôi cần thìa.', difficulty: DIFFICULTY.EASY },
      { word: '포장', reading: 'pojang', meaning: 'gói mang đi', example: '포장해 주세요.', exampleMeaning: 'Gói cho tôi mang đi.', difficulty: DIFFICULTY.EASY },
      { word: '배달', reading: 'baedal', meaning: 'giao hàng', example: '배달 시킬까요?', exampleMeaning: 'Đặt giao hàng nhé?', difficulty: DIFFICULTY.EASY },
      { word: '인분', reading: 'inbun', meaning: 'phần (cho ... người)', example: '2인분 주세요.', exampleMeaning: 'Cho 2 phần.', difficulty: DIFFICULTY.MEDIUM },
      { word: '반찬', reading: 'banchan', meaning: 'món phụ/đồ ăn kèm', example: '반찬 더 주세요.', exampleMeaning: 'Cho thêm đồ ăn kèm.', difficulty: DIFFICULTY.EASY },
      { word: '추천', reading: 'chucheon', meaning: 'đề xuất', example: '추천 메뉴가 뭐예요?', exampleMeaning: 'Món đề xuất là gì?', difficulty: DIFFICULTY.MEDIUM },
      { word: '예약', reading: 'yeyak', meaning: 'đặt bàn', example: '예약했어요.', exampleMeaning: 'Tôi đã đặt bàn.', difficulty: DIFFICULTY.MEDIUM },
      { word: '잘 먹겠습니다', reading: 'jal meokgesseumnida', meaning: 'xin mời (trước khi ăn)', example: '잘 먹겠습니다!', exampleMeaning: 'Xin mời! (nói trước khi ăn)', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: 'Khi muốn thanh toán, bạn nói gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['주문할게요', '계산해 주세요', '포장해 주세요', '메뉴 주세요'], answer: '계산해 주세요', explanation: '계산해 주세요 = Cho tôi thanh toán', explanationVi: '계산해 주세요 = Cho tôi thanh toán', difficulty: DIFFICULTY.EASY },
      { question: '"매운" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Ngọt', 'Mặn', 'Cay', 'Chua'], answer: 'Cay', explanation: '매운 (maeun) = cay', explanationVi: '매운 (maeun) = cay', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "___ 주세요." (đũa)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '젓가락', explanation: '젓가락 (jeotgarak) = đũa', explanationVi: '젓가락 (jeotgarak) = đũa', difficulty: DIFFICULTY.EASY },
      { question: '"반찬" là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Món chính', 'Món phụ/đồ ăn kèm', 'Tráng miệng', 'Đồ uống'], answer: 'Món phụ/đồ ăn kèm', explanation: '반찬 (banchan) = món phụ, đặc trưng ẩm thực Hàn', explanationVi: '반찬 (banchan) = món phụ, đặc trưng ẩm thực Hàn', difficulty: DIFFICULTY.EASY },
      { question: 'Trước khi ăn, người Hàn nói gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['잘 먹겠습니다', '감사합니다', '안녕하세요', '맛있어요'], answer: '잘 먹겠습니다', explanation: '잘 먹겠습니다 nói trước khi ăn, giống いただきます của Nhật', explanationVi: '잘 먹겠습니다 nói trước khi ăn, giống いただきます của Nhật', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
