import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const koreanFamilyLessons: LessonData[] = [
  {
    title: 'Family Members (가족)',
    titleVi: 'Thành viên gia đình',
    description: 'Learn Korean vocabulary about family',
    descriptionVi: 'Học từ vựng tiếng Hàn về gia đình',
    topic: TOPICS.FAMILY,
    vocabulary: [
      { word: '가족', reading: 'gajok', meaning: 'gia đình', example: '우리 가족은 4명이에요.', exampleMeaning: 'Gia đình tôi có 4 người.', difficulty: DIFFICULTY.EASY },
      { word: '아버지', reading: 'abeoji', meaning: 'bố/cha', example: '아버지는 회사원이에요.', exampleMeaning: 'Bố tôi là nhân viên công ty.', difficulty: DIFFICULTY.EASY },
      { word: '어머니', reading: 'eomeoni', meaning: 'mẹ', example: '어머니는 요리를 잘해요.', exampleMeaning: 'Mẹ tôi nấu ăn giỏi.', difficulty: DIFFICULTY.EASY },
      { word: '형', reading: 'hyeong', meaning: 'anh trai (nam gọi)', example: '형은 대학생이에요.', exampleMeaning: 'Anh trai tôi là sinh viên đại học.', difficulty: DIFFICULTY.EASY },
      { word: '오빠', reading: 'oppa', meaning: 'anh trai (nữ gọi)', example: '오빠가 도와줬어요.', exampleMeaning: 'Anh trai đã giúp tôi.', difficulty: DIFFICULTY.EASY },
      { word: '누나', reading: 'nuna', meaning: 'chị gái (nam gọi)', example: '누나는 선생님이에요.', exampleMeaning: 'Chị gái tôi là giáo viên.', difficulty: DIFFICULTY.EASY },
      { word: '언니', reading: 'eonni', meaning: 'chị gái (nữ gọi)', example: '언니랑 쇼핑했어요.', exampleMeaning: 'Tôi đã đi mua sắm với chị.', difficulty: DIFFICULTY.EASY },
      { word: '동생', reading: 'dongsaeng', meaning: 'em (trai/gái)', example: '동생은 고등학생이에요.', exampleMeaning: 'Em tôi là học sinh cấp 3.', difficulty: DIFFICULTY.EASY },
      { word: '할아버지', reading: 'harabeoji', meaning: 'ông (nội/ngoại)', example: '할아버지는 건강하세요.', exampleMeaning: 'Ông tôi khỏe mạnh.', difficulty: DIFFICULTY.EASY },
      { word: '할머니', reading: 'halmeoni', meaning: 'bà (nội/ngoại)', example: '할머니 집에 갔어요.', exampleMeaning: 'Tôi đã đến nhà bà.', difficulty: DIFFICULTY.EASY },
      { word: '아들', reading: 'adeul', meaning: 'con trai', example: '아들이 두 명 있어요.', exampleMeaning: 'Tôi có hai con trai.', difficulty: DIFFICULTY.EASY },
      { word: '딸', reading: 'ttal', meaning: 'con gái', example: '딸은 5살이에요.', exampleMeaning: 'Con gái tôi 5 tuổi.', difficulty: DIFFICULTY.EASY },
      { word: '남편', reading: 'nampyeon', meaning: 'chồng', example: '남편은 의사예요.', exampleMeaning: 'Chồng tôi là bác sĩ.', difficulty: DIFFICULTY.EASY },
      { word: '아내', reading: 'anae', meaning: 'vợ', example: '아내와 여행했어요.', exampleMeaning: 'Tôi đã đi du lịch với vợ.', difficulty: DIFFICULTY.EASY },
      { word: '부모님', reading: 'bumonim', meaning: 'bố mẹ', example: '부모님을 사랑해요.', exampleMeaning: 'Tôi yêu bố mẹ.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Gia đình" tiếng Hàn là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['친구', '가족', '학교', '회사'], answer: '가족', explanation: '가족 = gia đình', explanationVi: '가족 = gia đình', difficulty: DIFFICULTY.EASY },
      { question: '"오빠" dùng khi nào?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Nam gọi anh trai', 'Nữ gọi anh trai', 'Nam gọi chị gái', 'Nữ gọi em'], answer: 'Nữ gọi anh trai', explanation: '오빠 = anh trai (nữ gọi)', explanationVi: '오빠 = anh trai (nữ gọi)', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "할머니" = ?', type: QUIZ_TYPES.MATCHING, options: ['Bà', 'Ông', 'Mẹ', 'Chị'], answer: 'Bà', explanation: '할머니 = bà', explanationVi: '할머니 = bà', difficulty: DIFFICULTY.EASY },
      { question: '"Con gái" tiếng Hàn là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['아들', '딸', '동생', '언니'], answer: '딸', explanation: '딸 = con gái', explanationVi: '딸 = con gái', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "___는 회사원이에요." (bố)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '아버지', explanation: '아버지 = bố/cha', explanationVi: '아버지 = bố/cha', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'School & Study (학교)',
    titleVi: 'Trường học & Học tập',
    description: 'Learn Korean vocabulary about school and studying',
    descriptionVi: 'Học từ vựng tiếng Hàn về trường học',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: '학교', reading: 'hakgyo', meaning: 'trường học', example: '학교에 가요.', exampleMeaning: 'Tôi đi học.', difficulty: DIFFICULTY.EASY },
      { word: '선생님', reading: 'seonsaengnim', meaning: 'giáo viên', example: '선생님이 친절해요.', exampleMeaning: 'Giáo viên rất tử tế.', difficulty: DIFFICULTY.EASY },
      { word: '학생', reading: 'haksaeng', meaning: 'học sinh/sinh viên', example: '저는 학생이에요.', exampleMeaning: 'Tôi là học sinh.', difficulty: DIFFICULTY.EASY },
      { word: '수업', reading: 'sueop', meaning: 'tiết học/lớp học', example: '수업이 재미있어요.', exampleMeaning: 'Tiết học thú vị.', difficulty: DIFFICULTY.EASY },
      { word: '숙제', reading: 'sukje', meaning: 'bài tập về nhà', example: '숙제를 했어요.', exampleMeaning: 'Tôi đã làm bài tập.', difficulty: DIFFICULTY.EASY },
      { word: '시험', reading: 'siheom', meaning: 'bài thi', example: '내일 시험이 있어요.', exampleMeaning: 'Ngày mai có bài thi.', difficulty: DIFFICULTY.EASY },
      { word: '책', reading: 'chaek', meaning: 'sách', example: '한국어 책을 읽어요.', exampleMeaning: 'Tôi đọc sách tiếng Hàn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '공부하다', reading: 'gongbuhada', meaning: 'học/học bài', example: '매일 공부해요.', exampleMeaning: 'Tôi học mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: '읽다', reading: 'ikda', meaning: 'đọc', example: '소설을 읽어요.', exampleMeaning: 'Tôi đọc tiểu thuyết.', difficulty: DIFFICULTY.EASY },
      { word: '쓰다', reading: 'sseuda', meaning: 'viết', example: '일기를 써요.', exampleMeaning: 'Tôi viết nhật ký.', difficulty: DIFFICULTY.EASY },
      { word: '듣다', reading: 'deutda', meaning: 'nghe', example: '음악을 들어요.', exampleMeaning: 'Tôi nghe nhạc.', difficulty: DIFFICULTY.EASY },
      { word: '말하다', reading: 'malhada', meaning: 'nói', example: '한국어로 말해요.', exampleMeaning: 'Tôi nói bằng tiếng Hàn.', difficulty: DIFFICULTY.EASY },
      { word: '질문', reading: 'jilmun', meaning: 'câu hỏi', example: '질문이 있어요.', exampleMeaning: 'Tôi có câu hỏi.', difficulty: DIFFICULTY.EASY },
      { word: '대학교', reading: 'daehakgyo', meaning: 'đại học', example: '대학교에서 경제학을 공부해요.', exampleMeaning: 'Tôi học kinh tế ở đại học.', difficulty: DIFFICULTY.EASY },
      { word: '도서관', reading: 'doseogwan', meaning: 'thư viện', example: '도서관에서 공부해요.', exampleMeaning: 'Tôi học ở thư viện.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Trường học" tiếng Hàn là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['학생', '학교', '수업', '선생님'], answer: '학교', explanation: '학교 = trường học', explanationVi: '학교 = trường học', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "숙제" = ?', type: QUIZ_TYPES.MATCHING, options: ['Bài tập về nhà', 'Bài thi', 'Tiết học', 'Sách'], answer: 'Bài tập về nhà', explanation: '숙제 = bài tập về nhà', explanationVi: '숙제 = bài tập về nhà', difficulty: DIFFICULTY.EASY },
      { question: '"Đọc" tiếng Hàn là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['쓰다', '읽다', '듣다', '말하다'], answer: '읽다', explanation: '읽다 = đọc', explanationVi: '읽다 = đọc', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "매일 ___해요." (học)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '공부', explanation: '공부하다 = học bài', explanationVi: '공부하다 = học bài', difficulty: DIFFICULTY.EASY },
      { question: '"Thư viện" tiếng Hàn là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['학교', '도서관', '대학교', '교실'], answer: '도서관', explanation: '도서관 = thư viện', explanationVi: '도서관 = thư viện', difficulty: DIFFICULTY.EASY },
    ],
  },
];
