export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    ME: '/auth/me',
    LOGOUT: '/auth/logout',
  },
  LANGUAGES: '/languages',
  LESSONS: '/lessons',
  VOCABULARY: '/vocabulary',
  QUIZ: '/quiz',
  PROGRESS: '/progress',
  CHAT: '/chat',
  ADMIN: '/admin',
  ACHIEVEMENTS: '/achievements',
  LEADERBOARD: '/leaderboard',
  GOALS: '/goals',
  STUDY: '/study',
  FLASHCARD_REVIEW: '/flashcard-review',
  DAILY_GOALS: '/daily-goals',
  STUDY_PLAN: '/study-plan',
  BOOKMARKS: '/bookmarks',
  WORD_OF_DAY: '/word-of-day',
  ANALYTICS: '/analytics',
  GRAMMAR_TIPS: '/grammar-tips',
  SENTENCE_BUILDER: '/sentence-builder',
  SEARCH: '/search',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  REVIEW_HISTORY: '/review-history',
  LEARNING_PROGRESS: '/learning-progress',
  TYPING_PRACTICE: '/typing-practice',
  PRONUNCIATION: '/pronunciation',
} as const;

export type ApiEndpoint = typeof API_ENDPOINTS;
