import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishHobbiesLessons: LessonData[] = [
  {
    title: 'Hobbies & Free Time',
    titleVi: 'Sở thích & Thời gian rảnh',
    description: 'Talk about hobbies and leisure activities',
    descriptionVi: 'Nói về sở thích và hoạt động giải trí',
    topic: TOPICS.HOBBIES,
    vocabulary: [
      { word: 'hobby', meaning: 'sở thích', example: 'What is your hobby?', exampleMeaning: 'Sở thích của bạn là gì?', difficulty: DIFFICULTY.EASY },
      { word: 'play sports', meaning: 'chơi thể thao', example: 'I play sports every weekend.', exampleMeaning: 'Tôi chơi thể thao mỗi cuối tuần.', difficulty: DIFFICULTY.EASY },
      { word: 'listen to music', meaning: 'nghe nhạc', example: 'I listen to music on the bus.', exampleMeaning: 'Tôi nghe nhạc trên xe buýt.', difficulty: DIFFICULTY.EASY },
      { word: 'watch movies', meaning: 'xem phim', example: 'Let\'s watch a movie tonight.', exampleMeaning: 'Tối nay xem phim nhé.', difficulty: DIFFICULTY.EASY },
      { word: 'play games', meaning: 'chơi game', example: 'I play games with my friends online.', exampleMeaning: 'Tôi chơi game online với bạn bè.', difficulty: DIFFICULTY.EASY },
      { word: 'travel', meaning: 'du lịch', example: 'I love to travel to new places.', exampleMeaning: 'Tôi thích du lịch đến nơi mới.', difficulty: DIFFICULTY.EASY },
      { word: 'cook', meaning: 'nấu ăn', example: 'I enjoy cooking Vietnamese food.', exampleMeaning: 'Tôi thích nấu đồ ăn Việt Nam.', difficulty: DIFFICULTY.EASY },
      { word: 'draw', meaning: 'vẽ', example: 'She likes to draw portraits.', exampleMeaning: 'Cô ấy thích vẽ chân dung.', difficulty: DIFFICULTY.EASY },
      { word: 'sing', meaning: 'hát', example: 'I sing karaoke with friends.', exampleMeaning: 'Tôi hát karaoke với bạn bè.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'dance', meaning: 'nhảy/khiêu vũ', example: 'She dances very well.', exampleMeaning: 'Cô ấy nhảy rất giỏi.', difficulty: DIFFICULTY.EASY },
      { word: 'photography', meaning: 'nhiếp ảnh', example: 'Photography is my passion.', exampleMeaning: 'Nhiếp ảnh là đam mê của tôi.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'gardening', meaning: 'làm vườn', example: 'My grandmother enjoys gardening.', exampleMeaning: 'Bà tôi thích làm vườn.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'swimming', meaning: 'bơi', example: 'I go swimming twice a week.', exampleMeaning: 'Tôi đi bơi hai lần một tuần.', difficulty: DIFFICULTY.EASY },
      { word: 'cycling', meaning: 'đạp xe', example: 'Cycling is good exercise.', exampleMeaning: 'Đạp xe là bài tập tốt.', difficulty: DIFFICULTY.EASY },
      { word: 'camping', meaning: 'cắm trại', example: 'We go camping in the mountains.', exampleMeaning: 'Chúng tôi đi cắm trại trên núi.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Sở thích" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Habit', 'Hobby', 'Hope', 'Home'], answer: 'Hobby', explanation: 'Sở thích = Hobby', explanationVi: 'Sở thích = Hobby', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "I _____ to music on the bus." (nghe)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'listen', explanation: 'Listen to music = nghe nhạc', explanationVi: 'Listen to music = nghe nhạc', difficulty: DIFFICULTY.EASY },
      { question: 'Which is a water sport?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Cycling', 'Swimming', 'Camping', 'Dancing'], answer: 'Swimming', explanation: 'Swimming = bơi (thể thao dưới nước)', explanationVi: 'Swimming = bơi (thể thao dưới nước)', difficulty: DIFFICULTY.EASY },
      { question: 'Match: "nhiếp ảnh" = ?', type: QUIZ_TYPES.MATCHING, options: ['Drawing', 'Photography', 'Painting', 'Filming'], answer: 'Photography', explanation: 'Photography = nhiếp ảnh', explanationVi: 'Photography = nhiếp ảnh', difficulty: DIFFICULTY.MEDIUM },
      { question: 'Arrange: "with / karaoke / I / friends / sing"', type: QUIZ_TYPES.ARRANGE, options: ['with', 'karaoke', 'I', 'friends', 'sing'], answer: 'I sing karaoke with friends', explanation: '"I sing karaoke with friends" = Tôi hát karaoke với bạn bè', explanationVi: '"I sing karaoke with friends" = Tôi hát karaoke với bạn bè', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Emotions & Feelings',
    titleVi: 'Cảm xúc & Tình cảm',
    description: 'Express your emotions in English',
    descriptionVi: 'Diễn đạt cảm xúc bằng tiếng Anh',
    topic: TOPICS.EMOTIONS,
    vocabulary: [
      { word: 'happy', meaning: 'vui/hạnh phúc', example: 'I am very happy today.', exampleMeaning: 'Hôm nay tôi rất vui.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'sad', meaning: 'buồn', example: 'She looks sad. What happened?', exampleMeaning: 'Cô ấy trông buồn. Chuyện gì vậy?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'angry', meaning: 'giận/tức', example: 'Don\'t be angry with me.', exampleMeaning: 'Đừng giận tôi.', difficulty: DIFFICULTY.EASY },
      { word: 'tired', meaning: 'mệt', example: 'I am tired after work.', exampleMeaning: 'Tôi mệt sau giờ làm.', difficulty: DIFFICULTY.EASY },
      { word: 'excited', meaning: 'hào hứng', example: 'I am excited about the trip!', exampleMeaning: 'Tôi hào hứng về chuyến đi!', difficulty: DIFFICULTY.EASY },
      { word: 'nervous', meaning: 'lo lắng/hồi hộp', example: 'I am nervous about the exam.', exampleMeaning: 'Tôi hồi hộp về bài thi.', difficulty: DIFFICULTY.EASY },
      { word: 'surprised', meaning: 'ngạc nhiên', example: 'I was surprised by the gift.', exampleMeaning: 'Tôi ngạc nhiên vì món quà.', difficulty: DIFFICULTY.EASY },
      { word: 'bored', meaning: 'chán', example: 'I am bored. Let\'s do something.', exampleMeaning: 'Tôi chán quá. Làm gì đi.', difficulty: DIFFICULTY.EASY },
      { word: 'scared', meaning: 'sợ', example: 'Are you scared of the dark?', exampleMeaning: 'Bạn có sợ bóng tối không?', difficulty: DIFFICULTY.EASY },
      { word: 'proud', meaning: 'tự hào', example: 'I am proud of you!', exampleMeaning: 'Tôi tự hào về bạn!', difficulty: DIFFICULTY.EASY },
      { word: 'lonely', meaning: 'cô đơn', example: 'She feels lonely in the new city.', exampleMeaning: 'Cô ấy cảm thấy cô đơn ở thành phố mới.', difficulty: DIFFICULTY.EASY },
      { word: 'confident', meaning: 'tự tin', example: 'Be confident in yourself!', exampleMeaning: 'Hãy tự tin vào bản thân!', difficulty: DIFFICULTY.MEDIUM },
      { word: 'disappointed', meaning: 'thất vọng', example: 'I am disappointed with the result.', exampleMeaning: 'Tôi thất vọng với kết quả.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'grateful', meaning: 'biết ơn', example: 'I am grateful for your help.', exampleMeaning: 'Tôi biết ơn sự giúp đỡ của bạn.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'jealous', meaning: 'ghen tị', example: 'Don\'t be jealous of others.', exampleMeaning: 'Đừng ghen tị với người khác.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Vui" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sad', 'Happy', 'Angry', 'Tired'], answer: 'Happy', explanation: 'Vui/Hạnh phúc = Happy', explanationVi: 'Vui/Hạnh phúc = Happy', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Fill in: "I am _____ about the exam." (hồi hộp)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'nervous', explanation: 'Nervous = lo lắng/hồi hộp', explanationVi: 'Nervous = lo lắng/hồi hộp', difficulty: DIFFICULTY.EASY },
      { question: 'Which is the opposite of "happy"?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Excited', 'Sad', 'Angry', 'Bored'], answer: 'Sad', explanation: 'Sad (buồn) is the opposite of happy (vui)', explanationVi: 'Sad (buồn) trái nghĩa với happy (vui)', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Match: "tự hào" = ?', type: QUIZ_TYPES.MATCHING, options: ['Proud', 'Confident', 'Happy', 'Grateful'], answer: 'Proud', explanation: 'Proud = tự hào', explanationVi: 'Proud = tự hào', difficulty: DIFFICULTY.EASY },
      { question: '"Biết ơn" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Grateful', 'Great', 'Grand', 'Graceful'], answer: 'Grateful', explanation: 'Grateful = biết ơn', explanationVi: 'Grateful = biết ơn', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
