import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishFoodLessons: LessonData[] = [
  {
    title: 'Food & Drinks',
    titleVi: 'Đồ ăn & Thức uống',
    description: 'Learn common food and drink vocabulary',
    descriptionVi: 'Học từ vựng về đồ ăn và thức uống phổ biến',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: 'rice', meaning: 'cơm/gạo', example: 'I eat rice every day.', exampleMeaning: 'Tôi ăn cơm mỗi ngày.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'noodles', meaning: 'mì/phở', example: 'Vietnamese noodle soup is delicious.', exampleMeaning: 'Phở Việt Nam rất ngon.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'chicken', meaning: 'thịt gà', example: 'I would like fried chicken.', exampleMeaning: 'Tôi muốn gà rán.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'beef', meaning: 'thịt bò', example: 'This beef steak is well done.', exampleMeaning: 'Miếng bít tết bò này chín kỹ.', difficulty: DIFFICULTY.EASY },
      { word: 'pork', meaning: 'thịt heo/lợn', example: 'Pork is popular in Vietnam.', exampleMeaning: 'Thịt heo phổ biến ở Việt Nam.', difficulty: DIFFICULTY.EASY },
      { word: 'fish', meaning: 'cá', example: 'I like grilled fish.', exampleMeaning: 'Tôi thích cá nướng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'egg', meaning: 'trứng', example: 'I have eggs for breakfast.', exampleMeaning: 'Tôi ăn trứng cho bữa sáng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'bread', meaning: 'bánh mì', example: 'Vietnamese bread is famous.', exampleMeaning: 'Bánh mì Việt Nam nổi tiếng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'vegetable', meaning: 'rau', example: 'Eat more vegetables for health.', exampleMeaning: 'Ăn nhiều rau để khỏe mạnh.', difficulty: DIFFICULTY.EASY },
      { word: 'fruit', meaning: 'trái cây', example: 'Tropical fruits are sweet.', exampleMeaning: 'Trái cây nhiệt đới rất ngọt.', difficulty: DIFFICULTY.EASY },
      { word: 'water', meaning: 'nước', example: 'Can I have a glass of water?', exampleMeaning: 'Cho tôi một ly nước được không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'coffee', meaning: 'cà phê', example: 'Vietnamese coffee is very strong.', exampleMeaning: 'Cà phê Việt Nam rất đậm.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'tea', meaning: 'trà', example: 'Would you like some tea?', exampleMeaning: 'Bạn có muốn uống trà không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'milk', meaning: 'sữa', example: 'I drink milk every morning.', exampleMeaning: 'Tôi uống sữa mỗi sáng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'juice', meaning: 'nước ép', example: 'Orange juice is refreshing.', exampleMeaning: 'Nước cam rất mát.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Rice" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Mì', 'Cơm/Gạo', 'Bánh mì', 'Trứng'], answer: 'Cơm/Gạo', explanation: '"Rice" means cơm/gạo - the staple food in Vietnam', explanationVi: '"Rice" nghĩa là cơm/gạo - thực phẩm chính ở Việt Nam', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'What is "cà phê" in English?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Tea', 'Coffee', 'Milk', 'Juice'], answer: 'Coffee', explanation: 'Cà phê = Coffee. Vietnamese coffee is world-famous!', explanationVi: 'Cà phê = Coffee. Cà phê Việt Nam nổi tiếng thế giới!', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Fill in: "I eat _____ every day." (cơm)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'rice', explanation: 'Rice is the English word for cơm/gạo', explanationVi: '"Rice" là từ tiếng Anh cho cơm/gạo', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Which is NOT a meat?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Chicken', 'Beef', 'Bread', 'Pork'], answer: 'Bread', explanation: 'Bread (bánh mì) is not a meat. Chicken, beef, pork are meats.', explanationVi: 'Bread (bánh mì) không phải thịt. Chicken, beef, pork là thịt.', difficulty: DIFFICULTY.EASY },
      { question: 'Match: "trái cây" = ?', type: QUIZ_TYPES.MATCHING, options: ['Vegetable', 'Fruit', 'Fish', 'Egg'], answer: 'Fruit', explanation: 'Trái cây = Fruit', explanationVi: 'Trái cây = Fruit (hoa quả)', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'At the Restaurant',
    titleVi: 'Tại nhà hàng',
    description: 'Useful phrases for ordering food at restaurants',
    descriptionVi: 'Các cụm từ hữu ích khi gọi món tại nhà hàng',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: 'menu', meaning: 'thực đơn', example: 'Can I see the menu, please?', exampleMeaning: 'Cho tôi xem thực đơn được không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'order', meaning: 'gọi món', example: 'Are you ready to order?', exampleMeaning: 'Bạn sẵn sàng gọi món chưa?', difficulty: DIFFICULTY.EASY },
      { word: 'bill', meaning: 'hóa đơn', example: 'Can I have the bill, please?', exampleMeaning: 'Cho tôi hóa đơn được không?', difficulty: DIFFICULTY.EASY },
      { word: 'waiter', meaning: 'phục vụ (nam)', example: 'The waiter is very friendly.', exampleMeaning: 'Anh phục vụ rất thân thiện.', difficulty: DIFFICULTY.EASY },
      { word: 'delicious', meaning: 'ngon', example: 'This food is delicious!', exampleMeaning: 'Món ăn này ngon quá!', difficulty: DIFFICULTY.EASY },
      { word: 'spicy', meaning: 'cay', example: 'Is this dish spicy?', exampleMeaning: 'Món này có cay không?', difficulty: DIFFICULTY.EASY },
      { word: 'sweet', meaning: 'ngọt', example: 'The dessert is too sweet.', exampleMeaning: 'Món tráng miệng ngọt quá.', difficulty: DIFFICULTY.EASY },
      { word: 'sour', meaning: 'chua', example: 'I like sour soup.', exampleMeaning: 'Tôi thích canh chua.', difficulty: DIFFICULTY.EASY },
      { word: 'salty', meaning: 'mặn', example: 'This soup is too salty.', exampleMeaning: 'Canh này mặn quá.', difficulty: DIFFICULTY.EASY },
      { word: 'appetizer', meaning: 'món khai vị', example: 'What appetizers do you have?', exampleMeaning: 'Có món khai vị gì?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'main course', meaning: 'món chính', example: 'For the main course, I\'ll have steak.', exampleMeaning: 'Món chính, tôi chọn bít tết.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'dessert', meaning: 'tráng miệng', example: 'Would you like dessert?', exampleMeaning: 'Bạn có muốn tráng miệng không?', difficulty: DIFFICULTY.EASY },
      { word: 'tip', meaning: 'tiền boa', example: 'Should I leave a tip?', exampleMeaning: 'Tôi có nên để tiền boa không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'reservation', meaning: 'đặt bàn', example: 'I have a reservation for two.', exampleMeaning: 'Tôi đã đặt bàn cho hai người.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'takeaway', meaning: 'mang đi', example: 'I\'d like this to go / takeaway.', exampleMeaning: 'Tôi muốn mang đi.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: 'How do you ask for the bill?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Can I have the menu?', 'Can I have the bill?', 'Can I have water?', 'Can I order?'], answer: 'Can I have the bill?', explanation: '"Can I have the bill?" is how you ask to pay', explanationVi: '"Can I have the bill?" là cách hỏi khi muốn thanh toán', difficulty: DIFFICULTY.EASY },
      { question: '"Cay" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sweet', 'Sour', 'Spicy', 'Salty'], answer: 'Spicy', explanation: 'Cay = Spicy. Vietnamese food is often spicy!', explanationVi: 'Cay = Spicy. Đồ ăn Việt Nam thường cay!', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "Are you ready to _____?" (gọi món)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'order', explanation: '"Are you ready to order?" - the waiter asks this', explanationVi: '"Are you ready to order?" - phục vụ hỏi câu này', difficulty: DIFFICULTY.EASY },
      { question: 'Which word means "ngon"?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Delicious', 'Spicy', 'Expensive', 'Beautiful'], answer: 'Delicious', explanation: 'Delicious = ngon (dùng cho đồ ăn)', explanationVi: 'Delicious = ngon (dùng cho đồ ăn)', difficulty: DIFFICULTY.EASY },
      { question: 'Arrange: "the / Can / menu / I / see / ?"', type: QUIZ_TYPES.ARRANGE, options: ['the', 'Can', 'menu', 'I', 'see', '?'], answer: 'Can I see the menu ?', explanation: '"Can I see the menu?" - polite request to see the menu', explanationVi: '"Can I see the menu?" - yêu cầu lịch sự xem thực đơn', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
  {
    title: 'Shopping for Groceries',
    titleVi: 'Đi chợ mua đồ',
    description: 'Vocabulary for buying food and daily items',
    descriptionVi: 'Từ vựng khi mua đồ ăn và vật dụng hàng ngày',
    topic: TOPICS.SHOPPING,
    vocabulary: [
      { word: 'supermarket', meaning: 'siêu thị', example: 'I go to the supermarket every week.', exampleMeaning: 'Tôi đi siêu thị mỗi tuần.', difficulty: DIFFICULTY.EASY },
      { word: 'market', meaning: 'chợ', example: 'The morning market has fresh food.', exampleMeaning: 'Chợ sáng có đồ ăn tươi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'price', meaning: 'giá', example: 'What is the price of this?', exampleMeaning: 'Cái này giá bao nhiêu?', difficulty: DIFFICULTY.EASY },
      { word: 'cheap', meaning: 'rẻ', example: 'This is very cheap!', exampleMeaning: 'Cái này rẻ quá!', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'expensive', meaning: 'đắt', example: 'That bag is too expensive.', exampleMeaning: 'Cái túi đó đắt quá.', difficulty: DIFFICULTY.EASY },
      { word: 'discount', meaning: 'giảm giá', example: 'Is there a discount?', exampleMeaning: 'Có giảm giá không?', difficulty: DIFFICULTY.EASY },
      { word: 'fresh', meaning: 'tươi', example: 'These vegetables are very fresh.', exampleMeaning: 'Rau này rất tươi.', difficulty: DIFFICULTY.EASY },
      { word: 'kilogram', meaning: 'ki-lô-gam', example: 'Two kilograms of rice, please.', exampleMeaning: 'Cho tôi hai ký gạo.', difficulty: DIFFICULTY.EASY },
      { word: 'bag', meaning: 'túi', example: 'Do you need a bag?', exampleMeaning: 'Bạn có cần túi không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'change', meaning: 'tiền thối', example: 'Here is your change.', exampleMeaning: 'Đây là tiền thối của bạn.', difficulty: DIFFICULTY.EASY },
      { word: 'cash', meaning: 'tiền mặt', example: 'Do you accept cash?', exampleMeaning: 'Bạn có nhận tiền mặt không?', difficulty: DIFFICULTY.EASY },
      { word: 'receipt', meaning: 'hóa đơn/biên lai', example: 'Can I have a receipt?', exampleMeaning: 'Cho tôi hóa đơn được không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'aisle', meaning: 'lối đi (trong siêu thị)', example: 'The milk is in aisle 3.', exampleMeaning: 'Sữa ở lối đi số 3.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'cart', meaning: 'xe đẩy', example: 'I need a shopping cart.', exampleMeaning: 'Tôi cần xe đẩy mua hàng.', difficulty: DIFFICULTY.EASY },
      { word: 'checkout', meaning: 'quầy thanh toán', example: 'The checkout line is long.', exampleMeaning: 'Hàng chờ thanh toán dài quá.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Siêu thị" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Market', 'Supermarket', 'Shop', 'Store'], answer: 'Supermarket', explanation: 'Siêu thị = Supermarket (larger than a market/shop)', explanationVi: 'Siêu thị = Supermarket (lớn hơn chợ/cửa hàng)', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "Is there a _____?" (giảm giá)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'discount', explanation: '"Is there a discount?" - asking for a price reduction', explanationVi: '"Is there a discount?" - hỏi có giảm giá không', difficulty: DIFFICULTY.EASY },
      { question: 'Which means "đắt"?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Cheap', 'Expensive', 'Fresh', 'Free'], answer: 'Expensive', explanation: 'Expensive = đắt (opposite of cheap/rẻ)', explanationVi: 'Expensive = đắt (trái nghĩa với cheap/rẻ)', difficulty: DIFFICULTY.EASY },
      { question: 'Match: "tiền thối" = ?', type: QUIZ_TYPES.MATCHING, options: ['Cash', 'Change', 'Price', 'Receipt'], answer: 'Change', explanation: 'Change = tiền thối (money returned after paying)', explanationVi: 'Change = tiền thối (tiền trả lại sau khi thanh toán)', difficulty: DIFFICULTY.EASY },
      { question: 'Where do you pay at a supermarket?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Aisle', 'Cart', 'Checkout', 'Market'], answer: 'Checkout', explanation: 'Checkout = quầy thanh toán', explanationVi: 'Checkout = quầy thanh toán', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
