import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishFamilyLessons: LessonData[] = [
  {
    title: 'Family Members',
    titleVi: 'Thành viên gia đình',
    description: 'Learn vocabulary about family relationships',
    descriptionVi: 'Học từ vựng về các mối quan hệ gia đình',
    topic: TOPICS.FAMILY,
    vocabulary: [
      { word: 'father', meaning: 'bố/cha', example: 'My father is a teacher.', exampleMeaning: 'Bố tôi là giáo viên.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'mother', meaning: 'mẹ', example: 'My mother cooks very well.', exampleMeaning: 'Mẹ tôi nấu ăn rất ngon.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'brother', meaning: 'anh/em trai', example: 'I have two brothers.', exampleMeaning: 'Tôi có hai anh em trai.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'sister', meaning: 'chị/em gái', example: 'My sister is older than me.', exampleMeaning: 'Chị tôi lớn hơn tôi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'grandfather', meaning: 'ông', example: 'My grandfather is 80 years old.', exampleMeaning: 'Ông tôi 80 tuổi.', difficulty: DIFFICULTY.EASY },
      { word: 'grandmother', meaning: 'bà', example: 'My grandmother makes great pho.', exampleMeaning: 'Bà tôi nấu phở rất ngon.', difficulty: DIFFICULTY.EASY },
      { word: 'uncle', meaning: 'chú/bác/cậu', example: 'My uncle lives in Ho Chi Minh City.', exampleMeaning: 'Chú tôi sống ở TP.HCM.', difficulty: DIFFICULTY.EASY },
      { word: 'aunt', meaning: 'cô/dì/bác gái', example: 'My aunt is a doctor.', exampleMeaning: 'Cô tôi là bác sĩ.', difficulty: DIFFICULTY.EASY },
      { word: 'cousin', meaning: 'anh/chị/em họ', example: 'I have many cousins.', exampleMeaning: 'Tôi có nhiều anh chị em họ.', difficulty: DIFFICULTY.EASY },
      { word: 'husband', meaning: 'chồng', example: 'Her husband is an engineer.', exampleMeaning: 'Chồng cô ấy là kỹ sư.', difficulty: DIFFICULTY.EASY },
      { word: 'wife', meaning: 'vợ', example: 'His wife is very kind.', exampleMeaning: 'Vợ anh ấy rất tốt bụng.', difficulty: DIFFICULTY.EASY },
      { word: 'son', meaning: 'con trai', example: 'Their son is a student.', exampleMeaning: 'Con trai họ là sinh viên.', difficulty: DIFFICULTY.EASY },
      { word: 'daughter', meaning: 'con gái', example: 'My daughter loves reading.', exampleMeaning: 'Con gái tôi thích đọc sách.', difficulty: DIFFICULTY.EASY },
      { word: 'parents', meaning: 'bố mẹ', example: 'I live with my parents.', exampleMeaning: 'Tôi sống với bố mẹ.', difficulty: DIFFICULTY.EASY },
      { word: 'children', meaning: 'con cái', example: 'They have three children.', exampleMeaning: 'Họ có ba đứa con.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Mẹ" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Father', 'Mother', 'Sister', 'Aunt'], answer: 'Mother', explanation: 'Mẹ = Mother', explanationVi: 'Mẹ = Mother', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Fill in: "My _____ is a teacher." (bố)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'father', explanation: 'Father = bố/cha', explanationVi: 'Father = bố/cha', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Which word means "ông"?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Uncle', 'Father', 'Grandfather', 'Brother'], answer: 'Grandfather', explanation: 'Grandfather = ông (bố của bố/mẹ)', explanationVi: 'Grandfather = ông (bố của bố/mẹ)', difficulty: DIFFICULTY.EASY },
      { question: 'Match: "anh/chị/em họ" = ?', type: QUIZ_TYPES.MATCHING, options: ['Brother', 'Sister', 'Cousin', 'Uncle'], answer: 'Cousin', explanation: 'Cousin = anh/chị/em họ', explanationVi: 'Cousin = anh/chị/em họ', difficulty: DIFFICULTY.EASY },
      { question: '"Children" means...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Bố mẹ', 'Con cái', 'Anh em', 'Ông bà'], answer: 'Con cái', explanation: 'Children = con cái (số nhiều của child)', explanationVi: 'Children = con cái (số nhiều của child)', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Daily Routines',
    titleVi: 'Thói quen hàng ngày',
    description: 'Describe your daily activities in English',
    descriptionVi: 'Mô tả hoạt động hàng ngày bằng tiếng Anh',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: 'wake up', meaning: 'thức dậy', example: 'I wake up at 6 AM.', exampleMeaning: 'Tôi thức dậy lúc 6 giờ sáng.', difficulty: DIFFICULTY.EASY },
      { word: 'brush teeth', meaning: 'đánh răng', example: 'I brush my teeth twice a day.', exampleMeaning: 'Tôi đánh răng hai lần một ngày.', difficulty: DIFFICULTY.EASY },
      { word: 'take a shower', meaning: 'tắm', example: 'I take a shower every morning.', exampleMeaning: 'Tôi tắm mỗi sáng.', difficulty: DIFFICULTY.EASY },
      { word: 'get dressed', meaning: 'mặc quần áo', example: 'I get dressed for work.', exampleMeaning: 'Tôi mặc quần áo đi làm.', difficulty: DIFFICULTY.EASY },
      { word: 'have breakfast', meaning: 'ăn sáng', example: 'I have breakfast at 7 AM.', exampleMeaning: 'Tôi ăn sáng lúc 7 giờ.', difficulty: DIFFICULTY.EASY },
      { word: 'go to work', meaning: 'đi làm', example: 'I go to work by motorbike.', exampleMeaning: 'Tôi đi làm bằng xe máy.', difficulty: DIFFICULTY.EASY },
      { word: 'have lunch', meaning: 'ăn trưa', example: 'I have lunch at noon.', exampleMeaning: 'Tôi ăn trưa lúc 12 giờ.', difficulty: DIFFICULTY.EASY },
      { word: 'come home', meaning: 'về nhà', example: 'I come home at 6 PM.', exampleMeaning: 'Tôi về nhà lúc 6 giờ tối.', difficulty: DIFFICULTY.EASY },
      { word: 'cook dinner', meaning: 'nấu bữa tối', example: 'My mom cooks dinner.', exampleMeaning: 'Mẹ tôi nấu bữa tối.', difficulty: DIFFICULTY.EASY },
      { word: 'watch TV', meaning: 'xem TV', example: 'I watch TV after dinner.', exampleMeaning: 'Tôi xem TV sau bữa tối.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'do homework', meaning: 'làm bài tập', example: 'Students do homework every day.', exampleMeaning: 'Học sinh làm bài tập mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: 'go to bed', meaning: 'đi ngủ', example: 'I go to bed at 11 PM.', exampleMeaning: 'Tôi đi ngủ lúc 11 giờ đêm.', difficulty: DIFFICULTY.EASY },
      { word: 'exercise', meaning: 'tập thể dục', example: 'I exercise in the morning.', exampleMeaning: 'Tôi tập thể dục buổi sáng.', difficulty: DIFFICULTY.EASY },
      { word: 'read a book', meaning: 'đọc sách', example: 'I read a book before bed.', exampleMeaning: 'Tôi đọc sách trước khi ngủ.', difficulty: DIFFICULTY.EASY },
      { word: 'clean the house', meaning: 'dọn nhà', example: 'I clean the house on weekends.', exampleMeaning: 'Tôi dọn nhà vào cuối tuần.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Thức dậy" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Go to bed', 'Wake up', 'Get up', 'Stand up'], answer: 'Wake up', explanation: 'Wake up = thức dậy', explanationVi: 'Wake up = thức dậy', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "I _____ my teeth twice a day." (đánh răng)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'brush', explanation: 'Brush teeth = đánh răng', explanationVi: 'Brush teeth = đánh răng', difficulty: DIFFICULTY.EASY },
      { question: 'What do you do first in the morning?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Have lunch', 'Go to bed', 'Wake up', 'Cook dinner'], answer: 'Wake up', explanation: 'The first thing in the morning is to wake up', explanationVi: 'Việc đầu tiên buổi sáng là thức dậy', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Arrange: "to / I / work / go / by / motorbike"', type: QUIZ_TYPES.ARRANGE, options: ['to', 'I', 'work', 'go', 'by', 'motorbike'], answer: 'I go to work by motorbike', explanation: '"I go to work by motorbike" = Tôi đi làm bằng xe máy', explanationVi: '"I go to work by motorbike" = Tôi đi làm bằng xe máy', difficulty: DIFFICULTY.MEDIUM },
      { question: 'Match: "đi ngủ" = ?', type: QUIZ_TYPES.MATCHING, options: ['Wake up', 'Go to bed', 'Take a shower', 'Get dressed'], answer: 'Go to bed', explanation: 'Go to bed = đi ngủ', explanationVi: 'Go to bed = đi ngủ', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'School & Education',
    titleVi: 'Trường học & Giáo dục',
    description: 'Vocabulary related to school and studying',
    descriptionVi: 'Từ vựng liên quan đến trường học và việc học',
    topic: TOPICS.SCHOOL,
    vocabulary: [
      { word: 'school', meaning: 'trường học', example: 'I go to school every day.', exampleMeaning: 'Tôi đi học mỗi ngày.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'teacher', meaning: 'giáo viên', example: 'My teacher is very patient.', exampleMeaning: 'Giáo viên của tôi rất kiên nhẫn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'student', meaning: 'học sinh/sinh viên', example: 'There are 40 students in my class.', exampleMeaning: 'Lớp tôi có 40 học sinh.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'classroom', meaning: 'phòng học', example: 'Our classroom is on the 3rd floor.', exampleMeaning: 'Phòng học của chúng tôi ở tầng 3.', difficulty: DIFFICULTY.EASY },
      { word: 'homework', meaning: 'bài tập về nhà', example: 'I have a lot of homework today.', exampleMeaning: 'Hôm nay tôi có nhiều bài tập.', difficulty: DIFFICULTY.EASY },
      { word: 'exam', meaning: 'bài thi', example: 'The exam is next week.', exampleMeaning: 'Bài thi vào tuần sau.', difficulty: DIFFICULTY.EASY },
      { word: 'subject', meaning: 'môn học', example: 'English is my favorite subject.', exampleMeaning: 'Tiếng Anh là môn học yêu thích của tôi.', difficulty: DIFFICULTY.EASY },
      { word: 'notebook', meaning: 'vở', example: 'Open your notebooks, please.', exampleMeaning: 'Mở vở ra nào.', difficulty: DIFFICULTY.EASY },
      { word: 'pen', meaning: 'bút', example: 'Can I borrow your pen?', exampleMeaning: 'Cho tôi mượn bút được không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'textbook', meaning: 'sách giáo khoa', example: 'Please open your textbook to page 10.', exampleMeaning: 'Mở sách giáo khoa trang 10.', difficulty: DIFFICULTY.EASY },
      { word: 'library', meaning: 'thư viện', example: 'I study at the library.', exampleMeaning: 'Tôi học ở thư viện.', difficulty: DIFFICULTY.EASY },
      { word: 'grade', meaning: 'điểm/lớp', example: 'I got a good grade on the test.', exampleMeaning: 'Tôi được điểm tốt trong bài kiểm tra.', difficulty: DIFFICULTY.EASY },
      { word: 'graduate', meaning: 'tốt nghiệp', example: 'I will graduate next year.', exampleMeaning: 'Tôi sẽ tốt nghiệp năm sau.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'scholarship', meaning: 'học bổng', example: 'She got a scholarship to study abroad.', exampleMeaning: 'Cô ấy được học bổng du học.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'semester', meaning: 'học kỳ', example: 'This semester I study 6 subjects.', exampleMeaning: 'Học kỳ này tôi học 6 môn.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Giáo viên" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Student', 'Teacher', 'Doctor', 'Driver'], answer: 'Teacher', explanation: 'Giáo viên = Teacher', explanationVi: 'Giáo viên = Teacher', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Fill in: "I have a lot of _____ today." (bài tập)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'homework', explanation: 'Homework = bài tập về nhà', explanationVi: 'Homework = bài tập về nhà', difficulty: DIFFICULTY.EASY },
      { question: 'Where do you borrow books?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Classroom', 'Library', 'Cafeteria', 'Office'], answer: 'Library', explanation: 'Library = thư viện, nơi mượn sách', explanationVi: 'Library = thư viện, nơi mượn sách', difficulty: DIFFICULTY.EASY },
      { question: 'Match: "học bổng" = ?', type: QUIZ_TYPES.MATCHING, options: ['Grade', 'Scholarship', 'Semester', 'Exam'], answer: 'Scholarship', explanation: 'Scholarship = học bổng', explanationVi: 'Scholarship = học bổng', difficulty: DIFFICULTY.MEDIUM },
      { question: '"Tốt nghiệp" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Study', 'Graduate', 'Enroll', 'Register'], answer: 'Graduate', explanation: 'Graduate = tốt nghiệp', explanationVi: 'Graduate = tốt nghiệp', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
