import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishHealthLessons: LessonData[] = [
  {
    title: 'Body Parts',
    titleVi: 'Bộ phận cơ thể',
    description: 'Learn vocabulary about body parts',
    descriptionVi: 'Học từ vựng về các bộ phận cơ thể',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: 'head', meaning: 'đầu', example: 'My head hurts.', exampleMeaning: 'Đầu tôi đau.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'eye', meaning: 'mắt', example: 'She has beautiful eyes.', exampleMeaning: 'Cô ấy có đôi mắt đẹp.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'ear', meaning: 'tai', example: 'I cannot hear with my left ear.', exampleMeaning: 'Tôi không nghe được bằng tai trái.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'nose', meaning: 'mũi', example: 'My nose is running.', exampleMeaning: 'Tôi bị chảy mũi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'mouth', meaning: 'miệng', example: 'Open your mouth, please.', exampleMeaning: 'Hãy mở miệng ra.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'hand', meaning: 'tay (bàn tay)', example: 'Wash your hands before eating.', exampleMeaning: 'Rửa tay trước khi ăn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'arm', meaning: 'cánh tay', example: 'I broke my arm.', exampleMeaning: 'Tôi bị gãy tay.', difficulty: DIFFICULTY.EASY },
      { word: 'leg', meaning: 'chân (cả chân)', example: 'My legs are tired from walking.', exampleMeaning: 'Chân tôi mỏi vì đi bộ.', difficulty: DIFFICULTY.EASY },
      { word: 'foot', meaning: 'bàn chân', example: 'My foot is swollen.', exampleMeaning: 'Bàn chân tôi bị sưng.', difficulty: DIFFICULTY.EASY },
      { word: 'stomach', meaning: 'bụng/dạ dày', example: 'I have a stomachache.', exampleMeaning: 'Tôi bị đau bụng.', difficulty: DIFFICULTY.EASY },
      { word: 'back', meaning: 'lưng', example: 'My back hurts from sitting.', exampleMeaning: 'Lưng tôi đau vì ngồi nhiều.', difficulty: DIFFICULTY.EASY },
      { word: 'heart', meaning: 'tim', example: 'Exercise is good for your heart.', exampleMeaning: 'Tập thể dục tốt cho tim.', difficulty: DIFFICULTY.EASY },
      { word: 'tooth', meaning: 'răng', example: 'I have a toothache.', exampleMeaning: 'Tôi bị đau răng.', difficulty: DIFFICULTY.EASY },
      { word: 'finger', meaning: 'ngón tay', example: 'I cut my finger.', exampleMeaning: 'Tôi bị đứt ngón tay.', difficulty: DIFFICULTY.EASY },
      { word: 'shoulder', meaning: 'vai', example: 'My shoulders are tense.', exampleMeaning: 'Vai tôi bị căng.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Đầu" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Hand', 'Head', 'Heart', 'Hair'], answer: 'Head', explanation: 'Head = đầu', explanationVi: 'Head = đầu', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Điền: "Wash your ___ before eating." (tay)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'hands', explanation: 'Hands = tay (bàn tay)', explanationVi: 'Hands = tay (bàn tay)', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"Bụng/dạ dày" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Back', 'Stomach', 'Shoulder', 'Chest'], answer: 'Stomach', explanation: 'Stomach = bụng/dạ dày', explanationVi: 'Stomach = bụng/dạ dày', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "tooth" = ?', type: QUIZ_TYPES.MATCHING, options: ['Răng', 'Tai', 'Mũi', 'Mắt'], answer: 'Răng', explanation: 'Tooth = răng', explanationVi: 'Tooth = răng', difficulty: DIFFICULTY.EASY },
      { question: '"Tim" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Head', 'Hand', 'Heart', 'Hair'], answer: 'Heart', explanation: 'Heart = tim', explanationVi: 'Heart = tim', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'At the Doctor',
    titleVi: 'Ở phòng khám',
    description: 'Learn health-related vocabulary and phrases',
    descriptionVi: 'Học từ vựng và cụm từ liên quan đến sức khỏe',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: 'sick', meaning: 'ốm/bệnh', example: 'I feel sick today.', exampleMeaning: 'Hôm nay tôi thấy ốm.', difficulty: DIFFICULTY.EASY },
      { word: 'fever', meaning: 'sốt', example: 'I have a high fever.', exampleMeaning: 'Tôi bị sốt cao.', difficulty: DIFFICULTY.EASY },
      { word: 'cough', meaning: 'ho', example: 'I have a bad cough.', exampleMeaning: 'Tôi bị ho nặng.', difficulty: DIFFICULTY.EASY },
      { word: 'headache', meaning: 'đau đầu', example: 'I have a terrible headache.', exampleMeaning: 'Tôi bị đau đầu kinh khủng.', difficulty: DIFFICULTY.EASY },
      { word: 'cold', meaning: 'cảm lạnh', example: 'I caught a cold.', exampleMeaning: 'Tôi bị cảm lạnh.', difficulty: DIFFICULTY.EASY },
      { word: 'medicine', meaning: 'thuốc', example: 'Take this medicine twice a day.', exampleMeaning: 'Uống thuốc này hai lần một ngày.', difficulty: DIFFICULTY.EASY },
      { word: 'doctor', meaning: 'bác sĩ', example: 'I need to see a doctor.', exampleMeaning: 'Tôi cần gặp bác sĩ.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'hospital', meaning: 'bệnh viện', example: 'He is in the hospital.', exampleMeaning: 'Anh ấy đang ở bệnh viện.', difficulty: DIFFICULTY.EASY },
      { word: 'pharmacy', meaning: 'nhà thuốc', example: 'I bought medicine at the pharmacy.', exampleMeaning: 'Tôi mua thuốc ở nhà thuốc.', difficulty: DIFFICULTY.EASY },
      { word: 'pain', meaning: 'đau', example: 'I feel pain in my back.', exampleMeaning: 'Tôi thấy đau ở lưng.', difficulty: DIFFICULTY.EASY },
      { word: 'allergy', meaning: 'dị ứng', example: 'I have a food allergy.', exampleMeaning: 'Tôi bị dị ứng thức ăn.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'prescription', meaning: 'đơn thuốc', example: 'The doctor gave me a prescription.', exampleMeaning: 'Bác sĩ cho tôi đơn thuốc.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'appointment', meaning: 'cuộc hẹn (khám)', example: 'I have a doctor appointment.', exampleMeaning: 'Tôi có hẹn khám bác sĩ.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'healthy', meaning: 'khỏe mạnh', example: 'Eat vegetables to stay healthy.', exampleMeaning: 'Ăn rau để giữ sức khỏe.', difficulty: DIFFICULTY.EASY },
      { word: 'rest', meaning: 'nghỉ ngơi', example: 'You need to rest more.', exampleMeaning: 'Bạn cần nghỉ ngơi nhiều hơn.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Sốt" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Cold', 'Fever', 'Cough', 'Pain'], answer: 'Fever', explanation: 'Fever = sốt', explanationVi: 'Fever = sốt', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "I need to see a ___." (bác sĩ)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'doctor', explanation: 'Doctor = bác sĩ', explanationVi: 'Doctor = bác sĩ', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"Nhà thuốc" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Hospital', 'Pharmacy', 'Clinic', 'Laboratory'], answer: 'Pharmacy', explanation: 'Pharmacy = nhà thuốc', explanationVi: 'Pharmacy = nhà thuốc', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "prescription" = ?', type: QUIZ_TYPES.MATCHING, options: ['Đơn thuốc', 'Thuốc', 'Bệnh viện', 'Dị ứng'], answer: 'Đơn thuốc', explanation: 'Prescription = đơn thuốc', explanationVi: 'Prescription = đơn thuốc', difficulty: DIFFICULTY.MEDIUM },
      { question: '"Khỏe mạnh" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sick', 'Healthy', 'Happy', 'Strong'], answer: 'Healthy', explanation: 'Healthy = khỏe mạnh', explanationVi: 'Healthy = khỏe mạnh', difficulty: DIFFICULTY.EASY },
    ],
  },
];
