import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishShoppingLessons: LessonData[] = [
  {
    title: 'At the Store',
    titleVi: 'Ở cửa hàng',
    description: 'Learn shopping vocabulary and phrases',
    descriptionVi: 'Học từ vựng và cụm từ mua sắm',
    topic: TOPICS.SHOPPING,
    vocabulary: [
      { word: 'how much', meaning: 'bao nhiêu tiền', example: 'How much is this shirt?', exampleMeaning: 'Cái áo này bao nhiêu tiền?', difficulty: DIFFICULTY.EASY },
      { word: 'cheap', meaning: 'rẻ', example: 'This is very cheap.', exampleMeaning: 'Cái này rất rẻ.', difficulty: DIFFICULTY.EASY },
      { word: 'expensive', meaning: 'đắt', example: 'That bag is too expensive.', exampleMeaning: 'Cái túi đó quá đắt.', difficulty: DIFFICULTY.EASY },
      { word: 'discount', meaning: 'giảm giá', example: 'Is there a discount?', exampleMeaning: 'Có giảm giá không?', difficulty: DIFFICULTY.EASY },
      { word: 'size', meaning: 'kích cỡ', example: 'What size do you need?', exampleMeaning: 'Bạn cần cỡ nào?', difficulty: DIFFICULTY.EASY },
      { word: 'try on', meaning: 'thử (quần áo)', example: 'Can I try this on?', exampleMeaning: 'Tôi có thể thử cái này không?', difficulty: DIFFICULTY.EASY },
      { word: 'pay', meaning: 'trả tiền', example: 'I want to pay by card.', exampleMeaning: 'Tôi muốn trả bằng thẻ.', difficulty: DIFFICULTY.EASY },
      { word: 'cash', meaning: 'tiền mặt', example: 'Do you accept cash?', exampleMeaning: 'Bạn có nhận tiền mặt không?', difficulty: DIFFICULTY.EASY },
      { word: 'receipt', meaning: 'hóa đơn', example: 'Can I have the receipt?', exampleMeaning: 'Cho tôi xin hóa đơn?', difficulty: DIFFICULTY.EASY },
      { word: 'change', meaning: 'tiền thối', example: 'Here is your change.', exampleMeaning: 'Đây là tiền thối của bạn.', difficulty: DIFFICULTY.EASY },
      { word: 'sale', meaning: 'khuyến mãi', example: 'There is a big sale today!', exampleMeaning: 'Hôm nay có khuyến mãi lớn!', difficulty: DIFFICULTY.EASY },
      { word: 'customer', meaning: 'khách hàng', example: 'The customer is always right.', exampleMeaning: 'Khách hàng luôn đúng.', difficulty: DIFFICULTY.EASY },
      { word: 'shopping cart', meaning: 'giỏ hàng', example: 'Put it in the shopping cart.', exampleMeaning: 'Bỏ vào giỏ hàng đi.', difficulty: DIFFICULTY.EASY },
      { word: 'brand', meaning: 'thương hiệu', example: 'What brand do you like?', exampleMeaning: 'Bạn thích thương hiệu nào?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'refund', meaning: 'hoàn tiền', example: 'I want a refund, please.', exampleMeaning: 'Tôi muốn hoàn tiền.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Bao nhiêu tiền?" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['How many', 'How much', 'How old', 'How far'], answer: 'How much', explanation: 'How much = bao nhiêu tiền', explanationVi: 'How much = bao nhiêu tiền', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "Is there a ___?" (giảm giá)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'discount', explanation: 'Discount = giảm giá', explanationVi: 'Discount = giảm giá', difficulty: DIFFICULTY.EASY },
      { question: '"Tiền mặt" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Card', 'Cash', 'Change', 'Check'], answer: 'Cash', explanation: 'Cash = tiền mặt', explanationVi: 'Cash = tiền mặt', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "receipt" = ?', type: QUIZ_TYPES.MATCHING, options: ['Hóa đơn', 'Tiền thối', 'Giảm giá', 'Khuyến mãi'], answer: 'Hóa đơn', explanation: 'Receipt = hóa đơn', explanationVi: 'Receipt = hóa đơn', difficulty: DIFFICULTY.EASY },
      { question: '"Hoàn tiền" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Refund', 'Receipt', 'Return', 'Reward'], answer: 'Refund', explanation: 'Refund = hoàn tiền', explanationVi: 'Refund = hoàn tiền', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
  {
    title: 'Clothing & Fashion',
    titleVi: 'Quần áo & Thời trang',
    description: 'Learn vocabulary about clothes and fashion',
    descriptionVi: 'Học từ vựng về quần áo và thời trang',
    topic: TOPICS.SHOPPING,
    vocabulary: [
      { word: 'shirt', meaning: 'áo sơ mi', example: 'I need a new shirt.', exampleMeaning: 'Tôi cần một cái áo sơ mi mới.', difficulty: DIFFICULTY.EASY },
      { word: 'pants', meaning: 'quần dài', example: 'These pants are too long.', exampleMeaning: 'Cái quần này dài quá.', difficulty: DIFFICULTY.EASY },
      { word: 'dress', meaning: 'váy đầm', example: 'She wears a beautiful dress.', exampleMeaning: 'Cô ấy mặc một chiếc váy đẹp.', difficulty: DIFFICULTY.EASY },
      { word: 'shoes', meaning: 'giày', example: 'I bought new shoes.', exampleMeaning: 'Tôi mua giày mới.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'jacket', meaning: 'áo khoác', example: 'Wear a jacket, it is cold.', exampleMeaning: 'Mặc áo khoác đi, trời lạnh.', difficulty: DIFFICULTY.EASY },
      { word: 'hat', meaning: 'mũ/nón', example: 'I wear a hat in the sun.', exampleMeaning: 'Tôi đội mũ khi trời nắng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'socks', meaning: 'tất/vớ', example: 'I need clean socks.', exampleMeaning: 'Tôi cần tất sạch.', difficulty: DIFFICULTY.EASY },
      { word: 'skirt', meaning: 'chân váy', example: 'She likes wearing skirts.', exampleMeaning: 'Cô ấy thích mặc chân váy.', difficulty: DIFFICULTY.EASY },
      { word: 'T-shirt', meaning: 'áo phông', example: 'I wear a T-shirt every day.', exampleMeaning: 'Tôi mặc áo phông mỗi ngày.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'jeans', meaning: 'quần jeans', example: 'Jeans are very popular.', exampleMeaning: 'Quần jeans rất phổ biến.', difficulty: DIFFICULTY.EASY },
      { word: 'sweater', meaning: 'áo len', example: 'I wear a sweater in winter.', exampleMeaning: 'Tôi mặc áo len vào mùa đông.', difficulty: DIFFICULTY.EASY },
      { word: 'underwear', meaning: 'đồ lót', example: 'I need to buy new underwear.', exampleMeaning: 'Tôi cần mua đồ lót mới.', difficulty: DIFFICULTY.EASY },
      { word: 'belt', meaning: 'thắt lưng', example: 'This belt is too tight.', exampleMeaning: 'Cái thắt lưng này chật quá.', difficulty: DIFFICULTY.EASY },
      { word: 'scarf', meaning: 'khăn quàng', example: 'She wears a red scarf.', exampleMeaning: 'Cô ấy đeo khăn quàng đỏ.', difficulty: DIFFICULTY.EASY },
      { word: 'uniform', meaning: 'đồng phục', example: 'Students wear uniforms.', exampleMeaning: 'Học sinh mặc đồng phục.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Giày" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Socks', 'Shoes', 'Shirt', 'Shorts'], answer: 'Shoes', explanation: 'Shoes = giày', explanationVi: 'Shoes = giày', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Điền: "Wear a ___, it is cold." (áo khoác)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'jacket', explanation: 'Jacket = áo khoác', explanationVi: 'Jacket = áo khoác', difficulty: DIFFICULTY.EASY },
      { question: '"Đồng phục" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Uniform', 'Underwear', 'Umbrella', 'Unit'], answer: 'Uniform', explanation: 'Uniform = đồng phục', explanationVi: 'Uniform = đồng phục', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "sweater" = ?', type: QUIZ_TYPES.MATCHING, options: ['Áo len', 'Áo khoác', 'Áo sơ mi', 'Áo phông'], answer: 'Áo len', explanation: 'Sweater = áo len', explanationVi: 'Sweater = áo len', difficulty: DIFFICULTY.EASY },
      { question: '"Quần jeans" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Pants', 'Jeans', 'Shorts', 'Skirt'], answer: 'Jeans', explanation: 'Jeans = quần jeans', explanationVi: 'Jeans = quần jeans', difficulty: DIFFICULTY.EASY },
    ],
  },
];
