import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishTravelLessons: LessonData[] = [
  {
    title: 'At the Airport',
    titleVi: 'Tại sân bay',
    description: 'Essential vocabulary for air travel',
    descriptionVi: 'Từ vựng cần thiết khi đi máy bay',
    topic: TOPICS.TRAVEL,
    vocabulary: [
      { word: 'passport', meaning: 'hộ chiếu', example: 'Please show your passport.', exampleMeaning: 'Vui lòng xuất trình hộ chiếu.', difficulty: DIFFICULTY.EASY },
      { word: 'boarding pass', meaning: 'thẻ lên máy bay', example: 'Here is my boarding pass.', exampleMeaning: 'Đây là thẻ lên máy bay của tôi.', difficulty: DIFFICULTY.EASY },
      { word: 'luggage', meaning: 'hành lý', example: 'How many pieces of luggage do you have?', exampleMeaning: 'Bạn có bao nhiêu kiện hành lý?', difficulty: DIFFICULTY.EASY },
      { word: 'departure', meaning: 'khởi hành', example: 'The departure time is 10 AM.', exampleMeaning: 'Giờ khởi hành là 10 giờ sáng.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'arrival', meaning: 'đến nơi', example: 'What is the arrival time?', exampleMeaning: 'Giờ đến là mấy giờ?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'gate', meaning: 'cổng (lên máy bay)', example: 'Your flight departs from gate 5.', exampleMeaning: 'Chuyến bay của bạn khởi hành từ cổng 5.', difficulty: DIFFICULTY.EASY },
      { word: 'flight', meaning: 'chuyến bay', example: 'My flight is delayed.', exampleMeaning: 'Chuyến bay của tôi bị trễ.', difficulty: DIFFICULTY.EASY },
      { word: 'check-in', meaning: 'làm thủ tục', example: 'Where is the check-in counter?', exampleMeaning: 'Quầy làm thủ tục ở đâu?', difficulty: DIFFICULTY.EASY },
      { word: 'customs', meaning: 'hải quan', example: 'You need to go through customs.', exampleMeaning: 'Bạn cần qua hải quan.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'terminal', meaning: 'nhà ga', example: 'International flights are in Terminal 2.', exampleMeaning: 'Chuyến bay quốc tế ở Nhà ga 2.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'delay', meaning: 'trễ/hoãn', example: 'The flight has a 2-hour delay.', exampleMeaning: 'Chuyến bay trễ 2 tiếng.', difficulty: DIFFICULTY.EASY },
      { word: 'seat', meaning: 'ghế ngồi', example: 'I prefer a window seat.', exampleMeaning: 'Tôi thích ghế cạnh cửa sổ.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'carry-on', meaning: 'hành lý xách tay', example: 'You can bring one carry-on bag.', exampleMeaning: 'Bạn được mang một túi xách tay.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'immigration', meaning: 'xuất nhập cảnh', example: 'The immigration line is long.', exampleMeaning: 'Hàng chờ xuất nhập cảnh dài quá.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'duty-free', meaning: 'miễn thuế', example: 'Let\'s shop at the duty-free store.', exampleMeaning: 'Mua sắm ở cửa hàng miễn thuế nhé.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Hộ chiếu" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Visa', 'Passport', 'Ticket', 'ID card'], answer: 'Passport', explanation: 'Hộ chiếu = Passport', explanationVi: 'Hộ chiếu = Passport (giấy tờ đi nước ngoài)', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "My _____ is delayed." (chuyến bay)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'flight', explanation: 'Flight = chuyến bay', explanationVi: 'Flight = chuyến bay', difficulty: DIFFICULTY.EASY },
      { question: 'Where do you check in at the airport?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Gate', 'Counter', 'Terminal', 'Customs'], answer: 'Counter', explanation: 'You check in at the check-in counter', explanationVi: 'Bạn làm thủ tục tại quầy check-in (counter)', difficulty: DIFFICULTY.EASY },
      { question: 'Match: "hành lý" = ?', type: QUIZ_TYPES.MATCHING, options: ['Passport', 'Luggage', 'Ticket', 'Gate'], answer: 'Luggage', explanation: 'Hành lý = Luggage/Baggage', explanationVi: 'Hành lý = Luggage/Baggage', difficulty: DIFFICULTY.EASY },
      { question: '"Departure" means...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Đến nơi', 'Khởi hành', 'Trễ', 'Hủy'], answer: 'Khởi hành', explanation: 'Departure = khởi hành (opposite: arrival = đến nơi)', explanationVi: 'Departure = khởi hành (trái nghĩa: arrival = đến nơi)', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
  {
    title: 'Asking for Directions',
    titleVi: 'Hỏi đường',
    description: 'How to ask and give directions in English',
    descriptionVi: 'Cách hỏi và chỉ đường bằng tiếng Anh',
    topic: TOPICS.TRAVEL,
    vocabulary: [
      { word: 'turn left', meaning: 'rẽ trái', example: 'Turn left at the traffic light.', exampleMeaning: 'Rẽ trái ở đèn giao thông.', difficulty: DIFFICULTY.EASY },
      { word: 'turn right', meaning: 'rẽ phải', example: 'Turn right after the bridge.', exampleMeaning: 'Rẽ phải sau cầu.', difficulty: DIFFICULTY.EASY },
      { word: 'go straight', meaning: 'đi thẳng', example: 'Go straight for 200 meters.', exampleMeaning: 'Đi thẳng 200 mét.', difficulty: DIFFICULTY.EASY },
      { word: 'next to', meaning: 'bên cạnh', example: 'The bank is next to the hospital.', exampleMeaning: 'Ngân hàng ở bên cạnh bệnh viện.', difficulty: DIFFICULTY.EASY },
      { word: 'opposite', meaning: 'đối diện', example: 'The park is opposite the school.', exampleMeaning: 'Công viên đối diện trường học.', difficulty: DIFFICULTY.EASY },
      { word: 'between', meaning: 'ở giữa', example: 'The shop is between the bank and the cafe.', exampleMeaning: 'Cửa hàng ở giữa ngân hàng và quán cà phê.', difficulty: DIFFICULTY.EASY },
      { word: 'corner', meaning: 'góc (đường)', example: 'There is a pharmacy on the corner.', exampleMeaning: 'Có nhà thuốc ở góc đường.', difficulty: DIFFICULTY.EASY },
      { word: 'crossroad', meaning: 'ngã tư', example: 'Turn right at the crossroad.', exampleMeaning: 'Rẽ phải ở ngã tư.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'block', meaning: 'dãy nhà', example: 'Walk two blocks and turn left.', exampleMeaning: 'Đi hai dãy nhà rồi rẽ trái.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'far', meaning: 'xa', example: 'Is it far from here?', exampleMeaning: 'Có xa đây không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'near', meaning: 'gần', example: 'The station is near here.', exampleMeaning: 'Ga tàu gần đây.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'map', meaning: 'bản đồ', example: 'Can you show me on the map?', exampleMeaning: 'Bạn chỉ trên bản đồ được không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'lost', meaning: 'bị lạc', example: 'I am lost. Can you help me?', exampleMeaning: 'Tôi bị lạc. Bạn giúp tôi được không?', difficulty: DIFFICULTY.EASY },
      { word: 'traffic light', meaning: 'đèn giao thông', example: 'Stop at the traffic light.', exampleMeaning: 'Dừng ở đèn giao thông.', difficulty: DIFFICULTY.EASY },
      { word: 'roundabout', meaning: 'vòng xoay', example: 'Take the second exit at the roundabout.', exampleMeaning: 'Đi lối ra thứ hai ở vòng xoay.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: 'How do you say "rẽ trái"?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Turn right', 'Turn left', 'Go straight', 'Go back'], answer: 'Turn left', explanation: 'Rẽ trái = Turn left', explanationVi: 'Rẽ trái = Turn left', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "The bank is _____ the hospital." (bên cạnh)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'next to', explanation: 'Next to = bên cạnh', explanationVi: 'Next to = bên cạnh', difficulty: DIFFICULTY.EASY },
      { question: '"Đối diện" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Next to', 'Between', 'Opposite', 'Behind'], answer: 'Opposite', explanation: 'Đối diện = Opposite', explanationVi: 'Đối diện = Opposite', difficulty: DIFFICULTY.EASY },
      { question: 'What do you say when you don\'t know where you are?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['I am tired', 'I am lost', 'I am late', 'I am hungry'], answer: 'I am lost', explanation: '"I am lost" = Tôi bị lạc', explanationVi: '"I am lost" = Tôi bị lạc', difficulty: DIFFICULTY.EASY },
      { question: 'Arrange: "from / it / Is / far / here / ?"', type: QUIZ_TYPES.ARRANGE, options: ['from', 'it', 'Is', 'far', 'here', '?'], answer: 'Is it far from here ?', explanation: '"Is it far from here?" - asking about distance', explanationVi: '"Is it far from here?" - hỏi về khoảng cách', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
  {
    title: 'Hotel & Accommodation',
    titleVi: 'Khách sạn & Chỗ ở',
    description: 'Vocabulary for booking and staying at hotels',
    descriptionVi: 'Từ vựng khi đặt phòng và ở khách sạn',
    topic: TOPICS.TRAVEL,
    vocabulary: [
      { word: 'room', meaning: 'phòng', example: 'I\'d like to book a room.', exampleMeaning: 'Tôi muốn đặt phòng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'single room', meaning: 'phòng đơn', example: 'A single room for one night, please.', exampleMeaning: 'Cho tôi phòng đơn một đêm.', difficulty: DIFFICULTY.EASY },
      { word: 'double room', meaning: 'phòng đôi', example: 'We need a double room.', exampleMeaning: 'Chúng tôi cần phòng đôi.', difficulty: DIFFICULTY.EASY },
      { word: 'check in', meaning: 'nhận phòng', example: 'What time is check-in?', exampleMeaning: 'Mấy giờ nhận phòng?', difficulty: DIFFICULTY.EASY },
      { word: 'check out', meaning: 'trả phòng', example: 'Check-out is at 12 noon.', exampleMeaning: 'Trả phòng lúc 12 giờ trưa.', difficulty: DIFFICULTY.EASY },
      { word: 'key', meaning: 'chìa khóa', example: 'Here is your room key.', exampleMeaning: 'Đây là chìa khóa phòng của bạn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'reception', meaning: 'lễ tân', example: 'Please ask at reception.', exampleMeaning: 'Vui lòng hỏi ở lễ tân.', difficulty: DIFFICULTY.EASY },
      { word: 'breakfast included', meaning: 'bao gồm bữa sáng', example: 'Is breakfast included?', exampleMeaning: 'Có bao gồm bữa sáng không?', difficulty: DIFFICULTY.EASY },
      { word: 'wifi', meaning: 'wifi', example: 'What is the wifi password?', exampleMeaning: 'Mật khẩu wifi là gì?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'air conditioning', meaning: 'điều hòa', example: 'The air conditioning is not working.', exampleMeaning: 'Điều hòa không hoạt động.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'towel', meaning: 'khăn tắm', example: 'Can I have extra towels?', exampleMeaning: 'Cho tôi thêm khăn tắm được không?', difficulty: DIFFICULTY.EASY },
      { word: 'elevator', meaning: 'thang máy', example: 'Take the elevator to the 5th floor.', exampleMeaning: 'Đi thang máy lên tầng 5.', difficulty: DIFFICULTY.EASY },
      { word: 'floor', meaning: 'tầng', example: 'Your room is on the 3rd floor.', exampleMeaning: 'Phòng bạn ở tầng 3.', difficulty: DIFFICULTY.EASY },
      { word: 'booking', meaning: 'đặt phòng', example: 'I have a booking under Nguyen.', exampleMeaning: 'Tôi có đặt phòng dưới tên Nguyễn.', difficulty: DIFFICULTY.EASY },
      { word: 'available', meaning: 'còn trống', example: 'Are there any rooms available?', exampleMeaning: 'Còn phòng trống không?', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: 'How do you ask to book a room?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['I want to eat', 'I\'d like to book a room', 'I need a taxi', 'Where is the hotel?'], answer: 'I\'d like to book a room', explanation: '"I\'d like to book a room" is polite way to reserve', explanationVi: '"I\'d like to book a room" là cách lịch sự để đặt phòng', difficulty: DIFFICULTY.EASY },
      { question: '"Trả phòng" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Check in', 'Check out', 'Check up', 'Check off'], answer: 'Check out', explanation: 'Check out = trả phòng (opposite: check in = nhận phòng)', explanationVi: 'Check out = trả phòng (trái nghĩa: check in = nhận phòng)', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "What is the _____ password?" (wifi)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'wifi', explanation: 'Asking for wifi password at a hotel', explanationVi: 'Hỏi mật khẩu wifi ở khách sạn', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Match: "thang máy" = ?', type: QUIZ_TYPES.MATCHING, options: ['Stairs', 'Elevator', 'Escalator', 'Ladder'], answer: 'Elevator', explanation: 'Thang máy = Elevator (US) / Lift (UK)', explanationVi: 'Thang máy = Elevator (Mỹ) / Lift (Anh)', difficulty: DIFFICULTY.EASY },
      { question: 'Which question asks about room availability?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['How much is it?', 'Are there any rooms available?', 'Where is the hotel?', 'What time is breakfast?'], answer: 'Are there any rooms available?', explanation: '"Are there any rooms available?" = Còn phòng trống không?', explanationVi: '"Are there any rooms available?" = Còn phòng trống không?', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
