import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishGreetingsLessons: LessonData[] = [
  {
    title: 'Hello & Goodbye',
    titleVi: 'Chào hỏi & Tạm biệt',
    description: 'Basic greetings and farewells in English',
    descriptionVi: 'Các câu chào hỏi và tạm biệt cơ bản',
    topic: TOPICS.GREETINGS,
    vocabulary: [
      { word: 'hello', meaning: 'xin chào', example: 'Hello! How are you?', exampleMeaning: 'Xin chào! Bạn khỏe không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'hi', meaning: 'chào (thân mật)', example: 'Hi there! Nice to see you.', exampleMeaning: 'Chào bạn! Vui được gặp bạn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'good morning', meaning: 'chào buổi sáng', example: 'Good morning, teacher!', exampleMeaning: 'Chào buổi sáng, thầy/cô!', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'good afternoon', meaning: 'chào buổi chiều', example: 'Good afternoon, everyone.', exampleMeaning: 'Chào buổi chiều mọi người.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'good evening', meaning: 'chào buổi tối', example: 'Good evening, sir.', exampleMeaning: 'Chào buổi tối, thưa ông.', difficulty: DIFFICULTY.EASY },
      { word: 'goodbye', meaning: 'tạm biệt', example: 'Goodbye! See you tomorrow.', exampleMeaning: 'Tạm biệt! Hẹn gặp lại ngày mai.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'see you later', meaning: 'hẹn gặp lại', example: 'I have to go. See you later!', exampleMeaning: 'Tôi phải đi. Hẹn gặp lại!', difficulty: DIFFICULTY.EASY },
      { word: 'nice to meet you', meaning: 'rất vui được gặp bạn', example: 'Nice to meet you, Lan.', exampleMeaning: 'Rất vui được gặp bạn, Lan.', difficulty: DIFFICULTY.EASY },
      { word: 'how are you', meaning: 'bạn khỏe không', example: 'How are you today?', exampleMeaning: 'Hôm nay bạn khỏe không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'I am fine', meaning: 'tôi khỏe', example: 'I am fine, thank you.', exampleMeaning: 'Tôi khỏe, cảm ơn bạn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'thank you', meaning: 'cảm ơn', example: 'Thank you very much!', exampleMeaning: 'Cảm ơn rất nhiều!', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'you are welcome', meaning: 'không có gì', example: 'You are welcome!', exampleMeaning: 'Không có gì!', difficulty: DIFFICULTY.EASY },
      { word: 'excuse me', meaning: 'xin lỗi (để hỏi)', example: 'Excuse me, where is the bank?', exampleMeaning: 'Xin lỗi, ngân hàng ở đâu?', difficulty: DIFFICULTY.EASY },
      { word: 'sorry', meaning: 'xin lỗi', example: 'Sorry, I am late.', exampleMeaning: 'Xin lỗi, tôi đến muộn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'please', meaning: 'làm ơn', example: 'Please sit down.', exampleMeaning: 'Làm ơn ngồi xuống.', difficulty: DIFFICULTY.VERY_EASY },
    ],
    quizzes: [
      { question: '"Xin chào" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Goodbye', 'Hello', 'Sorry', 'Please'], answer: 'Hello', explanation: 'Hello = Xin chào', explanationVi: 'Hello = Xin chào', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Điền vào: "Good ___, teacher!" (buổi sáng)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'morning', explanation: 'Good morning = Chào buổi sáng', explanationVi: 'Good morning = Chào buổi sáng', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"Cảm ơn" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sorry', 'Please', 'Thank you', 'Excuse me'], answer: 'Thank you', explanation: 'Thank you = Cảm ơn', explanationVi: 'Thank you = Cảm ơn', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Nối: "See you later" = ?', type: QUIZ_TYPES.MATCHING, options: ['Hẹn gặp lại', 'Tạm biệt', 'Xin chào', 'Xin lỗi'], answer: 'Hẹn gặp lại', explanation: 'See you later = Hẹn gặp lại', explanationVi: 'See you later = Hẹn gặp lại', difficulty: DIFFICULTY.EASY },
      { question: 'Sắp xếp: "you / meet / Nice / to"', type: QUIZ_TYPES.ARRANGE, options: ['you', 'meet', 'Nice', 'to'], answer: 'Nice to meet you', explanation: '"Nice to meet you" = Rất vui được gặp bạn', explanationVi: '"Nice to meet you" = Rất vui được gặp bạn', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Self Introduction',
    titleVi: 'Giới thiệu bản thân',
    description: 'Introduce yourself in English',
    descriptionVi: 'Học cách giới thiệu bản thân bằng tiếng Anh',
    topic: TOPICS.GREETINGS,
    vocabulary: [
      { word: 'my name is', meaning: 'tên tôi là', example: 'My name is Minh.', exampleMeaning: 'Tên tôi là Minh.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'I am from', meaning: 'tôi đến từ', example: 'I am from Vietnam.', exampleMeaning: 'Tôi đến từ Việt Nam.', difficulty: DIFFICULTY.EASY },
      { word: 'I live in', meaning: 'tôi sống ở', example: 'I live in Ho Chi Minh City.', exampleMeaning: 'Tôi sống ở TP. Hồ Chí Minh.', difficulty: DIFFICULTY.EASY },
      { word: 'I am ... years old', meaning: 'tôi ... tuổi', example: 'I am 22 years old.', exampleMeaning: 'Tôi 22 tuổi.', difficulty: DIFFICULTY.EASY },
      { word: 'I am a student', meaning: 'tôi là sinh viên', example: 'I am a student at FPT University.', exampleMeaning: 'Tôi là sinh viên trường FPT.', difficulty: DIFFICULTY.EASY },
      { word: 'I work as', meaning: 'tôi làm nghề', example: 'I work as a teacher.', exampleMeaning: 'Tôi làm nghề giáo viên.', difficulty: DIFFICULTY.EASY },
      { word: 'I like', meaning: 'tôi thích', example: 'I like reading books.', exampleMeaning: 'Tôi thích đọc sách.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'I can speak', meaning: 'tôi có thể nói', example: 'I can speak Vietnamese and English.', exampleMeaning: 'Tôi có thể nói tiếng Việt và tiếng Anh.', difficulty: DIFFICULTY.EASY },
      { word: 'I want to learn', meaning: 'tôi muốn học', example: 'I want to learn Japanese.', exampleMeaning: 'Tôi muốn học tiếng Nhật.', difficulty: DIFFICULTY.EASY },
      { word: 'my hobby is', meaning: 'sở thích của tôi là', example: 'My hobby is playing guitar.', exampleMeaning: 'Sở thích của tôi là chơi guitar.', difficulty: DIFFICULTY.EASY },
      { word: 'I have', meaning: 'tôi có', example: 'I have two brothers.', exampleMeaning: 'Tôi có hai anh trai.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'I study', meaning: 'tôi học', example: 'I study English every day.', exampleMeaning: 'Tôi học tiếng Anh mỗi ngày.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'I enjoy', meaning: 'tôi thích/thưởng thức', example: 'I enjoy cooking Vietnamese food.', exampleMeaning: 'Tôi thích nấu đồ ăn Việt Nam.', difficulty: DIFFICULTY.EASY },
      { word: 'I was born in', meaning: 'tôi sinh ra ở', example: 'I was born in Hanoi.', exampleMeaning: 'Tôi sinh ra ở Hà Nội.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'I dream of', meaning: 'tôi mơ ước', example: 'I dream of traveling the world.', exampleMeaning: 'Tôi mơ ước đi du lịch vòng quanh thế giới.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Tên tôi là..." tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['I am from...', 'My name is...', 'I live in...', 'I like...'], answer: 'My name is...', explanation: 'My name is... = Tên tôi là...', explanationVi: 'My name is... = Tên tôi là...', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Điền: "I am ___ Vietnam." (đến từ)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'from', explanation: 'I am from = Tôi đến từ', explanationVi: 'I am from = Tôi đến từ', difficulty: DIFFICULTY.EASY },
      { question: '"Tôi muốn học" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['I can speak', 'I want to learn', 'I like', 'I study'], answer: 'I want to learn', explanation: 'I want to learn = Tôi muốn học', explanationVi: 'I want to learn = Tôi muốn học', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "I work as" = ?', type: QUIZ_TYPES.MATCHING, options: ['Tôi làm nghề', 'Tôi học', 'Tôi sống ở', 'Tôi thích'], answer: 'Tôi làm nghề', explanation: 'I work as = Tôi làm nghề', explanationVi: 'I work as = Tôi làm nghề', difficulty: DIFFICULTY.EASY },
      { question: 'Sắp xếp: "English / I / every day / study"', type: QUIZ_TYPES.ARRANGE, options: ['English', 'I', 'every day', 'study'], answer: 'I study English every day', explanation: '"I study English every day" = Tôi học tiếng Anh mỗi ngày', explanationVi: '"I study English every day" = Tôi học tiếng Anh mỗi ngày', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Polite Expressions',
    titleVi: 'Cách nói lịch sự',
    description: 'Learn polite phrases for everyday situations',
    descriptionVi: 'Học các cụm từ lịch sự cho tình huống hàng ngày',
    topic: TOPICS.GREETINGS,
    vocabulary: [
      { word: 'could you please', meaning: 'bạn có thể... được không', example: 'Could you please help me?', exampleMeaning: 'Bạn có thể giúp tôi được không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'would you like', meaning: 'bạn có muốn', example: 'Would you like some coffee?', exampleMeaning: 'Bạn có muốn uống cà phê không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'may I', meaning: 'tôi có thể... không', example: 'May I sit here?', exampleMeaning: 'Tôi có thể ngồi đây không?', difficulty: DIFFICULTY.EASY },
      { word: 'I would like', meaning: 'tôi muốn (lịch sự)', example: 'I would like a glass of water.', exampleMeaning: 'Tôi muốn một ly nước.', difficulty: DIFFICULTY.EASY },
      { word: 'no problem', meaning: 'không sao/không vấn đề gì', example: 'No problem! I can help you.', exampleMeaning: 'Không sao! Tôi có thể giúp bạn.', difficulty: DIFFICULTY.EASY },
      { word: 'I appreciate it', meaning: 'tôi rất trân trọng', example: 'Thank you, I appreciate it.', exampleMeaning: 'Cảm ơn, tôi rất trân trọng.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'pardon me', meaning: 'xin lỗi (trang trọng)', example: 'Pardon me, could you repeat that?', exampleMeaning: 'Xin lỗi, bạn có thể nhắc lại không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'I am sorry to bother you', meaning: 'xin lỗi đã làm phiền', example: 'I am sorry to bother you, but...', exampleMeaning: 'Xin lỗi đã làm phiền, nhưng...', difficulty: DIFFICULTY.MEDIUM },
      { word: 'have a nice day', meaning: 'chúc một ngày tốt lành', example: 'Goodbye! Have a nice day!', exampleMeaning: 'Tạm biệt! Chúc một ngày tốt lành!', difficulty: DIFFICULTY.EASY },
      { word: 'take care', meaning: 'bảo trọng', example: 'Take care! See you next week.', exampleMeaning: 'Bảo trọng! Hẹn gặp tuần sau.', difficulty: DIFFICULTY.EASY },
      { word: 'congratulations', meaning: 'chúc mừng', example: 'Congratulations on your new job!', exampleMeaning: 'Chúc mừng công việc mới!', difficulty: DIFFICULTY.EASY },
      { word: 'I am glad', meaning: 'tôi vui/mừng', example: 'I am glad you came.', exampleMeaning: 'Tôi mừng vì bạn đến.', difficulty: DIFFICULTY.EASY },
      { word: 'it does not matter', meaning: 'không sao đâu', example: 'It does not matter. Do not worry.', exampleMeaning: 'Không sao đâu. Đừng lo.', difficulty: DIFFICULTY.EASY },
      { word: 'of course', meaning: 'tất nhiên', example: 'Of course! I will help you.', exampleMeaning: 'Tất nhiên! Tôi sẽ giúp bạn.', difficulty: DIFFICULTY.EASY },
      { word: 'I beg your pardon', meaning: 'xin lỗi (rất trang trọng)', example: 'I beg your pardon, I did not hear you.', exampleMeaning: 'Xin lỗi, tôi không nghe rõ.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Bạn có muốn..." tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Could you please', 'Would you like', 'May I', 'I would like'], answer: 'Would you like', explanation: 'Would you like = Bạn có muốn', explanationVi: 'Would you like = Bạn có muốn', difficulty: DIFFICULTY.MEDIUM },
      { question: 'Điền: "___ I sit here?" (tôi có thể)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'May', explanation: 'May I = Tôi có thể... không', explanationVi: 'May I = Tôi có thể... không', difficulty: DIFFICULTY.EASY },
      { question: '"Chúc mừng" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Take care', 'Congratulations', 'No problem', 'Of course'], answer: 'Congratulations', explanation: 'Congratulations = Chúc mừng', explanationVi: 'Congratulations = Chúc mừng', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "Have a nice day" = ?', type: QUIZ_TYPES.MATCHING, options: ['Chúc một ngày tốt lành', 'Bảo trọng', 'Không sao', 'Tất nhiên'], answer: 'Chúc một ngày tốt lành', explanation: 'Have a nice day = Chúc một ngày tốt lành', explanationVi: 'Have a nice day = Chúc một ngày tốt lành', difficulty: DIFFICULTY.EASY },
      { question: '"Tất nhiên" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['No problem', 'Of course', 'I am glad', 'Take care'], answer: 'Of course', explanation: 'Of course = Tất nhiên', explanationVi: 'Of course = Tất nhiên', difficulty: DIFFICULTY.EASY },
    ],
  },
];
