import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishNumbersLessons: LessonData[] = [
  {
    title: 'Numbers 1-100',
    titleVi: 'Số đếm 1-100',
    description: 'Learn numbers from 1 to 100 in English',
    descriptionVi: 'Học số đếm từ 1 đến 100 bằng tiếng Anh',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: 'one', meaning: 'một (1)', example: 'I have one cat.', exampleMeaning: 'Tôi có một con mèo.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'two', meaning: 'hai (2)', example: 'There are two books.', exampleMeaning: 'Có hai quyển sách.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'three', meaning: 'ba (3)', example: 'I need three minutes.', exampleMeaning: 'Tôi cần ba phút.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'ten', meaning: 'mười (10)', example: 'I have ten fingers.', exampleMeaning: 'Tôi có mười ngón tay.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'twenty', meaning: 'hai mươi (20)', example: 'She is twenty years old.', exampleMeaning: 'Cô ấy hai mươi tuổi.', difficulty: DIFFICULTY.EASY },
      { word: 'fifty', meaning: 'năm mươi (50)', example: 'It costs fifty dollars.', exampleMeaning: 'Nó giá năm mươi đô la.', difficulty: DIFFICULTY.EASY },
      { word: 'hundred', meaning: 'trăm (100)', example: 'There are one hundred students.', exampleMeaning: 'Có một trăm sinh viên.', difficulty: DIFFICULTY.EASY },
      { word: 'first', meaning: 'thứ nhất', example: 'This is my first time here.', exampleMeaning: 'Đây là lần đầu tiên tôi ở đây.', difficulty: DIFFICULTY.EASY },
      { word: 'second', meaning: 'thứ hai', example: 'Wait a second, please.', exampleMeaning: 'Đợi một chút nhé.', difficulty: DIFFICULTY.EASY },
      { word: 'third', meaning: 'thứ ba', example: 'I live on the third floor.', exampleMeaning: 'Tôi sống ở tầng ba.', difficulty: DIFFICULTY.EASY },
      { word: 'half', meaning: 'một nửa', example: 'I ate half of the cake.', exampleMeaning: 'Tôi ăn một nửa cái bánh.', difficulty: DIFFICULTY.EASY },
      { word: 'zero', meaning: 'không (0)', example: 'The temperature is zero degrees.', exampleMeaning: 'Nhiệt độ là 0 độ.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'thousand', meaning: 'nghìn (1000)', example: 'It costs two thousand dong.', exampleMeaning: 'Nó giá hai nghìn đồng.', difficulty: DIFFICULTY.EASY },
      { word: 'million', meaning: 'triệu', example: 'Vietnam has 100 million people.', exampleMeaning: 'Việt Nam có 100 triệu người.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'double', meaning: 'gấp đôi', example: 'Double the price is too expensive.', exampleMeaning: 'Gấp đôi giá thì quá đắt.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Hai mươi" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Twelve', 'Twenty', 'Two', 'Ten'], answer: 'Twenty', explanation: 'Twenty = 20 = hai mươi', explanationVi: 'Twenty = 20 = hai mươi', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "I have ___ fingers." (mười)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'ten', explanation: 'Ten = 10 = mười', explanationVi: 'Ten = 10 = mười', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"Thứ nhất" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['One', 'First', 'Once', 'Single'], answer: 'First', explanation: 'First = thứ nhất', explanationVi: 'First = thứ nhất', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "hundred" = ?', type: QUIZ_TYPES.MATCHING, options: ['Trăm', 'Nghìn', 'Triệu', 'Mười'], answer: 'Trăm', explanation: 'Hundred = trăm (100)', explanationVi: 'Hundred = trăm (100)', difficulty: DIFFICULTY.EASY },
      { question: '"Một nửa" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Double', 'Half', 'Quarter', 'Third'], answer: 'Half', explanation: 'Half = một nửa', explanationVi: 'Half = một nửa', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Telling Time',
    titleVi: 'Nói giờ',
    description: 'Learn to tell time in English',
    descriptionVi: 'Học cách nói giờ bằng tiếng Anh',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: 'what time is it', meaning: 'mấy giờ rồi', example: 'What time is it now?', exampleMeaning: 'Bây giờ mấy giờ rồi?', difficulty: DIFFICULTY.EASY },
      { word: 'o\'clock', meaning: 'giờ đúng', example: 'It is 3 o\'clock.', exampleMeaning: 'Bây giờ là 3 giờ đúng.', difficulty: DIFFICULTY.EASY },
      { word: 'half past', meaning: 'rưỡi (30 phút)', example: 'It is half past seven.', exampleMeaning: 'Bây giờ là 7 giờ rưỡi.', difficulty: DIFFICULTY.EASY },
      { word: 'quarter past', meaning: '15 phút (qua)', example: 'It is quarter past nine.', exampleMeaning: 'Bây giờ là 9 giờ 15.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'quarter to', meaning: 'kém 15 phút', example: 'It is quarter to five.', exampleMeaning: 'Bây giờ là 5 giờ kém 15.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'morning', meaning: 'buổi sáng', example: 'I wake up in the morning.', exampleMeaning: 'Tôi thức dậy vào buổi sáng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'afternoon', meaning: 'buổi chiều', example: 'I study in the afternoon.', exampleMeaning: 'Tôi học vào buổi chiều.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'evening', meaning: 'buổi tối', example: 'I watch TV in the evening.', exampleMeaning: 'Tôi xem TV vào buổi tối.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'midnight', meaning: 'nửa đêm', example: 'I go to bed before midnight.', exampleMeaning: 'Tôi đi ngủ trước nửa đêm.', difficulty: DIFFICULTY.EASY },
      { word: 'noon', meaning: 'buổi trưa', example: 'We have lunch at noon.', exampleMeaning: 'Chúng tôi ăn trưa lúc 12 giờ.', difficulty: DIFFICULTY.EASY },
      { word: 'early', meaning: 'sớm', example: 'I wake up early every day.', exampleMeaning: 'Tôi dậy sớm mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: 'late', meaning: 'muộn/trễ', example: 'Sorry, I am late!', exampleMeaning: 'Xin lỗi, tôi đến muộn!', difficulty: DIFFICULTY.EASY },
      { word: 'on time', meaning: 'đúng giờ', example: 'Please arrive on time.', exampleMeaning: 'Hãy đến đúng giờ.', difficulty: DIFFICULTY.EASY },
      { word: 'minute', meaning: 'phút', example: 'Wait five minutes.', exampleMeaning: 'Đợi năm phút.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'hour', meaning: 'giờ', example: 'The class is one hour long.', exampleMeaning: 'Lớp học kéo dài một giờ.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Mấy giờ rồi?" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['What day is it', 'What time is it', 'How old are you', 'Where are you'], answer: 'What time is it', explanation: 'What time is it = Mấy giờ rồi?', explanationVi: 'What time is it = Mấy giờ rồi?', difficulty: DIFFICULTY.EASY },
      { question: '"7 giờ rưỡi" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Seven o\'clock', 'Half past seven', 'Quarter past seven', 'Quarter to seven'], answer: 'Half past seven', explanation: 'Half past seven = 7 giờ rưỡi', explanationVi: 'Half past seven = 7 giờ rưỡi', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "I wake up ___ every day." (sớm)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'early', explanation: 'Early = sớm', explanationVi: 'Early = sớm', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "midnight" = ?', type: QUIZ_TYPES.MATCHING, options: ['Nửa đêm', 'Buổi trưa', 'Buổi sáng', 'Buổi tối'], answer: 'Nửa đêm', explanation: 'Midnight = nửa đêm', explanationVi: 'Midnight = nửa đêm', difficulty: DIFFICULTY.EASY },
      { question: '"Đúng giờ" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['On time', 'Early', 'Late', 'O\'clock'], answer: 'On time', explanation: 'On time = đúng giờ', explanationVi: 'On time = đúng giờ', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Days & Months',
    titleVi: 'Ngày & Tháng',
    description: 'Learn days of the week and months in English',
    descriptionVi: 'Học các ngày trong tuần và tháng bằng tiếng Anh',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: 'Monday', meaning: 'thứ Hai', example: 'I start work on Monday.', exampleMeaning: 'Tôi bắt đầu làm việc vào thứ Hai.', difficulty: DIFFICULTY.EASY },
      { word: 'Tuesday', meaning: 'thứ Ba', example: 'We have a meeting on Tuesday.', exampleMeaning: 'Chúng tôi có cuộc họp vào thứ Ba.', difficulty: DIFFICULTY.EASY },
      { word: 'Wednesday', meaning: 'thứ Tư', example: 'Wednesday is the middle of the week.', exampleMeaning: 'Thứ Tư là giữa tuần.', difficulty: DIFFICULTY.EASY },
      { word: 'Thursday', meaning: 'thứ Năm', example: 'I play football on Thursday.', exampleMeaning: 'Tôi chơi bóng đá vào thứ Năm.', difficulty: DIFFICULTY.EASY },
      { word: 'Friday', meaning: 'thứ Sáu', example: 'Friday is my favorite day!', exampleMeaning: 'Thứ Sáu là ngày yêu thích của tôi!', difficulty: DIFFICULTY.EASY },
      { word: 'Saturday', meaning: 'thứ Bảy', example: 'I go shopping on Saturday.', exampleMeaning: 'Tôi đi mua sắm vào thứ Bảy.', difficulty: DIFFICULTY.EASY },
      { word: 'Sunday', meaning: 'Chủ nhật', example: 'Sunday is a rest day.', exampleMeaning: 'Chủ nhật là ngày nghỉ.', difficulty: DIFFICULTY.EASY },
      { word: 'January', meaning: 'tháng Một', example: 'January is the first month.', exampleMeaning: 'Tháng Một là tháng đầu tiên.', difficulty: DIFFICULTY.EASY },
      { word: 'February', meaning: 'tháng Hai', example: 'February has 28 days.', exampleMeaning: 'Tháng Hai có 28 ngày.', difficulty: DIFFICULTY.EASY },
      { word: 'today', meaning: 'hôm nay', example: 'Today is a beautiful day.', exampleMeaning: 'Hôm nay là một ngày đẹp.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'tomorrow', meaning: 'ngày mai', example: 'I will go tomorrow.', exampleMeaning: 'Ngày mai tôi sẽ đi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'yesterday', meaning: 'hôm qua', example: 'Yesterday was rainy.', exampleMeaning: 'Hôm qua trời mưa.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'week', meaning: 'tuần', example: 'I study 5 days a week.', exampleMeaning: 'Tôi học 5 ngày một tuần.', difficulty: DIFFICULTY.EASY },
      { word: 'month', meaning: 'tháng', example: 'This month is very busy.', exampleMeaning: 'Tháng này rất bận.', difficulty: DIFFICULTY.EASY },
      { word: 'year', meaning: 'năm', example: 'Happy New Year!', exampleMeaning: 'Chúc mừng năm mới!', difficulty: DIFFICULTY.VERY_EASY },
    ],
    quizzes: [
      { question: '"Thứ Hai" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sunday', 'Monday', 'Tuesday', 'Friday'], answer: 'Monday', explanation: 'Monday = thứ Hai', explanationVi: 'Monday = thứ Hai', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "___ is a rest day." (Chủ nhật)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'Sunday', explanation: 'Sunday = Chủ nhật', explanationVi: 'Sunday = Chủ nhật', difficulty: DIFFICULTY.EASY },
      { question: '"Ngày mai" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Today', 'Yesterday', 'Tomorrow', 'Next week'], answer: 'Tomorrow', explanation: 'Tomorrow = ngày mai', explanationVi: 'Tomorrow = ngày mai', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Nối: "February" = ?', type: QUIZ_TYPES.MATCHING, options: ['Tháng Hai', 'Tháng Một', 'Tháng Ba', 'Tháng Tư'], answer: 'Tháng Hai', explanation: 'February = tháng Hai', explanationVi: 'February = tháng Hai', difficulty: DIFFICULTY.EASY },
      { question: '"Tuần" tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Day', 'Week', 'Month', 'Year'], answer: 'Week', explanation: 'Week = tuần', explanationVi: 'Week = tuần', difficulty: DIFFICULTY.EASY },
    ],
  },
];
