import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishTransportLessons: LessonData[] = [
  {
    title: 'Getting Around',
    titleVi: 'Di chuyển',
    description: 'Learn vocabulary about transportation and directions',
    descriptionVi: 'Học từ vựng về phương tiện giao thông và chỉ đường',
    topic: TOPICS.TRANSPORT,
    vocabulary: [
      { word: 'bus', meaning: 'xe buýt', example: 'I take the bus to work every day.', exampleMeaning: 'Tôi đi xe buýt đi làm mỗi ngày.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'train', meaning: 'tàu hỏa', example: 'The train arrives at 9 AM.', exampleMeaning: 'Tàu đến lúc 9 giờ sáng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'taxi', meaning: 'xe taxi', example: 'Let\'s take a taxi to the airport.', exampleMeaning: 'Chúng ta đi taxi ra sân bay nhé.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'subway', meaning: 'tàu điện ngầm', example: 'The subway is faster than the bus.', exampleMeaning: 'Tàu điện ngầm nhanh hơn xe buýt.', difficulty: DIFFICULTY.EASY },
      { word: 'bicycle', meaning: 'xe đạp', example: 'She rides her bicycle to school.', exampleMeaning: 'Cô ấy đạp xe đến trường.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'motorcycle', meaning: 'xe máy', example: 'Motorcycles are very popular in Vietnam.', exampleMeaning: 'Xe máy rất phổ biến ở Việt Nam.', difficulty: DIFFICULTY.EASY },
      { word: 'airplane', meaning: 'máy bay', example: 'The airplane flies to Tokyo.', exampleMeaning: 'Máy bay bay đến Tokyo.', difficulty: DIFFICULTY.EASY },
      { word: 'ticket', meaning: 'vé', example: 'I need to buy a ticket.', exampleMeaning: 'Tôi cần mua vé.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'station', meaning: 'nhà ga / trạm', example: 'The bus station is near here.', exampleMeaning: 'Trạm xe buýt ở gần đây.', difficulty: DIFFICULTY.EASY },
      { word: 'airport', meaning: 'sân bay', example: 'We arrived at the airport early.', exampleMeaning: 'Chúng tôi đến sân bay sớm.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Xe buýt" trong tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['train', 'bus', 'taxi', 'subway'], answer: 'bus', explanationVi: 'Bus = xe buýt', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"airplane" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Xe đạp', 'Tàu hỏa', 'Máy bay', 'Xe máy'], answer: 'Máy bay', explanationVi: 'Airplane = máy bay', difficulty: DIFFICULTY.EASY },
      { question: '"ticket" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Vé', 'Tiền', 'Bản đồ', 'Hành lý'], answer: 'Vé', explanationVi: 'Ticket = vé (xe, máy bay, tàu...)', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Phương tiện nào phổ biến nhất ở Việt Nam?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['bus', 'train', 'motorcycle', 'subway'], answer: 'motorcycle', explanationVi: 'Motorcycle (xe máy) là phương tiện phổ biến nhất ở Việt Nam', difficulty: DIFFICULTY.EASY },
      { question: '"station" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sân bay', 'Nhà ga / Trạm', 'Bến cảng', 'Đường phố'], answer: 'Nhà ga / Trạm', explanationVi: 'Station = nhà ga, trạm (bus station, train station)', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Asking for Directions',
    titleVi: 'Hỏi đường',
    description: 'Learn how to ask for and give directions',
    descriptionVi: 'Học cách hỏi và chỉ đường',
    topic: TOPICS.TRANSPORT,
    vocabulary: [
      { word: 'left', meaning: 'bên trái', example: 'Turn left at the traffic light.', exampleMeaning: 'Rẽ trái ở đèn giao thông.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'right', meaning: 'bên phải', example: 'The bank is on your right.', exampleMeaning: 'Ngân hàng ở bên phải bạn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'straight', meaning: 'thẳng', example: 'Go straight for two blocks.', exampleMeaning: 'Đi thẳng hai dãy nhà.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'corner', meaning: 'góc đường', example: 'The shop is on the corner.', exampleMeaning: 'Cửa hàng ở góc đường.', difficulty: DIFFICULTY.EASY },
      { word: 'next to', meaning: 'bên cạnh', example: 'The pharmacy is next to the bank.', exampleMeaning: 'Nhà thuốc ở bên cạnh ngân hàng.', difficulty: DIFFICULTY.EASY },
      { word: 'across from', meaning: 'đối diện', example: 'The park is across from the school.', exampleMeaning: 'Công viên đối diện trường học.', difficulty: DIFFICULTY.EASY },
      { word: 'between', meaning: 'ở giữa', example: 'The cafe is between the bookstore and the bank.', exampleMeaning: 'Quán cà phê ở giữa hiệu sách và ngân hàng.', difficulty: DIFFICULTY.EASY },
      { word: 'far', meaning: 'xa', example: 'Is it far from here?', exampleMeaning: 'Nó có xa đây không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'near', meaning: 'gần', example: 'The hospital is near the station.', exampleMeaning: 'Bệnh viện gần nhà ga.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'map', meaning: 'bản đồ', example: 'Can I see the map?', exampleMeaning: 'Tôi có thể xem bản đồ không?', difficulty: DIFFICULTY.VERY_EASY },
    ],
    quizzes: [
      { question: '"Turn left" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Rẽ phải', 'Rẽ trái', 'Đi thẳng', 'Quay lại'], answer: 'Rẽ trái', explanationVi: 'Turn left = rẽ trái', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"next to" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Đối diện', 'Bên cạnh', 'Ở giữa', 'Phía sau'], answer: 'Bên cạnh', explanationVi: 'Next to = bên cạnh', difficulty: DIFFICULTY.EASY },
      { question: '"Xa" trong tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['near', 'far', 'close', 'long'], answer: 'far', explanationVi: 'Far = xa, ngược lại near = gần', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"across from" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Bên cạnh', 'Phía trước', 'Đối diện', 'Phía sau'], answer: 'Đối diện', explanationVi: 'Across from = đối diện', difficulty: DIFFICULTY.EASY },
      { question: '"Go straight" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Rẽ trái', 'Rẽ phải', 'Đi thẳng', 'Dừng lại'], answer: 'Đi thẳng', explanationVi: 'Go straight = đi thẳng', difficulty: DIFFICULTY.VERY_EASY },
    ],
  },
  {
    title: 'At the Airport',
    titleVi: 'Ở sân bay',
    description: 'Essential vocabulary for traveling by air',
    descriptionVi: 'Từ vựng cần thiết khi đi máy bay',
    topic: TOPICS.TRAVEL,
    vocabulary: [
      { word: 'passport', meaning: 'hộ chiếu', example: 'Please show your passport.', exampleMeaning: 'Vui lòng xuất trình hộ chiếu.', difficulty: DIFFICULTY.EASY },
      { word: 'boarding pass', meaning: 'thẻ lên máy bay', example: 'Here is your boarding pass.', exampleMeaning: 'Đây là thẻ lên máy bay của bạn.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'luggage', meaning: 'hành lý', example: 'My luggage is very heavy.', exampleMeaning: 'Hành lý của tôi rất nặng.', difficulty: DIFFICULTY.EASY },
      { word: 'departure', meaning: 'khởi hành', example: 'The departure time is 3 PM.', exampleMeaning: 'Giờ khởi hành là 3 giờ chiều.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'arrival', meaning: 'đến nơi', example: 'The arrival gate is B5.', exampleMeaning: 'Cổng đến là B5.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'gate', meaning: 'cổng', example: 'Please go to gate 12.', exampleMeaning: 'Vui lòng đến cổng 12.', difficulty: DIFFICULTY.EASY },
      { word: 'flight', meaning: 'chuyến bay', example: 'My flight is delayed.', exampleMeaning: 'Chuyến bay của tôi bị trễ.', difficulty: DIFFICULTY.EASY },
      { word: 'check-in', meaning: 'làm thủ tục', example: 'Online check-in is available.', exampleMeaning: 'Có thể làm thủ tục trực tuyến.', difficulty: DIFFICULTY.EASY },
      { word: 'customs', meaning: 'hải quan', example: 'You must go through customs.', exampleMeaning: 'Bạn phải qua hải quan.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'delay', meaning: 'trễ / hoãn', example: 'There is a two-hour delay.', exampleMeaning: 'Có sự trễ hai tiếng.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"passport" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Vé máy bay', 'Hộ chiếu', 'Hành lý', 'Thẻ lên máy bay'], answer: 'Hộ chiếu', explanationVi: 'Passport = hộ chiếu', difficulty: DIFFICULTY.EASY },
      { question: '"Hành lý" trong tiếng Anh là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['passport', 'ticket', 'luggage', 'gate'], answer: 'luggage', explanationVi: 'Luggage = hành lý', difficulty: DIFFICULTY.EASY },
      { question: '"departure" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Đến nơi', 'Khởi hành', 'Trễ', 'Hủy'], answer: 'Khởi hành', explanationVi: 'Departure = khởi hành, ngược lại arrival = đến nơi', difficulty: DIFFICULTY.MEDIUM },
      { question: '"flight" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Sân bay', 'Chuyến bay', 'Cổng', 'Hải quan'], answer: 'Chuyến bay', explanationVi: 'Flight = chuyến bay', difficulty: DIFFICULTY.EASY },
      { question: '"customs" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Hải quan', 'Cổng', 'Quầy vé', 'Phòng chờ'], answer: 'Hải quan', explanationVi: 'Customs = hải quan, nơi kiểm tra hàng hóa khi nhập cảnh', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
