import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const englishWorkLessons: LessonData[] = [
  {
    title: 'Job Interview',
    titleVi: 'Phỏng vấn xin việc',
    description: 'Prepare for job interviews in English',
    descriptionVi: 'Chuẩn bị cho phỏng vấn xin việc bằng tiếng Anh',
    topic: TOPICS.WORK,
    xpReward: 25,
    vocabulary: [
      { word: 'resume', meaning: 'hồ sơ xin việc', example: 'Please send your resume to HR.', exampleMeaning: 'Vui lòng gửi hồ sơ đến phòng nhân sự.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'interview', meaning: 'phỏng vấn', example: 'I have a job interview tomorrow.', exampleMeaning: 'Ngày mai tôi có buổi phỏng vấn.', difficulty: DIFFICULTY.EASY },
      { word: 'experience', meaning: 'kinh nghiệm', example: 'I have 3 years of experience.', exampleMeaning: 'Tôi có 3 năm kinh nghiệm.', difficulty: DIFFICULTY.EASY },
      { word: 'salary', meaning: 'lương', example: 'What is the expected salary?', exampleMeaning: 'Mức lương mong muốn là bao nhiêu?', difficulty: DIFFICULTY.EASY },
      { word: 'position', meaning: 'vị trí', example: 'I am applying for the manager position.', exampleMeaning: 'Tôi ứng tuyển vị trí quản lý.', difficulty: DIFFICULTY.EASY },
      { word: 'strength', meaning: 'điểm mạnh', example: 'My strength is teamwork.', exampleMeaning: 'Điểm mạnh của tôi là làm việc nhóm.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'weakness', meaning: 'điểm yếu', example: 'My weakness is being too perfectionist.', exampleMeaning: 'Điểm yếu của tôi là quá cầu toàn.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'qualification', meaning: 'bằng cấp/trình độ', example: 'What qualifications do you have?', exampleMeaning: 'Bạn có bằng cấp gì?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'deadline', meaning: 'hạn chót', example: 'The deadline is next Friday.', exampleMeaning: 'Hạn chót là thứ Sáu tuần sau.', difficulty: DIFFICULTY.EASY },
      { word: 'teamwork', meaning: 'làm việc nhóm', example: 'Teamwork is very important here.', exampleMeaning: 'Làm việc nhóm rất quan trọng ở đây.', difficulty: DIFFICULTY.EASY },
      { word: 'promotion', meaning: 'thăng chức', example: 'She got a promotion last month.', exampleMeaning: 'Cô ấy được thăng chức tháng trước.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'colleague', meaning: 'đồng nghiệp', example: 'My colleagues are very friendly.', exampleMeaning: 'Đồng nghiệp của tôi rất thân thiện.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'overtime', meaning: 'làm thêm giờ', example: 'I often work overtime.', exampleMeaning: 'Tôi thường làm thêm giờ.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'benefit', meaning: 'phúc lợi', example: 'The company offers good benefits.', exampleMeaning: 'Công ty có phúc lợi tốt.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'apply', meaning: 'ứng tuyển', example: 'I want to apply for this job.', exampleMeaning: 'Tôi muốn ứng tuyển công việc này.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Phỏng vấn" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Meeting', 'Interview', 'Discussion', 'Presentation'], answer: 'Interview', explanation: 'Phỏng vấn = Interview', explanationVi: 'Phỏng vấn = Interview', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "I have 3 years of _____." (kinh nghiệm)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'experience', explanation: 'Experience = kinh nghiệm', explanationVi: 'Experience = kinh nghiệm', difficulty: DIFFICULTY.EASY },
      { question: '"Lương" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Bonus', 'Salary', 'Benefit', 'Income'], answer: 'Salary', explanation: 'Salary = lương (hàng tháng)', explanationVi: 'Salary = lương (hàng tháng)', difficulty: DIFFICULTY.EASY },
      { question: 'Match: "đồng nghiệp" = ?', type: QUIZ_TYPES.MATCHING, options: ['Manager', 'Colleague', 'Boss', 'Employee'], answer: 'Colleague', explanation: 'Colleague = đồng nghiệp', explanationVi: 'Colleague = đồng nghiệp', difficulty: DIFFICULTY.MEDIUM },
      { question: 'Which means "thăng chức"?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Promotion', 'Position', 'Permission', 'Presentation'], answer: 'Promotion', explanation: 'Promotion = thăng chức', explanationVi: 'Promotion = thăng chức', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
  {
    title: 'Office Communication',
    titleVi: 'Giao tiếp văn phòng',
    description: 'Essential phrases for workplace communication',
    descriptionVi: 'Các cụm từ cần thiết cho giao tiếp nơi làm việc',
    topic: TOPICS.WORK,
    xpReward: 25,
    vocabulary: [
      { word: 'meeting', meaning: 'cuộc họp', example: 'We have a meeting at 2 PM.', exampleMeaning: 'Chúng ta có cuộc họp lúc 2 giờ.', difficulty: DIFFICULTY.EASY },
      { word: 'email', meaning: 'thư điện tử', example: 'I will send you an email.', exampleMeaning: 'Tôi sẽ gửi email cho bạn.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'report', meaning: 'báo cáo', example: 'Please submit the report by Friday.', exampleMeaning: 'Vui lòng nộp báo cáo trước thứ Sáu.', difficulty: DIFFICULTY.EASY },
      { word: 'schedule', meaning: 'lịch trình', example: 'What is your schedule today?', exampleMeaning: 'Lịch trình hôm nay của bạn thế nào?', difficulty: DIFFICULTY.EASY },
      { word: 'project', meaning: 'dự án', example: 'This project is due next month.', exampleMeaning: 'Dự án này đến hạn tháng sau.', difficulty: DIFFICULTY.EASY },
      { word: 'presentation', meaning: 'bài thuyết trình', example: 'I need to prepare a presentation.', exampleMeaning: 'Tôi cần chuẩn bị bài thuyết trình.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'feedback', meaning: 'phản hồi', example: 'Can you give me some feedback?', exampleMeaning: 'Bạn có thể cho tôi phản hồi không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'approve', meaning: 'phê duyệt', example: 'The manager approved the plan.', exampleMeaning: 'Quản lý đã phê duyệt kế hoạch.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'postpone', meaning: 'hoãn lại', example: 'Let\'s postpone the meeting to tomorrow.', exampleMeaning: 'Hoãn cuộc họp sang ngày mai nhé.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'confirm', meaning: 'xác nhận', example: 'Please confirm your attendance.', exampleMeaning: 'Vui lòng xác nhận tham dự.', difficulty: DIFFICULTY.EASY },
      { word: 'attach', meaning: 'đính kèm', example: 'I attached the file to the email.', exampleMeaning: 'Tôi đã đính kèm file trong email.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'urgent', meaning: 'khẩn cấp', example: 'This is an urgent matter.', exampleMeaning: 'Đây là vấn đề khẩn cấp.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'available', meaning: 'có thể/rảnh', example: 'Are you available at 3 PM?', exampleMeaning: 'Bạn rảnh lúc 3 giờ không?', difficulty: DIFFICULTY.EASY },
      { word: 'in charge of', meaning: 'phụ trách', example: 'Who is in charge of this project?', exampleMeaning: 'Ai phụ trách dự án này?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'follow up', meaning: 'theo dõi/tiếp tục', example: 'I will follow up on this issue.', exampleMeaning: 'Tôi sẽ theo dõi vấn đề này.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Cuộc họp" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Meeting', 'Greeting', 'Eating', 'Seating'], answer: 'Meeting', explanation: 'Cuộc họp = Meeting', explanationVi: 'Cuộc họp = Meeting', difficulty: DIFFICULTY.EASY },
      { question: 'Fill in: "Please _____ the report by Friday." (nộp)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'submit', explanation: 'Submit = nộp/gửi', explanationVi: 'Submit = nộp/gửi', difficulty: DIFFICULTY.MEDIUM },
      { question: '"Hoãn lại" in English is...', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Cancel', 'Postpone', 'Delete', 'Reject'], answer: 'Postpone', explanation: 'Postpone = hoãn lại (không phải hủy)', explanationVi: 'Postpone = hoãn lại (không phải hủy)', difficulty: DIFFICULTY.MEDIUM },
      { question: 'Match: "phản hồi" = ?', type: QUIZ_TYPES.MATCHING, options: ['Report', 'Feedback', 'Review', 'Comment'], answer: 'Feedback', explanation: 'Feedback = phản hồi', explanationVi: 'Feedback = phản hồi', difficulty: DIFFICULTY.MEDIUM },
      { question: 'Which phrase means "phụ trách"?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Look after', 'In charge of', 'Take care', 'Deal with'], answer: 'In charge of', explanation: 'In charge of = phụ trách', explanationVi: 'In charge of = phụ trách', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
