import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const japaneseTravelLessons: LessonData[] = [
  {
    title: '交通 (Transportation)',
    titleVi: 'Giao thông',
    description: 'Vocabulary for getting around in Japan',
    descriptionVi: 'Từ vựng di chuyển ở Nhật Bản',
    topic: TOPICS.TRANSPORT,
    vocabulary: [
      { word: '電車', reading: 'densha', meaning: 'tàu điện', example: '電車で行きます。', exampleMeaning: 'Tôi đi bằng tàu điện.', difficulty: DIFFICULTY.EASY },
      { word: '駅', reading: 'eki', meaning: 'ga tàu', example: '駅はどこですか？', exampleMeaning: 'Ga tàu ở đâu?', difficulty: DIFFICULTY.EASY },
      { word: 'バス', reading: 'basu', meaning: 'xe buýt', example: 'バスに乗ります。', exampleMeaning: 'Tôi đi xe buýt.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '切符', reading: 'kippu', meaning: 'vé', example: '切符を買います。', exampleMeaning: 'Tôi mua vé.', difficulty: DIFFICULTY.EASY },
      { word: '空港', reading: 'kuukou', meaning: 'sân bay', example: '空港まで一時間です。', exampleMeaning: 'Đến sân bay mất 1 tiếng.', difficulty: DIFFICULTY.EASY },
      { word: 'タクシー', reading: 'takushii', meaning: 'taxi', example: 'タクシーを呼んでください。', exampleMeaning: 'Gọi taxi giúp tôi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '地下鉄', reading: 'chikatetsu', meaning: 'tàu điện ngầm', example: '地下鉄が便利です。', exampleMeaning: 'Tàu điện ngầm tiện lợi.', difficulty: DIFFICULTY.MEDIUM },
      { word: '乗り換え', reading: 'norikae', meaning: 'chuyển tàu', example: '次の駅で乗り換えます。', exampleMeaning: 'Chuyển tàu ở ga tiếp theo.', difficulty: DIFFICULTY.MEDIUM },
      { word: '出口', reading: 'deguchi', meaning: 'lối ra', example: '出口はあちらです。', exampleMeaning: 'Lối ra ở phía kia.', difficulty: DIFFICULTY.EASY },
      { word: '入口', reading: 'iriguchi', meaning: 'lối vào', example: '入口はどこですか？', exampleMeaning: 'Lối vào ở đâu?', difficulty: DIFFICULTY.EASY },
      { word: '片道', reading: 'katamichi', meaning: 'một chiều', example: '片道切符をください。', exampleMeaning: 'Cho tôi vé một chiều.', difficulty: DIFFICULTY.MEDIUM },
      { word: '往復', reading: 'oufuku', meaning: 'khứ hồi', example: '往復切符はいくらですか？', exampleMeaning: 'Vé khứ hồi bao nhiêu?', difficulty: DIFFICULTY.MEDIUM },
      { word: '時刻表', reading: 'jikokuhyou', meaning: 'bảng giờ tàu', example: '時刻表を見てください。', exampleMeaning: 'Xem bảng giờ tàu nhé.', difficulty: DIFFICULTY.MEDIUM },
      { word: '遅れる', reading: 'okureru', meaning: 'trễ/muộn', example: '電車が遅れています。', exampleMeaning: 'Tàu đang bị trễ.', difficulty: DIFFICULTY.MEDIUM },
      { word: '到着', reading: 'touchaku', meaning: 'đến nơi', example: '到着時間は何時ですか？', exampleMeaning: 'Giờ đến là mấy giờ?', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"電車" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Xe buýt', 'Tàu điện', 'Taxi', 'Máy bay'], answer: 'Tàu điện', explanation: '電車 (densha) = tàu điện', explanationVi: '電車 (densha) = tàu điện', difficulty: DIFFICULTY.EASY },
      { question: 'Cách đọc của "駅" là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['machi', 'eki', 'michi', 'ie'], answer: 'eki', explanation: '駅 đọc là "eki" = ga tàu', explanationVi: '駅 đọc là "eki" = ga tàu', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "___を買います。" (vé)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '切符', explanation: '切符 (kippu) = vé', explanationVi: '切符 (kippu) = vé', difficulty: DIFFICULTY.EASY },
      { question: '"Lối ra" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['入口', '出口', '改札', '窓口'], answer: '出口', explanation: '出口 (deguchi) = lối ra', explanationVi: '出口 (deguchi) = lối ra', difficulty: DIFFICULTY.EASY },
      { question: 'Ghép: "乗り換え" = ?', type: QUIZ_TYPES.MATCHING, options: ['Mua vé', 'Chuyển tàu', 'Lên tàu', 'Xuống tàu'], answer: 'Chuyển tàu', explanation: '乗り換え (norikae) = chuyển tàu', explanationVi: '乗り換え (norikae) = chuyển tàu', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
  {
    title: '買い物 (Shopping)',
    titleVi: 'Mua sắm',
    description: 'Shopping vocabulary and phrases in Japanese',
    descriptionVi: 'Từ vựng và cụm từ mua sắm tiếng Nhật',
    topic: TOPICS.SHOPPING,
    vocabulary: [
      { word: 'いくらですか', reading: 'ikura desu ka', meaning: 'bao nhiêu tiền?', example: 'これはいくらですか？', exampleMeaning: 'Cái này bao nhiêu tiền?', difficulty: DIFFICULTY.EASY },
      { word: '高い', reading: 'takai', meaning: 'đắt', example: 'ちょっと高いですね。', exampleMeaning: 'Hơi đắt nhỉ.', difficulty: DIFFICULTY.EASY },
      { word: '安い', reading: 'yasui', meaning: 'rẻ', example: 'この店は安いです。', exampleMeaning: 'Cửa hàng này rẻ.', difficulty: DIFFICULTY.EASY },
      { word: '大きい', reading: 'ookii', meaning: 'to/lớn', example: 'もっと大きいサイズはありますか？', exampleMeaning: 'Có size lớn hơn không?', difficulty: DIFFICULTY.EASY },
      { word: '小さい', reading: 'chiisai', meaning: 'nhỏ', example: '小さいのをください。', exampleMeaning: 'Cho tôi cái nhỏ.', difficulty: DIFFICULTY.EASY },
      { word: '試着', reading: 'shichaku', meaning: 'thử đồ', example: '試着してもいいですか？', exampleMeaning: 'Tôi thử đồ được không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'レジ', reading: 'reji', meaning: 'quầy thanh toán', example: 'レジはあちらです。', exampleMeaning: 'Quầy thanh toán ở phía kia.', difficulty: DIFFICULTY.EASY },
      { word: '袋', reading: 'fukuro', meaning: 'túi', example: '袋はいりますか？', exampleMeaning: 'Bạn cần túi không?', difficulty: DIFFICULTY.EASY },
      { word: 'クレジットカード', reading: 'kurejitto kaado', meaning: 'thẻ tín dụng', example: 'クレジットカードは使えますか？', exampleMeaning: 'Dùng thẻ tín dụng được không?', difficulty: DIFFICULTY.EASY },
      { word: '現金', reading: 'genkin', meaning: 'tiền mặt', example: '現金でお願いします。', exampleMeaning: 'Tôi trả tiền mặt.', difficulty: DIFFICULTY.EASY },
      { word: 'セール', reading: 'seeru', meaning: 'giảm giá', example: '今セール中です。', exampleMeaning: 'Đang giảm giá.', difficulty: DIFFICULTY.EASY },
      { word: 'お土産', reading: 'omiyage', meaning: 'quà lưu niệm', example: 'お土産を買いたいです。', exampleMeaning: 'Tôi muốn mua quà lưu niệm.', difficulty: DIFFICULTY.EASY },
      { word: '色', reading: 'iro', meaning: 'màu sắc', example: '他の色はありますか？', exampleMeaning: 'Có màu khác không?', difficulty: DIFFICULTY.EASY },
      { word: '包む', reading: 'tsutsumu', meaning: 'gói (quà)', example: 'プレゼント用に包んでください。', exampleMeaning: 'Gói làm quà giúp tôi.', difficulty: DIFFICULTY.MEDIUM },
      { word: '免税', reading: 'menzei', meaning: 'miễn thuế', example: '免税で買えますか？', exampleMeaning: 'Mua miễn thuế được không?', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: 'Hỏi giá tiếng Nhật nói thế nào?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['なんですか', 'いくらですか', 'どこですか', 'いつですか'], answer: 'いくらですか', explanation: 'いくらですか = bao nhiêu tiền?', explanationVi: 'いくらですか = bao nhiêu tiền?', difficulty: DIFFICULTY.EASY },
      { question: '"高い" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Rẻ', 'Đắt', 'To', 'Nhỏ'], answer: 'Đắt', explanation: '高い (takai) = đắt (cũng có nghĩa là cao)', explanationVi: '高い (takai) = đắt (cũng có nghĩa là cao)', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "___してもいいですか？" (thử đồ)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '試着', explanation: '試着 (shichaku) = thử đồ', explanationVi: '試着 (shichaku) = thử đồ', difficulty: DIFFICULTY.MEDIUM },
      { question: '"Quà lưu niệm" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['プレゼント', 'お土産', 'おみやげ', 'Both B and C'], answer: 'Both B and C', explanation: 'お土産 = おみやげ (omiyage) = quà lưu niệm', explanationVi: 'お土産 = おみやげ (omiyage) = quà lưu niệm', difficulty: DIFFICULTY.EASY },
      { question: 'Ghép: "現金" = ?', type: QUIZ_TYPES.MATCHING, options: ['Thẻ tín dụng', 'Tiền mặt', 'Hóa đơn', 'Tiền thối'], answer: 'Tiền mặt', explanation: '現金 (genkin) = tiền mặt', explanationVi: '現金 (genkin) = tiền mặt', difficulty: DIFFICULTY.EASY },
    ],
  },
];
