import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const japaneseFoodLessons: LessonData[] = [
  {
    title: '食べ物 (Food)',
    titleVi: 'Đồ ăn',
    description: 'Learn common food vocabulary in Japanese',
    descriptionVi: 'Học từ vựng về đồ ăn phổ biến trong tiếng Nhật',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: 'ご飯', reading: 'gohan', meaning: 'cơm', example: 'ご飯を食べましょう。', exampleMeaning: 'Ăn cơm thôi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'ラーメン', reading: 'raamen', meaning: 'mì ramen', example: 'ラーメンが好きです。', exampleMeaning: 'Tôi thích mì ramen.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '寿司', reading: 'sushi', meaning: 'sushi', example: '寿司を食べたいです。', exampleMeaning: 'Tôi muốn ăn sushi.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '肉', reading: 'niku', meaning: 'thịt', example: '肉が好きですか？', exampleMeaning: 'Bạn thích thịt không?', difficulty: DIFFICULTY.EASY },
      { word: '魚', reading: 'sakana', meaning: 'cá', example: '魚は新鮮です。', exampleMeaning: 'Cá rất tươi.', difficulty: DIFFICULTY.EASY },
      { word: '野菜', reading: 'yasai', meaning: 'rau', example: '野菜をたくさん食べてください。', exampleMeaning: 'Hãy ăn nhiều rau.', difficulty: DIFFICULTY.EASY },
      { word: '卵', reading: 'tamago', meaning: 'trứng', example: '卵焼きを作ります。', exampleMeaning: 'Tôi làm trứng cuộn.', difficulty: DIFFICULTY.EASY },
      { word: 'パン', reading: 'pan', meaning: 'bánh mì', example: '朝はパンを食べます。', exampleMeaning: 'Buổi sáng tôi ăn bánh mì.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '水', reading: 'mizu', meaning: 'nước', example: '水をください。', exampleMeaning: 'Cho tôi nước.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'お茶', reading: 'ocha', meaning: 'trà', example: 'お茶を飲みましょう。', exampleMeaning: 'Uống trà nhé.', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'コーヒー', reading: 'koohii', meaning: 'cà phê', example: 'コーヒーを一杯ください。', exampleMeaning: 'Cho tôi một ly cà phê.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '牛乳', reading: 'gyuunyuu', meaning: 'sữa bò', example: '牛乳を飲みます。', exampleMeaning: 'Tôi uống sữa.', difficulty: DIFFICULTY.EASY },
      { word: '果物', reading: 'kudamono', meaning: 'trái cây', example: '果物は甘いです。', exampleMeaning: 'Trái cây ngọt.', difficulty: DIFFICULTY.EASY },
      { word: 'おいしい', reading: 'oishii', meaning: 'ngon', example: 'このラーメンはおいしいです！', exampleMeaning: 'Mì ramen này ngon quá!', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'お腹が空いた', reading: 'onaka ga suita', meaning: 'đói bụng', example: 'お腹が空きました。', exampleMeaning: 'Tôi đói bụng rồi.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"ご飯" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Mì', 'Cơm', 'Bánh mì', 'Sushi'], answer: 'Cơm', explanation: 'ご飯 (gohan) = cơm, cũng có nghĩa là bữa ăn', explanationVi: 'ご飯 (gohan) = cơm, cũng có nghĩa là bữa ăn', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Cách đọc của "魚" là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['niku', 'sakana', 'tamago', 'yasai'], answer: 'sakana', explanation: '魚 đọc là "sakana" = cá', explanationVi: '魚 đọc là "sakana" = cá', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "___をください。" (nước)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '水', explanation: '水 (mizu) = nước. "水をください" = Cho tôi nước', explanationVi: '水 (mizu) = nước. "水をください" = Cho tôi nước', difficulty: DIFFICULTY.EASY },
      { question: '"おいしい" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Đắt', 'Ngon', 'Cay', 'Ngọt'], answer: 'Ngon', explanation: 'おいしい (oishii) = ngon, dùng khen đồ ăn', explanationVi: 'おいしい (oishii) = ngon, dùng khen đồ ăn', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Ghép nghĩa: "野菜" = ?', type: QUIZ_TYPES.MATCHING, options: ['Thịt', 'Rau', 'Cá', 'Trứng'], answer: 'Rau', explanation: '野菜 (yasai) = rau', explanationVi: '野菜 (yasai) = rau', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'レストランで (At a Restaurant)',
    titleVi: 'Tại nhà hàng',
    description: 'Ordering food at Japanese restaurants',
    descriptionVi: 'Gọi món tại nhà hàng Nhật',
    topic: TOPICS.FOOD,
    vocabulary: [
      { word: 'メニュー', reading: 'menyuu', meaning: 'thực đơn', example: 'メニューを見せてください。', exampleMeaning: 'Cho tôi xem thực đơn.', difficulty: DIFFICULTY.EASY },
      { word: '注文', reading: 'chuumon', meaning: 'gọi món', example: '注文してもいいですか？', exampleMeaning: 'Tôi gọi món được không?', difficulty: DIFFICULTY.MEDIUM },
      { word: 'お会計', reading: 'okaikei', meaning: 'thanh toán', example: 'お会計お願いします。', exampleMeaning: 'Cho tôi thanh toán.', difficulty: DIFFICULTY.MEDIUM },
      { word: '一つ', reading: 'hitotsu', meaning: 'một cái', example: 'これを一つください。', exampleMeaning: 'Cho tôi một cái này.', difficulty: DIFFICULTY.EASY },
      { word: '辛い', reading: 'karai', meaning: 'cay', example: 'これは辛いですか？', exampleMeaning: 'Cái này có cay không?', difficulty: DIFFICULTY.EASY },
      { word: '甘い', reading: 'amai', meaning: 'ngọt', example: 'このケーキは甘いです。', exampleMeaning: 'Bánh này ngọt.', difficulty: DIFFICULTY.EASY },
      { word: '温かい', reading: 'atatakai', meaning: 'ấm/nóng', example: '温かいお茶をください。', exampleMeaning: 'Cho tôi trà nóng.', difficulty: DIFFICULTY.EASY },
      { word: '冷たい', reading: 'tsumetai', meaning: 'lạnh', example: '冷たい水をください。', exampleMeaning: 'Cho tôi nước lạnh.', difficulty: DIFFICULTY.EASY },
      { word: 'おすすめ', reading: 'osusume', meaning: 'món đề xuất', example: 'おすすめは何ですか？', exampleMeaning: 'Món đề xuất là gì?', difficulty: DIFFICULTY.MEDIUM },
      { word: '定食', reading: 'teishoku', meaning: 'set ăn', example: '焼き魚定食をください。', exampleMeaning: 'Cho tôi set cá nướng.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'お箸', reading: 'ohashi', meaning: 'đũa', example: 'お箸をもう一膳ください。', exampleMeaning: 'Cho tôi thêm một đôi đũa.', difficulty: DIFFICULTY.EASY },
      { word: 'スプーン', reading: 'supuun', meaning: 'thìa/muỗng', example: 'スプーンをください。', exampleMeaning: 'Cho tôi cái thìa.', difficulty: DIFFICULTY.EASY },
      { word: 'ごちそうさま', reading: 'gochisousama', meaning: 'cảm ơn bữa ăn (sau khi ăn)', example: 'ごちそうさまでした！', exampleMeaning: 'Cảm ơn bữa ăn ngon!', difficulty: DIFFICULTY.MEDIUM },
      { word: '持ち帰り', reading: 'mochikaeri', meaning: 'mang đi', example: '持ち帰りでお願いします。', exampleMeaning: 'Cho tôi mang đi.', difficulty: DIFFICULTY.MEDIUM },
      { word: '予約', reading: 'yoyaku', meaning: 'đặt bàn/đặt chỗ', example: '予約したいのですが。', exampleMeaning: 'Tôi muốn đặt bàn.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: 'Khi muốn thanh toán, bạn nói gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['いただきます', 'お会計お願いします', 'ごちそうさま', 'すみません'], answer: 'お会計お願いします', explanation: 'お会計お願いします (okaikei onegaishimasu) = Cho tôi thanh toán', explanationVi: 'お会計お願いします = Cho tôi thanh toán', difficulty: DIFFICULTY.MEDIUM },
      { question: '"辛い" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Ngọt', 'Cay', 'Mặn', 'Chua'], answer: 'Cay', explanation: '辛い (karai) = cay', explanationVi: '辛い (karai) = cay', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "___を見せてください。" (thực đơn)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: 'メニュー', explanation: 'メニュー (menyuu) = thực đơn', explanationVi: 'メニュー (menyuu) = thực đơn', difficulty: DIFFICULTY.EASY },
      { question: 'Sau khi ăn xong, bạn nói gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['いただきます', 'ごちそうさまでした', 'おいしい', 'すみません'], answer: 'ごちそうさまでした', explanation: 'ごちそうさまでした nói sau khi ăn xong để cảm ơn', explanationVi: 'ごちそうさまでした nói sau khi ăn xong để cảm ơn', difficulty: DIFFICULTY.MEDIUM },
      { question: 'Ghép: "冷たい" = ?', type: QUIZ_TYPES.MATCHING, options: ['Nóng', 'Lạnh', 'Cay', 'Ngọt'], answer: 'Lạnh', explanation: '冷たい (tsumetai) = lạnh (cho đồ vật, thức ăn)', explanationVi: '冷たい (tsumetai) = lạnh (cho đồ vật, thức ăn)', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: '日常生活 (Daily Life)',
    titleVi: 'Cuộc sống hàng ngày',
    description: 'Common words for daily activities',
    descriptionVi: 'Từ vựng cho hoạt động hàng ngày',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: '起きる', reading: 'okiru', meaning: 'thức dậy', example: '毎朝六時に起きます。', exampleMeaning: 'Mỗi sáng tôi dậy lúc 6 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '寝る', reading: 'neru', meaning: 'ngủ', example: '十一時に寝ます。', exampleMeaning: 'Tôi ngủ lúc 11 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '食べる', reading: 'taberu', meaning: 'ăn', example: '朝ご飯を食べます。', exampleMeaning: 'Tôi ăn sáng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '飲む', reading: 'nomu', meaning: 'uống', example: 'コーヒーを飲みます。', exampleMeaning: 'Tôi uống cà phê.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '行く', reading: 'iku', meaning: 'đi', example: '学校に行きます。', exampleMeaning: 'Tôi đi học.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '帰る', reading: 'kaeru', meaning: 'về (nhà)', example: '五時に帰ります。', exampleMeaning: 'Tôi về lúc 5 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '勉強する', reading: 'benkyou suru', meaning: 'học', example: '日本語を勉強します。', exampleMeaning: 'Tôi học tiếng Nhật.', difficulty: DIFFICULTY.EASY },
      { word: '働く', reading: 'hataraku', meaning: 'làm việc', example: '月曜日から金曜日まで働きます。', exampleMeaning: 'Tôi làm việc từ thứ 2 đến thứ 6.', difficulty: DIFFICULTY.MEDIUM },
      { word: '買い物', reading: 'kaimono', meaning: 'mua sắm', example: '週末に買い物に行きます。', exampleMeaning: 'Cuối tuần tôi đi mua sắm.', difficulty: DIFFICULTY.EASY },
      { word: '料理する', reading: 'ryouri suru', meaning: 'nấu ăn', example: '毎日料理します。', exampleMeaning: 'Tôi nấu ăn mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: '洗う', reading: 'arau', meaning: 'rửa/giặt', example: '手を洗ってください。', exampleMeaning: 'Hãy rửa tay.', difficulty: DIFFICULTY.EASY },
      { word: '見る', reading: 'miru', meaning: 'xem/nhìn', example: 'テレビを見ます。', exampleMeaning: 'Tôi xem TV.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '聞く', reading: 'kiku', meaning: 'nghe', example: '音楽を聞きます。', exampleMeaning: 'Tôi nghe nhạc.', difficulty: DIFFICULTY.EASY },
      { word: '読む', reading: 'yomu', meaning: 'đọc', example: '本を読みます。', exampleMeaning: 'Tôi đọc sách.', difficulty: DIFFICULTY.EASY },
      { word: '書く', reading: 'kaku', meaning: 'viết', example: '手紙を書きます。', exampleMeaning: 'Tôi viết thư.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"起きる" nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Ngủ', 'Thức dậy', 'Ăn', 'Đi'], answer: 'Thức dậy', explanation: '起きる (okiru) = thức dậy', explanationVi: '起きる (okiru) = thức dậy', difficulty: DIFFICULTY.EASY },
      { question: 'Cách đọc của "食べる" là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['nomu', 'taberu', 'miru', 'kiku'], answer: 'taberu', explanation: '食べる đọc là "taberu" = ăn', explanationVi: '食べる đọc là "taberu" = ăn', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào: "日本語を___します。" (học)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '勉強', explanation: '勉強する (benkyou suru) = học', explanationVi: '勉強する (benkyou suru) = học', difficulty: DIFFICULTY.EASY },
      { question: '"Về nhà" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['行く', '帰る', '来る', '出る'], answer: '帰る', explanation: '帰る (kaeru) = về nhà', explanationVi: '帰る (kaeru) = về nhà', difficulty: DIFFICULTY.EASY },
      { question: 'Ghép: "買い物" = ?', type: QUIZ_TYPES.MATCHING, options: ['Nấu ăn', 'Mua sắm', 'Làm việc', 'Học'], answer: 'Mua sắm', explanation: '買い物 (kaimono) = mua sắm', explanationVi: '買い物 (kaimono) = mua sắm', difficulty: DIFFICULTY.EASY },
    ],
  },
];
