import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const japaneseDailyLessons: LessonData[] = [
  {
    title: 'Daily Routine (日常生活)',
    titleVi: 'Sinh hoạt hàng ngày',
    description: 'Learn vocabulary about daily activities in Japanese',
    descriptionVi: 'Học từ vựng về hoạt động hàng ngày bằng tiếng Nhật',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: '起きる', reading: 'おきる', meaning: 'thức dậy', example: '毎朝6時に起きます。', exampleMeaning: 'Tôi thức dậy lúc 6 giờ mỗi sáng.', difficulty: DIFFICULTY.EASY },
      { word: '寝る', reading: 'ねる', meaning: 'đi ngủ', example: '11時に寝ます。', exampleMeaning: 'Tôi đi ngủ lúc 11 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '食べる', reading: 'たべる', meaning: 'ăn', example: '朝ごはんを食べます。', exampleMeaning: 'Tôi ăn sáng.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '飲む', reading: 'のむ', meaning: 'uống', example: 'コーヒーを飲みます。', exampleMeaning: 'Tôi uống cà phê.', difficulty: DIFFICULTY.EASY },
      { word: '行く', reading: 'いく', meaning: 'đi', example: '学校に行きます。', exampleMeaning: 'Tôi đi đến trường.', difficulty: DIFFICULTY.EASY },
      { word: '帰る', reading: 'かえる', meaning: 'về nhà', example: '5時に帰ります。', exampleMeaning: 'Tôi về nhà lúc 5 giờ.', difficulty: DIFFICULTY.EASY },
      { word: 'シャワーを浴びる', reading: 'シャワーをあびる', meaning: 'tắm (vòi sen)', example: '朝シャワーを浴びます。', exampleMeaning: 'Tôi tắm vào buổi sáng.', difficulty: DIFFICULTY.MEDIUM },
      { word: '歯を磨く', reading: 'はをみがく', meaning: 'đánh răng', example: '毎日歯を磨きます。', exampleMeaning: 'Tôi đánh răng mỗi ngày.', difficulty: DIFFICULTY.MEDIUM },
      { word: '着替える', reading: 'きがえる', meaning: 'thay quần áo', example: '制服に着替えます。', exampleMeaning: 'Tôi thay đồng phục.', difficulty: DIFFICULTY.MEDIUM },
      { word: '勉強する', reading: 'べんきょうする', meaning: 'học bài', example: '毎日日本語を勉強します。', exampleMeaning: 'Tôi học tiếng Nhật mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: '仕事する', reading: 'しごとする', meaning: 'làm việc', example: '9時から仕事します。', exampleMeaning: 'Tôi làm việc từ 9 giờ.', difficulty: DIFFICULTY.EASY },
      { word: '運動する', reading: 'うんどうする', meaning: 'tập thể dục', example: '毎朝運動します。', exampleMeaning: 'Tôi tập thể dục mỗi sáng.', difficulty: DIFFICULTY.EASY },
      { word: '買い物する', reading: 'かいものする', meaning: 'mua sắm', example: '週末に買い物します。', exampleMeaning: 'Tôi mua sắm vào cuối tuần.', difficulty: DIFFICULTY.EASY },
      { word: '料理する', reading: 'りょうりする', meaning: 'nấu ăn', example: '夕食を料理します。', exampleMeaning: 'Tôi nấu bữa tối.', difficulty: DIFFICULTY.EASY },
      { word: '散歩する', reading: 'さんぽする', meaning: 'đi dạo', example: '公園で散歩します。', exampleMeaning: 'Tôi đi dạo ở công viên.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Thức dậy" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['寝る', '起きる', '食べる', '行く'], answer: '起きる', explanation: '起きる (おきる) = thức dậy', explanationVi: '起きる (おきる) = thức dậy', difficulty: DIFFICULTY.EASY },
      { question: 'Điền vào chỗ trống: "コーヒーを___ます。" (uống)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '飲み', explanation: '飲む → 飲みます = uống', explanationVi: '飲む → 飲みます = uống', difficulty: DIFFICULTY.EASY },
      { question: '"勉強する" có nghĩa là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['Làm việc', 'Học bài', 'Tập thể dục', 'Nấu ăn'], answer: 'Học bài', explanation: '勉強する = học bài', explanationVi: '勉強する = học bài', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "散歩する" = ?', type: QUIZ_TYPES.MATCHING, options: ['Đi dạo', 'Mua sắm', 'Nấu ăn', 'Về nhà'], answer: 'Đi dạo', explanation: '散歩する = đi dạo', explanationVi: '散歩する = đi dạo', difficulty: DIFFICULTY.EASY },
      { question: '"Đánh răng" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['歯を磨く', '着替える', 'シャワーを浴びる', '起きる'], answer: '歯を磨く', explanation: '歯を磨く (はをみがく) = đánh răng', explanationVi: '歯を磨く (はをみがく) = đánh răng', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
  {
    title: 'Numbers & Time (数字と時間)',
    titleVi: 'Số đếm & Thời gian',
    description: 'Learn numbers and time expressions in Japanese',
    descriptionVi: 'Học số đếm và cách nói giờ bằng tiếng Nhật',
    topic: TOPICS.DAILY_LIFE,
    vocabulary: [
      { word: '一', reading: 'いち', meaning: 'một (1)', example: '一つください。', exampleMeaning: 'Cho tôi một cái.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '二', reading: 'に', meaning: 'hai (2)', example: '二人です。', exampleMeaning: 'Hai người.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '三', reading: 'さん', meaning: 'ba (3)', example: '三時に会いましょう。', exampleMeaning: 'Gặp nhau lúc 3 giờ nhé.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '十', reading: 'じゅう', meaning: 'mười (10)', example: '十分待ってください。', exampleMeaning: 'Xin đợi 10 phút.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '百', reading: 'ひゃく', meaning: 'trăm (100)', example: '百円です。', exampleMeaning: 'Giá 100 yên.', difficulty: DIFFICULTY.EASY },
      { word: '千', reading: 'せん', meaning: 'nghìn (1000)', example: '千円札がありますか。', exampleMeaning: 'Bạn có tờ 1000 yên không?', difficulty: DIFFICULTY.EASY },
      { word: '今', reading: 'いま', meaning: 'bây giờ', example: '今何時ですか。', exampleMeaning: 'Bây giờ mấy giờ?', difficulty: DIFFICULTY.EASY },
      { word: '朝', reading: 'あさ', meaning: 'buổi sáng', example: '朝ごはんを食べました。', exampleMeaning: 'Tôi đã ăn sáng.', difficulty: DIFFICULTY.EASY },
      { word: '昼', reading: 'ひる', meaning: 'buổi trưa', example: '昼ごはんは何ですか。', exampleMeaning: 'Bữa trưa ăn gì?', difficulty: DIFFICULTY.EASY },
      { word: '夜', reading: 'よる', meaning: 'buổi tối', example: '夜は涼しいです。', exampleMeaning: 'Buổi tối mát mẻ.', difficulty: DIFFICULTY.EASY },
      { word: '今日', reading: 'きょう', meaning: 'hôm nay', example: '今日は暑いです。', exampleMeaning: 'Hôm nay nóng.', difficulty: DIFFICULTY.EASY },
      { word: '明日', reading: 'あした', meaning: 'ngày mai', example: '明日学校に行きます。', exampleMeaning: 'Ngày mai tôi đi học.', difficulty: DIFFICULTY.EASY },
      { word: '昨日', reading: 'きのう', meaning: 'hôm qua', example: '昨日映画を見ました。', exampleMeaning: 'Hôm qua tôi đã xem phim.', difficulty: DIFFICULTY.EASY },
      { word: '毎日', reading: 'まいにち', meaning: 'mỗi ngày', example: '毎日勉強します。', exampleMeaning: 'Tôi học mỗi ngày.', difficulty: DIFFICULTY.EASY },
      { word: '週末', reading: 'しゅうまつ', meaning: 'cuối tuần', example: '週末何をしますか。', exampleMeaning: 'Cuối tuần bạn làm gì?', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Bây giờ" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['今日', '明日', '今', '昨日'], answer: '今', explanation: '今 (いま) = bây giờ', explanationVi: '今 (いま) = bây giờ', difficulty: DIFFICULTY.EASY },
      { question: '"百" đọc là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['せん', 'ひゃく', 'じゅう', 'まん'], answer: 'ひゃく', explanation: '百 = ひゃく = 100', explanationVi: '百 = ひゃく = 100', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "週末" = ?', type: QUIZ_TYPES.MATCHING, options: ['Cuối tuần', 'Mỗi ngày', 'Hôm qua', 'Ngày mai'], answer: 'Cuối tuần', explanation: '週末 (しゅうまつ) = cuối tuần', explanationVi: '週末 (しゅうまつ) = cuối tuần', difficulty: DIFFICULTY.EASY },
      { question: '"Buổi tối" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['朝', '昼', '夜', '今'], answer: '夜', explanation: '夜 (よる) = buổi tối', explanationVi: '夜 (よる) = buổi tối', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "___は暑いです。" (hôm nay)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '今日', explanation: '今日 (きょう) = hôm nay', explanationVi: '今日 (きょう) = hôm nay', difficulty: DIFFICULTY.EASY },
    ],
  },
];
