import { LessonData } from '../utils';
import { TOPICS, DIFFICULTY, QUIZ_TYPES } from '../constants';

export const japaneseGreetingsLessons: LessonData[] = [
  {
    title: 'Greetings (挨拶)',
    titleVi: 'Chào hỏi',
    description: 'Learn basic Japanese greetings',
    descriptionVi: 'Học các câu chào hỏi cơ bản tiếng Nhật',
    topic: TOPICS.GREETINGS,
    vocabulary: [
      { word: 'おはようございます', reading: 'ohayou gozaimasu', meaning: 'chào buổi sáng (lịch sự)', example: 'おはようございます、先生。', exampleMeaning: 'Chào buổi sáng, thầy/cô.', difficulty: DIFFICULTY.EASY },
      { word: 'こんにちは', reading: 'konnichiwa', meaning: 'xin chào (ban ngày)', example: 'こんにちは、お元気ですか。', exampleMeaning: 'Xin chào, bạn khỏe không?', difficulty: DIFFICULTY.VERY_EASY },
      { word: 'こんばんは', reading: 'konbanwa', meaning: 'chào buổi tối', example: 'こんばんは、田中さん。', exampleMeaning: 'Chào buổi tối, anh Tanaka.', difficulty: DIFFICULTY.EASY },
      { word: 'さようなら', reading: 'sayounara', meaning: 'tạm biệt', example: 'さようなら、また明日。', exampleMeaning: 'Tạm biệt, hẹn gặp lại ngày mai.', difficulty: DIFFICULTY.EASY },
      { word: 'ありがとうございます', reading: 'arigatou gozaimasu', meaning: 'cảm ơn (lịch sự)', example: 'ありがとうございます、助かりました。', exampleMeaning: 'Cảm ơn, bạn đã giúp tôi rất nhiều.', difficulty: DIFFICULTY.EASY },
      { word: 'すみません', reading: 'sumimasen', meaning: 'xin lỗi / xin phép', example: 'すみません、トイレはどこですか。', exampleMeaning: 'Xin lỗi, nhà vệ sinh ở đâu?', difficulty: DIFFICULTY.EASY },
      { word: 'お元気ですか', reading: 'ogenki desu ka', meaning: 'bạn khỏe không?', example: 'お元気ですか。元気です。', exampleMeaning: 'Bạn khỏe không? Tôi khỏe.', difficulty: DIFFICULTY.EASY },
      { word: 'はじめまして', reading: 'hajimemashite', meaning: 'rất vui được gặp (lần đầu)', example: 'はじめまして、リンです。', exampleMeaning: 'Rất vui được gặp, tôi là Linh.', difficulty: DIFFICULTY.EASY },
      { word: 'よろしくお願いします', reading: 'yoroshiku onegaishimasu', meaning: 'mong được giúp đỡ/xin chỉ giáo', example: 'よろしくお願いします。', exampleMeaning: 'Mong được giúp đỡ.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'いただきます', reading: 'itadakimasu', meaning: 'xin phép ăn (trước bữa ăn)', example: 'いただきます！おいしそう。', exampleMeaning: 'Xin phép ăn! Trông ngon quá.', difficulty: DIFFICULTY.EASY },
      { word: 'ごちそうさまでした', reading: 'gochisousama deshita', meaning: 'cảm ơn bữa ăn (sau bữa ăn)', example: 'ごちそうさまでした。おいしかったです。', exampleMeaning: 'Cảm ơn bữa ăn. Rất ngon.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'おやすみなさい', reading: 'oyasuminasai', meaning: 'chúc ngủ ngon', example: 'おやすみなさい、また明日。', exampleMeaning: 'Chúc ngủ ngon, hẹn gặp ngày mai.', difficulty: DIFFICULTY.EASY },
      { word: 'いってきます', reading: 'ittekimasu', meaning: 'tôi đi đây (khi ra khỏi nhà)', example: 'いってきます！', exampleMeaning: 'Tôi đi đây!', difficulty: DIFFICULTY.EASY },
      { word: 'ただいま', reading: 'tadaima', meaning: 'tôi về rồi', example: 'ただいま！疲れた。', exampleMeaning: 'Tôi về rồi! Mệt quá.', difficulty: DIFFICULTY.EASY },
      { word: 'お疲れ様です', reading: 'otsukaresama desu', meaning: 'vất vả rồi (chào đồng nghiệp)', example: 'お疲れ様です。今日も頑張りましたね。', exampleMeaning: 'Vất vả rồi. Hôm nay cũng cố gắng nhỉ.', difficulty: DIFFICULTY.MEDIUM },
    ],
    quizzes: [
      { question: '"Xin chào" (ban ngày) tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['おはよう', 'こんにちは', 'こんばんは', 'さようなら'], answer: 'こんにちは', explanation: 'こんにちは = xin chào (dùng ban ngày)', explanationVi: 'こんにちは = xin chào (dùng ban ngày)', difficulty: DIFFICULTY.VERY_EASY },
      { question: 'Trước khi ăn, người Nhật nói gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['ごちそうさま', 'いただきます', 'ありがとう', 'すみません'], answer: 'いただきます', explanation: 'いただきます = xin phép ăn (nói trước bữa ăn)', explanationVi: 'いただきます = xin phép ăn (nói trước bữa ăn)', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "おやすみなさい" = ?', type: QUIZ_TYPES.MATCHING, options: ['Chúc ngủ ngon', 'Tạm biệt', 'Cảm ơn', 'Xin lỗi'], answer: 'Chúc ngủ ngon', explanation: 'おやすみなさい = chúc ngủ ngon', explanationVi: 'おやすみなさい = chúc ngủ ngon', difficulty: DIFFICULTY.EASY },
      { question: '"Cảm ơn" (lịch sự) tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['すみません', 'ありがとうございます', 'よろしく', 'おはよう'], answer: 'ありがとうございます', explanation: 'ありがとうございます = cảm ơn (lịch sự)', explanationVi: 'ありがとうございます = cảm ơn (lịch sự)', difficulty: DIFFICULTY.EASY },
      { question: 'Khi về đến nhà, người Nhật nói gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['いってきます', 'ただいま', 'おかえり', 'さようなら'], answer: 'ただいま', explanation: 'ただいま = tôi về rồi (nói khi về đến nhà)', explanationVi: 'ただいま = tôi về rồi (nói khi về đến nhà)', difficulty: DIFFICULTY.EASY },
    ],
  },
  {
    title: 'Self Introduction (自己紹介)',
    titleVi: 'Giới thiệu bản thân',
    description: 'Learn to introduce yourself in Japanese',
    descriptionVi: 'Học cách giới thiệu bản thân bằng tiếng Nhật',
    topic: TOPICS.GREETINGS,
    vocabulary: [
      { word: '名前', reading: 'なまえ', meaning: 'tên', example: '名前は何ですか。', exampleMeaning: 'Tên bạn là gì?', difficulty: DIFFICULTY.EASY },
      { word: '私', reading: 'わたし', meaning: 'tôi', example: '私はベトナム人です。', exampleMeaning: 'Tôi là người Việt Nam.', difficulty: DIFFICULTY.VERY_EASY },
      { word: '出身', reading: 'しゅっしん', meaning: 'quê quán/xuất thân', example: '出身はハノイです。', exampleMeaning: 'Quê tôi ở Hà Nội.', difficulty: DIFFICULTY.EASY },
      { word: '趣味', reading: 'しゅみ', meaning: 'sở thích', example: '趣味は読書です。', exampleMeaning: 'Sở thích của tôi là đọc sách.', difficulty: DIFFICULTY.EASY },
      { word: '仕事', reading: 'しごと', meaning: 'công việc', example: '仕事はエンジニアです。', exampleMeaning: 'Công việc của tôi là kỹ sư.', difficulty: DIFFICULTY.EASY },
      { word: '学生', reading: 'がくせい', meaning: 'sinh viên', example: '私は大学生です。', exampleMeaning: 'Tôi là sinh viên đại học.', difficulty: DIFFICULTY.EASY },
      { word: '歳', reading: 'さい', meaning: 'tuổi', example: '22歳です。', exampleMeaning: 'Tôi 22 tuổi.', difficulty: DIFFICULTY.EASY },
      { word: '好き', reading: 'すき', meaning: 'thích', example: '日本語が好きです。', exampleMeaning: 'Tôi thích tiếng Nhật.', difficulty: DIFFICULTY.EASY },
      { word: '家族', reading: 'かぞく', meaning: 'gia đình', example: '家族は4人です。', exampleMeaning: 'Gia đình tôi có 4 người.', difficulty: DIFFICULTY.EASY },
      { word: '兄弟', reading: 'きょうだい', meaning: 'anh chị em', example: '兄弟は2人います。', exampleMeaning: 'Tôi có 2 anh chị em.', difficulty: DIFFICULTY.EASY },
      { word: '住んでいます', reading: 'すんでいます', meaning: 'đang sống ở', example: 'ホーチミンに住んでいます。', exampleMeaning: 'Tôi đang sống ở TP.HCM.', difficulty: DIFFICULTY.MEDIUM },
      { word: '勉強しています', reading: 'べんきょうしています', meaning: 'đang học', example: '日本語を勉強しています。', exampleMeaning: 'Tôi đang học tiếng Nhật.', difficulty: DIFFICULTY.EASY },
      { word: '将来', reading: 'しょうらい', meaning: 'tương lai', example: '将来、日本で働きたいです。', exampleMeaning: 'Tương lai, tôi muốn làm việc ở Nhật.', difficulty: DIFFICULTY.MEDIUM },
      { word: '夢', reading: 'ゆめ', meaning: 'ước mơ', example: '夢は通訳になることです。', exampleMeaning: 'Ước mơ của tôi là trở thành phiên dịch.', difficulty: DIFFICULTY.MEDIUM },
      { word: 'どうぞよろしく', reading: 'douzo yoroshiku', meaning: 'mong được giúp đỡ (thân mật)', example: 'リンです。どうぞよろしく。', exampleMeaning: 'Tôi là Linh. Mong được giúp đỡ.', difficulty: DIFFICULTY.EASY },
    ],
    quizzes: [
      { question: '"Tên" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['仕事', '名前', '趣味', '出身'], answer: '名前', explanation: '名前 (なまえ) = tên', explanationVi: '名前 (なまえ) = tên', difficulty: DIFFICULTY.EASY },
      { question: 'Điền: "___はベトナム人です。" (tôi)', type: QUIZ_TYPES.FILL_BLANK, options: [], answer: '私', explanation: '私 (わたし) = tôi', explanationVi: '私 (わたし) = tôi', difficulty: DIFFICULTY.VERY_EASY },
      { question: '"Sở thích" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['仕事', '出身', '趣味', '家族'], answer: '趣味', explanation: '趣味 (しゅみ) = sở thích', explanationVi: '趣味 (しゅみ) = sở thích', difficulty: DIFFICULTY.EASY },
      { question: 'Nối: "家族" = ?', type: QUIZ_TYPES.MATCHING, options: ['Gia đình', 'Anh chị em', 'Bạn bè', 'Đồng nghiệp'], answer: 'Gia đình', explanation: '家族 (かぞく) = gia đình', explanationVi: '家族 (かぞく) = gia đình', difficulty: DIFFICULTY.EASY },
      { question: '"Ước mơ" tiếng Nhật là gì?', type: QUIZ_TYPES.MULTIPLE_CHOICE, options: ['将来', '夢', '好き', '趣味'], answer: '夢', explanation: '夢 (ゆめ) = ước mơ', explanationVi: '夢 (ゆめ) = ước mơ', difficulty: DIFFICULTY.MEDIUM },
    ],
  },
];
